### ISSUE TITLE
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4

### ISSUE THREAD

**Issue by BigData-YC** [ververica/flink-cdc-connectors#1030]
Caused by: org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1648695944000, eventType=UPDATE_ROWS, serverId=4194815432, headerLength=19, dataLength=3713, nextPosition=24870909, flags=0}
		at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241)
		at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218)
		at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:607)
		at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1104)
		at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:955)
		at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595)
		at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.RuntimeException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1648695944000, eventType=UPDATE_ROWS, serverId=4194815432, headerLength=19, dataLength=3713, nextPosition=24870909, flags=0}
		at io.debezium.connector.mysql.BinlogReader.handleServerIncident(BinlogReader.java:675)
		at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:590)
		... 5 more
	Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1648695944000, eventType=UPDATE_ROWS, serverId=4194815432, headerLength=19, dataLength=3713, nextPosition=24870909, flags=0}
		at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:304)
		at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:227)
		at io.debezium.connector.mysql.BinlogReader$1.nextEvent(BinlogReader.java:252)
		at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:934)
		... 3 more
	Caused by: java.io.EOFException
		at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:192)
		at java.io.InputStream.read(InputStream.java:170)
		at java.io.InputStream.skip(InputStream.java:224)
		at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:219)
		at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300)
		... 6 more

**Comment by GOODBOY008** [comment]
@BigData-YC  Can you supply more detail info.

**Comment by BuddyJack** [comment]
2.2测试也是遇到了这个问题

**Comment by GOODBOY008** [comment]
> 2.2测试也是遇到了这个问题
可以提供下重现的case吗？

**Comment by BuddyJack** [comment]
邮件已收到！谢谢！                       薛超

**Comment by PatrickRen** [comment]
@BuddyJack Could you check the configuration of your MySQL binlog? `binlog-format` should be `row` and `binlog_row_image` should be `full`. 

https://debezium.io/documentation/reference/stable/connectors/mysql.html#enable-mysql-binlog

**Comment by zhilinli123** [comment]
How did you solve the problem at last?

**Comment by BuddyJack** [comment]
邮件已收到！谢谢！                       薛超

**Comment by ChenShuai1981** [comment]
I met the same issue with version 2.2.1

> Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler.setProducerThrowable(MySqlErrorHandler.java:72)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1185)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:973)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)
	... 1 more
Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1665379665000, eventType=WRITE_ROWS, serverId=1940348705, headerLength=19, dataLength=209, nextPosition=501210427, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1146)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1665379665000, eventType=WRITE_ROWS, serverId=1940348705, headerLength=19, dataLength=209, nextPosition=501210427, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945)
	... 3 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:113)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:104)
	at io.debezium.connector.mysql.RowDeserializers.deserializeVarString(RowDeserializers.java:264)
	at io.debezium.connector.mysql.RowDeserializers$WriteRowsDeserializer.deserializeVarString(RowDeserializers.java:192)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:189)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:143)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	... 6 more

**Comment by BuddyJack** [comment]
邮件已收到！谢谢！                       薛超

**Comment by leonardBang** [comment]
Duplicated with #1030, let's track this issue in #1030

**Comment by BuddyJack** [comment]
邮件已收到！谢谢！                       薛超

**Comment by BuddyJack** [comment]
邮件已收到！谢谢！                       薛超
