### ISSUE TITLE
ORA-00600: internal error code, arguments: [krvrdccs10], [], [], [], [], [], [], [], [], [], [], []

### ISSUE THREAD

**Issue by hehetown** [ververica/flink-cdc-connectors#1076]
**Describe the bug(Please use English)**
-----------------------
ORA-00600: internal error code, arguments: [krvrdccs10], [], [], [], [], [], [], [], [], [], [], []
----------------------
**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.2.0
 - Database and version:  oracle 19c

**To Reproduce**
1. Thes test data :
2. The test code :
DROP TABLE IF EXISTS source_Test;
CREATE TABLE source_Test (
    TESTID INT,
    TESTCONTENT STRING,
    PRIMARY KEY (TESTID) NOT ENFORCED
  ) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = '10.10.10.100',
    'port' = '1521',
    'username' = 'test',
    'password' = 'test!2324',
    'database-name' = 'testpdb',
    'schema-name' = 'test',  
    'table-name' = 'testTable',  
    'debezium.database.hostname' = '10.10.10.100',  
    'debezium.database.port' = '1521',  
    'debezium.database.server.name' = 'orclcdb',  
    'debezium.database.dbname' = 'orclcdb',  
    'debezium.database.pdb.name' = 'testpdb',  
    'debezium.database.user' = 'c##dbzuser',  
    'debezium.database.password' = 'dbz@1235',  
    'debezium.log.mining.strategy' = 'online_catalog', 
    'debezium.log.tasks.max' = '1'
  );
3. The error :
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
Caused by: java.sql.SQLException: ORA-00600: internal error code, arguments: [krvrdccs10], [], [], [], [], [], [], [], [], [], [], []

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3713) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1167) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:184) ~[flink-sql-connector-oracle-cdc-2.2.0.jar:2.2.0]
	... 7 more

**Additional Description**

**Comment by PatrickRen** [comment]
@hehetown Looks like an issue inside `LogMinerStreamingChangeEventSource` from Debezium Oracle connector. Could you check if there's any information about this exception in Debezium community?

**Comment by hehetown** [comment]
你好！邮件已经收到了。谢谢。

**Comment by hehetown** [comment]
@PatrickRen Thank you, but I checked Debezium Community and could not find relevant treatment methods, so I come here for help.

**Comment by luckes-yang** [comment]
I have the same problem， How did you solve it？

**Comment by wl3207601** [comment]
I have the same problem too， How did you solve it？

**Comment by gong** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 
cc @GOODBOY008

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
