### ISSUE TITLE
flink-connector-debezium:2.2.0 and flink-connector-kafka_2.11:1.13.5 conflict

### ISSUE THREAD

**Issue by ryuunami** [ververica/flink-cdc-connectors#1094]
**Describe the bug(Please use English)**
flink-connector-debezium:2.2.0 and flink-connector-kafka_2.11:1.13.5 conflict

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.2.0
 - Database and version: 

**To Reproduce**
<flink.version>1.13.5</flink.version>
<flink.cdc.version>2.2.0</flink.cdc.version>
        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-connector-mysql-cdc</artifactId>
            <version>${flink.cdc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>
**Additional Description**
同时引入cdc和flink-connector-kafka，启动就会报错：
java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/ThreadUtils
	at com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore.start(FlinkOffsetBackingStore.java:152) ~[flink-connector-debezium-2.2.0.jar:2.2.0]
	at com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore.configure(FlinkOffsetBackingStore.java:71) ~[flink-connector-debezium-2.2.0.jar:2.2.0]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:690) [debezium-embedded-1.5.4.Final.jar:1.5.4.Final]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) [debezium-embedded-1.5.4.Final.jar:1.5.4.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
19:49:50,611 ERROR com.ververica.cdc.debezium.internal.Handover                 [] - Reporting error:
java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/ThreadUtils
	at com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore.start(FlinkOffsetBackingStore.java:152) ~[flink-connector-debezium-2.2.0.jar:2.2.0]
	at com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore.configure(FlinkOffsetBackingStore.java:71) ~[flink-connector-debezium-2.2.0.jar:2.2.0]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:690) [debezium-embedded-1.5.4.Final.jar:1.5.4.Final]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) [debezium-embedded-1.5.4.Final.jar:1.5.4.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.utils.ThreadUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 7 more

**Comment by ryuunami** [comment]
thx，add Kafka-client:2.7 into pom  can solve this problem
