### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.kafka.connect.data.Schema

### ISSUE THREAD

**Issue by cqlyiyeshu** [ververica/flink-cdc-connectors#1119]
**Describe the bug(Please use English)**
when I Etl data from mysql table1 to table2, I got an error: Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.data.Schema

**Environment :**
 - Flink version :  1.13.6-2.12
 - Flink CDC version: 2.2.0
 - Database and version: Mysql 5.27.36

**To Reproduce**
1. Thes test data :
bin/sql-client.sh

CREATE TABLE source_cdc_advert_order (
    id bigint,
    coupon_id bigint,
    order_sn varchar,
    total_amount decimal(10,2),
    order_time timestamp(3),
    primary key(id) not enforced
 ) WITH (
'connector' = 'mysql-cdc',
'scan.incremental.snapshot.enabled' = 'true',
'hostname' = '*****',
'port' = '3306',
'server-id' = '1',
'username' = '',
'password' = '',
'database-name' = 'flinkcdc',
'table-name' = 'table1'
);

CREATE TABLE target_cdc_advert_order (
    id bigint,
    coupon_id bigint,
    order_sn varchar,
    total_amount decimal(10,2),
    order_time timestamp(3),
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector.type' = 'jdbc',
    'connector.url' = 'jdbc:mysql://*****:3306/flinkcdc',
    'connector.table' = 'table2',
    'connector.driver' = 'com.mysql.cj.jdbc.Driver',
    'connector.username' = '',
    'connector.password' = ''
  );

insert into table2 select * from table2;
3. The error :
[INFO] Submitting SQL update statement to the cluster...
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/connect/data/Schema
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1644)
        at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:79)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:520)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:494)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:391)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1134)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
        at org.apache.flink.util.SerializedValue.<init>(SerializedValue.java:62)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobVertex(StreamingJobGraphGenerator.java:594)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createChain(StreamingJobGraphGenerator.java:454)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.setChaining(StreamingJobGraphGenerator.java:375)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:176)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:114)
        at org.apache.flink.streaming.api.graph.StreamGraph.getJobGraph(StreamGraph.java:959)
        at org.apache.flink.client.StreamGraphTranslator.translateToJobGraph(StreamGraphTranslator.java:50)
        at org.apache.flink.client.FlinkPipelineTranslationUtil.getJobGraph(FlinkPipelineTranslationUtil.java:39)
        at org.apache.flink.client.deployment.executors.PipelineExecutorUtils.getJobGraph(PipelineExecutorUtils.java:56)
        at org.apache.flink.client.deployment.executors.AbstractSessionClusterExecutor.execute(AbstractSessionClusterExecutor.java:67)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1956)
        at org.apache.flink.table.planner.delegation.ExecutorBase.executeAsync(ExecutorBase.java:55)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:759)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:742)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeModifyOperations$4(LocalExecutor.java:226)
        at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:90)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeModifyOperations(LocalExecutor.java:226)
        at org.apache.flink.table.client.cli.CliClient.callInserts(CliClient.java:518)
        at org.apache.flink.table.client.cli.CliClient.callInsert(CliClient.java:507)
        at org.apache.flink.table.client.cli.CliClient.callOperation(CliClient.java:409)
        at org.apache.flink.table.client.cli.CliClient.lambda$executeStatement$0(CliClient.java:327)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:327)
        at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297)
        at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221)
        at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151)
        at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95)
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.data.Schema
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 69 more

Shutting down the session...

**Comment by cqlyiyeshu** [comment]
把flink换成1.13.6-2.11 就可以了

**Comment by slankka** [comment]
Scala is not the reason.

Flink-1.13.5
Flink-CDC 2.2.1

The reason may be debezium-embedded who depends on `org.apache.kafka:connect-api`

**Comment by yanye666** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/42414099/21d7d665-37ca-4f41-a84d-a79f7a7309aa)
<img width="960" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/42414099/c46a74ff-1347-4348-b4e7-e4b7e15d07b4">

我吧这两个删除了就好了；
因为我刚开始是一个一个引用源包，没有使用打的聚合包，导致后面引入聚合包冲突了
