### ISSUE TITLE
MySqlChangeEventSourceExampleTest encounter NPL in JdbcSourceStreamFetcher.hasEnterPureBinlogPhase

### ISSUE THREAD

**Issue by molsionmo** [ververica/flink-cdc-connectors#1122]
**Describe the bug(Please use English)**
com.ververica.cdc.connectors.base.MySqlChangeEventSourceExampleTest in bin log phase will encounter NPL in JdbcSourceStreamFetcher.hasEnterPureBinlogPhase. maxSplitHighWatermarkMap is null.

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.3.SNOPSHOT
 - Database and version: Mysql 5.7

**To Reproduce**
1. Thes test data :
 Snapshot phase is executed. And then update one row data.
2. The test code :
com.ververica.cdc.connectors.base.MySqlChangeEventSourceExampleTest
4. The error :
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:223) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623) ~[flink-streaming-java_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) ~[flink-runtime_2.11-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-runtime_2.11-1.13.5.jar:1.13.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.RuntimeException: SplitFetcher thread 1 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.lang.NullPointerException
	at com.ververica.cdc.connectors.base.source.reader.external.JdbcSourceStreamFetcher.hasEnterPureBinlogPhase(JdbcSourceStreamFetcher.java:180) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.external.JdbcSourceStreamFetcher.shouldEmit(JdbcSourceStreamFetcher.java:152) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.external.JdbcSourceStreamFetcher.pollSplitRecords(JdbcSourceStreamFetcher.java:112) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.JdbcSourceSplitReader.fetch(JdbcSourceSplitReader.java:68) ~[classes/:?]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:140) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more

**Additional Description**

**Comment by molsionmo** [comment]
@fuyun2024 can you fix it and use a new pull request?

**Comment by fuyun2024** [comment]
@molsionmo OK, I will support it later

**Comment by fuyun2024** [comment]
hi @molsionmo   me add some questions ：
Throw RuntimeException timely in snapshot scan phase ： https://github.com/ververica/flink-cdc-connectors/pull/1098
