### ISSUE TITLE
Flink CDC base registers the identical history engine on multiple tasks

### ISSUE THREAD

**Issue by fuyun2024** [ververica/flink-cdc-connectors#1130]
**Describe the bug(Please use English)**
Flink CDC base registers the identical history engine on multiple tasks

**Additional Description**

203145 [Source Data Fetcher for Source: OracleParallelSource (4/4)#0] ERROR org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) [flink-connector-base-1.13.5.jar:1.13.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:47) ~[debezium-core-1.6.4.Final.jar:1.6.4.Final]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.validateAndLoadDatabaseHistory(OracleSourceFetchTaskContext.java:235) ~[classes/:?]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.configure(OracleSourceFetchTaskContext.java:107) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.external.JdbcSourceScanFetcher.submitTask(JdbcSourceScanFetcher.java:79) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.JdbcSourceSplitReader.checkSplitOrStartNext(JdbcSourceSplitReader.java:133) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.JdbcSourceSplitReader.fetch(JdbcSourceSplitReader.java:65) ~[classes/:?]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:140) ~[flink-connector-base-1.13.5.jar:1.13.5]
	... 6 more
203138 [Source Data Fetcher for Source: OracleParallelSource (2/4)#0] ERROR org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) [flink-connector-base-1.13.5.jar:1.13.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:47) ~[debezium-core-1.6.4.Final.jar:1.6.4.Final]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.validateAndLoadDatabaseHistory(OracleSourceFetchTaskContext.java:235) ~[classes/:?]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.configure(OracleSourceFetchTaskContext.java:107) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.external.JdbcSourceScanFetcher.submitTask(JdbcSourceScanFetcher.java:79) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.JdbcSourceSplitReader.checkSplitOrStartNext(JdbcSourceSplitReader.java:133) ~[classes/:?]
	at com.ververica.cdc.connectors.base.source.reader.JdbcSourceSplitReader.fetch(JdbcSourceSplitReader.java:65) ~[classes/:?]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:140) ~[flink-connector-base-1.13.5.jar:1.13.5]
	... 6 more

![image](https://user-images.githubusercontent.com/26080592/165664614-8c1b96d8-a006-4ed8-adca-3d4594a0e701.png)

**Comment by molsionmo** [comment]
**Environment :**

Flink version : 1.13.5
Flink CDC version: 2.3.SNOPSHOT
Database and version: Mysql 5.7


**To Reproduce**
Steps to reproduce the behavior:

1. Thes test data :NONE

2. The test code :
com.ververica.cdc.connectors.base.MySqlChangeEventSourceExampleTest#testConsumingAllEvents
change code to:(just add .splitSize(3))
inventoryDatabase.createAndInitialize();
        JdbcIncrementalSource<String> mySqlChangeEventSource =
                new MySqlSourceBuilder()
                        .hostname(MYSQL_CONTAINER.getHost())
                        .port(MYSQL_CONTAINER.getDatabasePort())
                        .databaseList(inventoryDatabase.getDatabaseName())
                        .tableList(inventoryDatabase.getDatabaseName() + ".products")
                        .username(inventoryDatabase.getUsername())
                        .password(inventoryDatabase.getPassword())
                        .serverId("5401-5404")
                        .splitSize(3)
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(true) // output the schema changes as well
                        .build();
