### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to java.lang.Long when using oracle connector

### ISSUE THREAD

**Issue by MichaelXucf** [ververica/flink-cdc-connectors#121]
When I test oracle connector using DebeziumSourceFunction, it throw exception after a checkpoint Completed as following.
```java
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at io.debezium.connector.oracle.xstream.XstreamStreamingChangeEventSource.commitOffset(XstreamStreamingChangeEventSource.java:113) ~[debezium-connector-oracle-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.commitOffset(ChangeEventSourceCoordinator.java:146) ~[debezium-core-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.connector.common.BaseSourceTask.commit(BaseSourceTask.java:235) ~[debezium-core-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.embedded.EmbeddedEngine.commitOffsets(EmbeddedEngine.java:952) ~[debezium-embedded-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.embedded.EmbeddedEngine.maybeFlush(EmbeddedEngine.java:926) ~[debezium-embedded-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.embedded.EmbeddedEngine$4.markBatchFinished(EmbeddedEngine.java:907) ~[debezium-embedded-1.4.1.Final.jar:1.4.1.Final]
	at io.debezium.embedded.ConvertingEngineBuilder$1.markBatchFinished(ConvertingEngineBuilder.java:94) ~[debezium-embedded-1.4.1.Final.jar:1.4.1.Final]
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.commitOffset(DebeziumChangeConsumer.java:230) ~[classes/:?]
	at com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction.notifyCheckpointComplete(DebeziumSourceFunction.java:431) ~[classes/:?]
```

the code of the ```XstreamStreamingChangeEventSource.commitOffset``` is:
```java
   @Override
    public void commitOffset(Map<String, ?> offset) {
        if (xsOut != null) {
            LOGGER.debug("Sending message to request recording of offsets to Oracle");
            final LcrPosition lcrPosition = LcrPosition.valueOf((String) offset.get(SourceInfo.LCR_POSITION_KEY));
            final Long scn = (Long) offset.get(SourceInfo.SCN_KEY);// this is line 113
            // We can safely overwrite the message even if it was not processed. The watermarked will be set to the highest
            // (last) delivered value in a single step instead of incrementally
            sendPublishedPosition(lcrPosition, scn);
        }
    }
```

The reason is that the data type in ```DebeziumOffset``` has been changed. For example,before serialized by DebeziumOffsetSerializer, the DebeziumOffset is: 
```
{sourcePartition={server=oracle_binlog_source}, sourceOffset={snapshot=true, scn=1644059(Long), snapshot_completed=true}}
```
The data type of the **scn** is **Long**. after serialized in method ```DebeziumChangeConsumer.snapshotCurrentState()``` by ```DebeziumOffsetSerializer.serialize```,  and deserialized in method DebeziumSourceFunction.notifyCheckpointComplete by ```DebeziumOffsetSerializer.deserialize```，the DebeziumOffset is: 
```
{sourcePartition={server=oracle_binlog_source}, sourceOffset={snapshot=true, scn=1644059(Integer), snapshot_completed=true}}
```
The data type of the **scn** has been changed to  **Integer**. 

Using the following code can reproduce the problem:

```java
    @Test
    public void TestJsonSerializer() throws IOException {
        Map<String, Object> sourcePartition = new HashMap<>();
        sourcePartition.put("server", "oracle_binlog_source");

        Map<String, Object> sourceOffset = new HashMap<>();
        sourceOffset.put("snapshot", true);
        sourceOffset.put("scn", 1657160L);
        sourceOffset.put("snapshot_completed", false);

        DebeziumOffset offset = new DebeziumOffset();
        offset.setSourcePartition(sourcePartition);
        offset.setSourceOffset(sourceOffset);

        System.out.println("before serialize: "+offset);
        Assert.assertEquals(1657160L, offset.sourceOffset.get("scn"));

        byte[] serializedOffset = DebeziumOffsetSerializer.INSTANCE.serialize(offset);

        DebeziumOffset deserializeOffset = DebeziumOffsetSerializer.INSTANCE.deserialize(serializedOffset);
        System.out.println("after deserialize:"+deserializeOffset);
        Assert.assertEquals(1657160L, deserializeOffset.sourceOffset.get("scn"));
    }
```

This issue is caused by the ```Jackson.ObjectMapper``` used in the DebeziumOffsetSerializer. 
To avoid this problem ,we should add ```DeserializationFeature.USE_LONG_FOR_INTS``` when deserialize.

change the code 
```java
   public DebeziumOffset deserialize(byte[] bytes) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        return objectMapper.readValue(bytes, DebeziumOffset.class);
    }
```
to
```java
    public DebeziumOffset deserialize(byte[] bytes) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.enable(DeserializationFeature.USE_LONG_FOR_INTS);
        return objectMapper.readValue(bytes, DebeziumOffset.class);
    }
```

I have commit a pull request #119 to fixed this also. @wuchong 

--------------------------------------update------------------------------------------
It may be not a good solution to fixed this problem becase if we has a field of Integer type in the DebeziumOffset, after serialized and deserialized, the data type of the field will be changed to Long. So I wonder is it necessary to serialize and deserialize the variable DebeziumOffset?

**Comment by MichaelXucf** [comment]
This is a snapshot for this issue when I test the oracle connector.
<img width="1555" alt="DebeziumOffset-001" src="https://user-images.githubusercontent.com/16697434/111023576-d7394880-8414-11eb-8d54-b7a40c624886.png">

**Comment by MichaelXucf** [comment]
I wonder is it necessary to serialize and deserialize the variable DebeziumOffset?
