### ISSUE TITLE
 ORA-26824: user-defined XStream callback error

### ISSUE THREAD

**Issue by hehetown** [ververica/flink-cdc-connectors#1224]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :   1.13.6
 - Flink CDC version:  2.2.1
 - Database and version:  oracle19.7
     'debezium.database.connection.adapter' = 'xstream',
**To Reproduce**
1. Thes test data :
2'debezium.database.connection.adapter' = 'xstream',
3. The test code :
4. The error :

Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.

at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at io.debezium.connector.oracle.xstream.XstreamStreamingChangeEventSource.execute(XstreamStreamingChangeEventSource.java:112) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]

at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]

Caused by: oracle.streams.StreamsException: ORA-26824: user-defined XStream callback error

XStreamOut DeliverChunk: exception thrown in processChunk callback.

at oracle.streams.XStreamOut.XStreamOutReceiveLCRCallbackNative(Native Method) ~[xstreams.jar:?]

at oracle.streams.XStreamOut.receiveLCRCallback(XStreamOut.java:465) ~[xstreams.jar:?]

at io.debezium.connector.oracle.xstream.XstreamStreamingChangeEventSource.execute(XstreamStreamingChangeEventSource.java:94) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]

at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]

2022-05-26 02:00:26,989 INFO org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - Disconnect job manager 8c0a29fa9bd20b789d673ad2da584f9d@akka.tcp://flink@10.233.111.79:6123/user/rpc/jobmanager_2 for job 00000000000000000000000000000000 from the resource manager.

2022-05-26 02:00:26,991 INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint [] - Shutting KubernetesApplicationClusterEntrypoint down with application status FAILED. Diagnostics null.

2022-05-26 02:00:26,993 INFO org.apache.flink.runtime.jobmaster.MiniDispatcherRestEndpoint [] - Shutting down rest endpoint.

**Additional Description**

**Comment by molsionmo** [comment]
@hehetown Can you describe the oracle database configuration that with XStream Outbound Server?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
