### ISSUE TITLE
[tidb-cdc]tidb-cdc supports TiDB v6.1.0

### ISSUE THREAD

**Issue by RaiToKU** [ververica/flink-cdc-connectors#1296]
**Is your feature request related to a problem? Please describe.**
tidb-cdc connector occur error with tidb v6.1.0
**Environment :**
 - Flink version :  1.13.6|1.14.4
 - Flink CDC version: 2.2.0
 - Database and version: v6.1.0
 
Tidb cdc connector will occur error with two situation listd below
(1) The job started to get error
```
org.tikv.common.exception.TiClientInternalException: Error scanning data from region.
	at org.tikv.common.operation.iterator.ScanIterator.cacheLoadFails(ScanIterator.java:115) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.operation.iterator.ConcreteScanIterator.hasNext(ConcreteScanIterator.java:105) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.codec.MetaCodec.hashGetFields(MetaCodec.java:117) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.catalog.CatalogTransaction.getDatabases(CatalogTransaction.java:75) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.catalog.Catalog$CatalogCache.loadDatabases(Catalog.java:195) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.catalog.Catalog$CatalogCache.<init>(Catalog.java:136) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.catalog.Catalog$CatalogCache.<init>(Catalog.java:124) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.catalog.Catalog.<init>(Catalog.java:44) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.common.TiSession.getCatalog(TiSession.java:357) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.open(TiKVRichParallelSourceFunction.java:104) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:100) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:110) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:711) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:687) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_311]
```
(2) The job ran for a while with an error
```
2022-06-21 09:19:45,669 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.125:20160] is not reachable
2022-06-21 09:19:46,270 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.125:20160] recovers to be reachable
2022-06-21 09:19:48,070 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.125:20160] is not reachable
2022-06-21 09:19:48,672 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.125:20160] recovers to be reachable
2022-06-21 09:19:50,826 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.123:20160] is not reachable
2022-06-21 09:19:50,863 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.123:20160] recovers to be reachable
2022-06-21 09:19:54,069 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.124:20160] is not reachable
2022-06-21 09:19:56,561 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [10.2.8.124:20160] recovers to be reachable
2022-06-21 09:19:56,721 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: TableSourceScan(table=[[default_catalog, default_database, retail_pay]], fields=[id, is_deleted, create_time, update_time,  pay_order_no, pay_type, model_type, data_source, actual_amount, tenant_id]) (3/3) (229f59d374735997b1fdcdc56b5bbe8e) switched from RUNNING to FAILED on container_e31_1653990537273_0218_01_000002 @ amb084 (dataPort=35215).
java.lang.NullPointerException: null
	at org.tikv.cdc.CDCClient.getMinResolvedTs(CDCClient.java:100) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.cdc.CDCClient.handleErrorEvent(CDCClient.java:230) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.tikv.cdc.CDCClient.get(CDCClient.java:92) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.readChangeEvents(TiKVRichParallelSourceFunction.java:199) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:136) ~[flink-sql-connector-tidb-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
2022-06-21 09:19:56,754 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - Calculating tasks to restart to recover the failed task 9cc85f2801967b977e1ff98f7c76ea3c_2.
2022-06-21 09:19:56,756 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - 6 tasks should be restarted to recover the failed task 9cc85f2801967b977e1ff98f7c76ea3c_2. 
2022-06-21 09:19:56,762 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job DWDOrder (d50fb172ee2ab7e2fcfa98a3a29d47b5) switched from state RUNNING to FAILING.
```
**Describe the solution you'd like**
tidb-cdc supports tidb v6.1.0

**Describe alternatives you've considered**
etc.

**Comment by GOODBOY008** [comment]
@RaiToKU  Please make your flink cluster can connect tikv's config `advertise-addr`.

**Comment by RaiToKU** [comment]
Thx，I close the issue.
