### ISSUE TITLE
flink cdc sqlserver bug。

### ISSUE THREAD

**Issue by lpn666** [ververica/flink-cdc-connectors#1323]
**Describe the bug(Please use English)**

**Environment :**  
 - Flink version :  flink-14.4
 - Flink CDC version:  2.2.1
 - Database and version:  sqlserver 2014

**To Reproduce**
1. Thes test data : 
2. The test code :
CREATE TABLE if not exists orders (
 ID int ,
	UserName varchar(20) ,
	Code varchar(20) ,
	DisplayName varchar(30) ,
	Nationality varchar(10) ,
	Sex varchar(5) ,
	BirthDay timestamp ,
	IDCardNumber varchar(20) ,
    PRIMARY KEY (ID) NOT ENFORCED
) WITH (
    'connector' = 'sqlserver-cdc',
    'hostname' = 'localhost',
    'port' = '1433',
    'username' = 'sa',
    'password' = 'test',
    'database-name' = 'yddx',
    'schema-name' = 'dbo',
    'table-name' = 'Users'
);

select * from orders;

3. The error :
Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.NoClassDefFoundError: io/debezium/connector/sqlserver/SqlServerConnector
	at com.ververica.cdc.connectors.sqlserver.SqlServerSource$Builder.build(SqlServerSource.java:119)
	at com.ververica.cdc.connectors.sqlserver.table.SqlServerTableSource.getScanRuntimeProvider(SqlServerTableSource.java:142)
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:452)
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:160)
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.convertSourceToRel(DynamicSourceUtils.java:124)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:85)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:177)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:169)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:1057)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:1026)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:301)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$parseStatement$1(LocalExecutor.java:172)
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:88)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.parseStatement(LocalExecutor.java:172)
	at org.apache.flink.table.client.cli.CliClient.parseCommand(CliClient.java:396)
	at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:324)
	at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297)
	at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221)
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95)
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
	... 1 more
Caused by: java.lang.ClassNotFoundException: io.debezium.connector.sqlserver.SqlServerConnector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

**Additional Description**

**Comment by lpn666** [comment]
I'm sure that I have put the  flink-connector-sqlserver-cdc  jar file into the lib path .

**Comment by gong** [comment]
@lpn666 Maybe you need use [flink-sql-connector-sqlserver-cdc-2.2.1.jar](https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-sqlserver-cdc/2.2.1/flink-sql-connector-sqlserver-cdc-2.2.1.jar)

**Comment by lpn666** [comment]
> @lpn666 Maybe you need use [flink-sql-connector-sqlserver-cdc-2.2.1.jar](https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-sqlserver-cdc/2.2.1/flink-sql-connector-sqlserver-cdc-2.2.1.jar)

That's the version I used.  It's doesn't work  well  either.

**Comment by gong** [comment]
> 

Is it same exception, `Caused by: java.lang.ClassNotFoundException io.debezium.connector.sqlserver.SqlServerConnector`? I decompile the jar [flink-sql-connector-sqlserver-cdc-2.2.1.jar](https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-sqlserver-cdc/2.2.1/flink-sql-connector-sqlserver-cdc-2.2.1.jar) that I can find `io.debezium.connector.sqlserver.SqlServerConnector`

**Comment by lpn666** [comment]
> 
wow ! That's amazing, now I'm using the aliyun maven Repositories  and my jar file only 37KB,  at the same time , it's 11MB in  central。
Thanks so much and have a good day.
![image](https://user-images.githubusercontent.com/26716574/176116862-dd06ae4a-8174-40f3-b7d0-1291301af0db.png)
