### ISSUE TITLE
flink cdc  checkpoint  oom 

### ISSUE THREAD

**Issue by Chosen123Wang** [ververica/flink-cdc-connectors#1338]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version:  2.2
 - Database and version: MySQL 8.0 

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

2022-07-03 14:41:14
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source:MySQL Source' (operator bc764cd8ddf7a0cff126f51c16239658).
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:545)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:231)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorProvider$CoordinatorExecutorThreadFactory.lambda$new$0(SourceCoordinatorProvider.java:101)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorProvider$CoordinatorExecutorThreadFactory.uncaughtException(SourceCoordinatorProvider.java:124)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.lambda$runInCoordinatorThread$6(SourceCoordinatorContext.java:255)
	at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.writeCheckpointBytes(SourceCoordinator.java:389)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.toBytes(SourceCoordinator.java:370)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$checkpointCoordinator$5(SourceCoordinator.java:244)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator$$Lambda$1148/1173738638.run(Unknown Source)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator$$Lambda$827/48172322.run(Unknown Source)
	at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40)
	... 7 more

**Comment by fuyun2024** [comment]
You can try to increase the memory of jobmanager

**Comment by ruanhang1993** [comment]
Reopen when there is update.
