### ISSUE TITLE
Flink cdc如何读取阿里的DRDS，是读取代理节点还是分别读取各个节点？

### ISSUE THREAD

**Issue by qingfengKnight** [ververica/flink-cdc-connectors#138]
Caused by: org.apache.kafka.connect.errors.ConnectException: [12330401f20e6000][172.16.176.72:3306][sdm]Unknown command Error code: 1047; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:1142) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:962) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: [12330401f20e6000][172.16.176.72:3306][sdm]Unknown command
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:926) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
