### ISSUE TITLE
[mysql] Don't support MySQL type 'INT UNSIGNED ZEROFILL' yet.

### ISSUE THREAD

**Issue by yd0906** [ververica/flink-cdc-connectors#1462]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version:  2.2.1
 - Database and version:  mysql5.6

**To Reproduce**
1. The test data :
2. The test code :
3. The error : Don't support MySQL type 'INT UNSIGNED ZEROFILL' yet.

**Additional Description**
Caused by: java.lang.UnsupportedOperationException: Don't support MySQL type 'INT UNSIGNED ZEROFILL' yet.
	at com.ververica.cdc.connectors.mysql.schema.MySqlTypeUtils.convertFromColumn(MySqlTypeUtils.java:131)
	at com.ververica.cdc.connectors.mysql.schema.MySqlTypeUtils.fromDbzColumn(MySqlTypeUtils.java:72)
	at com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter.isEvenlySplitColumn(ChunkSplitter.java:272)
	at com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter.splitTableIntoChunks(ChunkSplitter.java:143)
	at com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter.generateSplits(ChunkSplitter.java:85)

**Comment by ruanhang1993** [comment]
Could you please provide a test about this?
This type test should already be contained in `MySqlConnectorITCase#testMysql57AllDataTypes`.

**Comment by Jiabao-Sun** [comment]
Hi @yd0906, this problem seems to be fixed by #1197 and will be released in the next version.
You can use the master branch to package it yourself, or patch it from that commit.
