### ISSUE TITLE
Oracle CDC 在CDB+PDB模式中未切换session导致的权限问题

### ISSUE THREAD

**Issue by luckes-yang** [ververica/flink-cdc-connectors#1483]
**Describe the bug(Please use English)**
I'm sure the cdc user has right privileges,
may be when exec sql as "SELECT dbms_metadata.get_ddl('TABLE','MYTEST','DW_TEST') FROM DUAL", it's not change the container to pdb?

**Environment :**
 - Flink version :  1.15.1
 - Flink CDC version: 2.3-SNAPSHOT
 - Database and version: 19c cdb+pdb

**To Reproduce**
1. The test data :
2. The test code :
3. The error :
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1012)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1362)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:369)
        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:648)
        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:517)
        at io.debezium.connector.oracle.OracleConnection.getTableMetadataDdl(OracleConnection.java:395)
        at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.getTableMetadataDdl(LogMinerQueryResultProcessor.java:364)
        at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.dispatchSchemaChangeEventAndGetTableForNewCapturedTable(LogMinerQueryResultProcessor.java:344)
        at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.getTableForDmlEvent(LogMinerQueryResultProcessor.java:323)
        at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.processResult(LogMinerQueryResultProcessor.java:257)
        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:204)
        ... 8 more
Caused by: Error : 31603, Position : 7, Sql = SELECT dbms_metadata.get_ddl('TABLE','MYTEST','DW_TEST') FROM DUAL, OriginalSql = SELECT dbms_metadata.get_ddl('TABLE','MYTEST','DW_TEST') FROM DUAL, Error Msg = ORA-31603: 对象 "MYTEST" 属于类型 TABLE, 在方案 "DW_TEST" 中未找到
ORA-06512: 在 "SYS.DBMS_METADATA", line 6731
ORA-06512: 在 "SYS.DBMS_SYS_ERROR", line 105
ORA-06512: 在 "SYS.DBMS_METADATA", line 2588
ORA-06512: 在 "SYS.DBMS_METADATA", line 2827
ORA-06512: 在 "SYS.DBMS_METADATA", line 3608
ORA-06512: 在 "SYS.DBMS_METADATA", line 5008
ORA-06512: 在 "SYS.DBMS_METADATA", line 5336
ORA-06512: 在 "SYS.DBMS_METADATA", line 6702
ORA-06512: 在 "SYS.DBMS_METADATA", line 9734

**Additional Description**
![image](https://user-images.githubusercontent.com/16068182/184829836-2c5a22b1-6dff-43da-877c-2a1122f28709.png)

**Comment by luckes-yang** [comment]
经过调试，发现是配置项`'debezium.database.pdb.name' = 'xxx'`的问题， Stream模式的dbz配置项直接使用'database.pdb.name' = 'xxx'即可

**Comment by vincent183** [comment]
> 经过调试，发现是配置项`'debezium.database.pdb.name' = 'xxx'`的问题， Stream模式的dbz配置项直接使用'database.pdb.name' = 'xxx'即可

您好， 请问方便的话能贴一下您的建表属性参数吗？ 我想看一下参考一下

**Comment by vincent183** [comment]
> 经过调试，发现是配置项`'debezium.database.pdb.name' = 'xxx'`的问题， Stream模式的dbz配置项直接使用'database.pdb.name' = 'xxx'即可

您好，请问方便的话能贴一下您的代码和属性参数、Oracle授权语句嘛？我想看一下参考一下

我这边也是2.3的oracle cdc、 19c的pdb，1.14.4的Flink。

没有加 'debezium.database.pdb.name' 参数时: 
返回 `Caused by: oracle.jdbc.OracleDatabaseException: ORA-65040: operation not allowed from within a pluggable database
ORA-06512: at "SYS.DBMS_LOGMNR", line 82
ORA-06512: at line 1`

加了 'debezium.database.pdb.name' 参数时: 
返回`Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges`
