### ISSUE TITLE
Exception while handling ad hoc snapshot signals

### ISSUE THREAD

**Issue by samanhappy** [ververica/flink-cdc-connectors#1528]
**Describe the bug(Please use English)**
I was using debezium_signal table to do an ad hoc snapshot, but got NullPointerException
	at io.debezium.pipeline.signal.ExecuteSnapshot.arrived(ExecuteSnapshot.java:64)

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version:  2.3-SNAPSHOT
 - Database and version: Aliyun RDS MySql 5.6.16-log (Source distribution)

**To Reproduce**
Not sure

**exception log**
2022-08-31 11:18:54,207 INFO  io.debezium.pipeline.signal.ExecuteSnapshot                  [] - Requested 'INCREMENTAL' snapshot of data collections '[.]'
2022-08-31 11:18:54,208 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  [] - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.009070/451965786
2022-08-31 11:18:54,208 ERROR io.debezium.pipeline.ErrorHandler                            [] - Producer failure
io.debezium.DebeziumException: Error processing binlog event
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:366) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.handleEvent(MySqlBinlogSplitReadTask.java:82) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$25(MySqlStreamingChangeEventSource.java:842) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1125) [flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:973) [flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Error while processing event at offset {transaction_id=null, ts_sec=1661915934, file=mysql-bin.009070, pos=451965711, gtids=0e6c973c-793a-11e8-b405-7cd30ac0ab24:1-87883871,b265abd2-cf63-11eb-b5df-7cd30ab8a42a:1-757486272,dc1703d8-b5ff-11e6-b5a5-40a8f01e5d38:1-15540,e04363ca-12c4-11ea-a294-7cd30ae439c6:1-85325711,e2af0569-2307-11eb-91f4-0c42a1f04bae:1-214527545,ebafb2b4-b5ff-11e6-b5a5-6c92bf2c161d:1-5116325, row=1, server_id=2015827136, event=2}
	at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:253) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleInsert$4(MySqlStreamingChangeEventSource.java:682) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleChange(MySqlStreamingChangeEventSource.java:732) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleInsert(MySqlStreamingChangeEventSource.java:681) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$15(MySqlStreamingChangeEventSource.java:817) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:349) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	... 7 more
Caused by: java.lang.NullPointerException
	at io.debezium.pipeline.signal.ExecuteSnapshot.arrived(ExecuteSnapshot.java:64) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.pipeline.signal.Signal.process(Signal.java:136) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.pipeline.signal.Signal.process(Signal.java:180) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.pipeline.EventDispatcher$2.changeRecord(EventDispatcher.java:227) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.relational.RelationalChangeRecordEmitter.emitCreateRecord(RelationalChangeRecordEmitter.java:77) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:45) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:217) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleInsert$4(MySqlStreamingChangeEventSource.java:682) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleChange(MySqlStreamingChangeEventSource.java:732) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleInsert(MySqlStreamingChangeEventSource.java:681) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$15(MySqlStreamingChangeEventSource.java:817) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:349) ~[flink-sql-connector-mysql-cdc-2.3-SNAPSHOT.jar:2.3-SNAPSHOT]
	... 7 more

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
