### ISSUE TITLE
unsupported jdbc type

### ISSUE THREAD

**Issue by Jungle666** [ververica/flink-cdc-connectors#1537]
java.lang.IllegalArgumentException: Unexpected value for JDBC type 4 and column pipeline_id INT UNSIGNED(10) NOT NULL: class=class [B
	at io.debezium.jdbc.JdbcValueConverters.handleUnknownData(JdbcValueConverters.java:1248)

.......

Caused by: org.apache.kafka.connect.errors.ConnectException: Data row is smaller than a column index, internal schema representation is probably out of sync with real database schema
	at io.debezium.relational.TableSchemaBuilder.validateIncomingRowToInternalMetadata(TableSchemaBuilder.java:221)
	at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:250)
	at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitCreateRecord(RelationalChangeRecordEmitter.java:69)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:45)
	at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:202)
	... 10 more

**Comment by GOODBOY008** [comment]
Real reason is 
`'Caused by: org.apache.kafka.connect.errors.ConnectException: Data row is smaller than a column index, internal schema representation is probably out of sync with real database schema
'`. Are you use `sqlserver-connector`?

**Comment by Jungle666** [comment]
im using mysql-connector

**Comment by Jungle666** [comment]
> 

I guss it only support  "column pipeline_id INT UNSIGNED"   but "column pipeline_id INT UNSIGNED(10) " unsupported

**Comment by GOODBOY008** [comment]
@Jungle666 Can u supply  table `ddl` and `sql`, I would reproduce this scenio.

**Comment by Jungle666** [comment]
final we find the problem, and fix in
https://github.com/ververica/flink-cdc-connectors/issues/732
case replicia database need reconnect after change binlog_row_image param.

**Comment by farhadlotfii** [comment]
these things for change the schema and change datatype of source
first : restarting task
second : change the database.history.kafka.topic
