### ISSUE TITLE
flink sink ES7 报错：Invalid lambda deserialization

### ISSUE THREAD

**Issue by William-Kaiser** [ververica/flink-cdc-connectors#167]
我的flink 1.12.1  sql clinet 使用
flink-sql-connector-elasticsearch7，代码里使用的flink-connector-elasticsearch7，然后在同一个flink上运行，报如下错误：

Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1248)
        ... 33 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
        at
org.apache.flink.streaming.connectors.elasticsearch7.ElasticsearchSink$Builder.$deserializeLambda$(ElasticsearchSink.java:86)
        ... 42 more

**Comment by fsk119** [comment]
这个不是cdc的问题，解决办法可以参考 [FLINK-18857](https://issues.apache.org/jira/browse/FLINK-18857)。
