### ISSUE TITLE
Flink MySQL CDC connector  job always restart

### ISSUE THREAD

**Issue by chaplinthink** [ververica/flink-cdc-connectors#1692]
**Describe the bug(Please use English)**
 I used datastream api, but it can not run. The flink job always restart. 
  
**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version:  2.2.0、2.2.1、2.3-SNAPSHOT
 - Database and version: MySQL 5.7.34

**To Reproduce**
1. The test data :
2. The test code:
```
 def main(args: Array[String]): Unit = {
        val mySqlSource = MySqlSource.builder[String]
          .hostname("localhost")
          .port(3306)
          .databaseList("test")
          .tableList("test.user")
          .username("root)
          .password("123456")
          .deserializer(new JsonDebeziumDeserializationSchema)
          .build // converts SourceRecord to JSON String

        val env = StreamExecutionEnvironment.getExecutionEnvironment
        // enable checkpoint
        env.enableCheckpointing(3000)

        env.fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source")
          // set 4 parallel source tasks
          .setParallelism(4)
          .print()
          .setParallelism(1); // use parallelism 1 for sink to keep message ordering

        env.execute("Print MySQL Snapshot + Binlog");
```
4. The error :
```
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: MySQL Source' (operator bc764cd8ddf7a0cff126f51c16239658).
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:545)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:231)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.failJob(SourceCoordinatorContext.java:287)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:128)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$DeferrableCoordinator.resetAndStart(RecreateOnResetOperatorCoordinator.java:389)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator.lambda$resetToCheckpoint$6(RecreateOnResetOperatorCoordinator.java:144)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.apache.flink.runtime.operators.coordination.ComponentClosingUtils.lambda$closeAsyncWithTimeout$0(ComponentClosingUtils.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig
	at com.ververica.cdc.connectors.mysql.source.config.MySqlSourceConfig.<init>(MySqlSourceConfig.java:111)
	at com.ververica.cdc.connectors.mysql.source.config.MySqlSourceConfigFactory.createConfig(MySqlSourceConfigFactory.java:313)
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createEnumerator(MySqlSource.java:167)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:124)
	... 8 more

```
**Additional Description**

**Comment by larryju** [comment]
dependency scope  is provided?

**Comment by emerkfu** [comment]
> > dependency scope is provided?
> 
> I find the problem, the different jdbc version caused the error.

I had the same problem, can you please explain how you solved it? Thank you so much!
