### ISSUE TITLE
flinkcdc写入hive hadoop错误

### ISSUE THREAD

**Issue by Xinghan** [ververica/flink-cdc-connectors#171]
2021-04-25 11:58:24,392 ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    [] - Reporting error:
java.lang.NoSuchMethodError: org.apache.hadoop.tracing.SpanReceiverHost.get(Lorg/apache/hadoop/conf/Configuration;Ljava/lang/String;)Lorg/apache/hadoop/tracing/SpanReceiverHost;
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:634) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149) ~[hadoop-hdfs-2.7.1.jar:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596) ~[flinkcdc-0.0.1-SNAPSHOT.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91) ~[flinkcdc-0.0.1-SNAPSHOT.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630) ~[flinkcdc-0.0.1-SNAPSHOT.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612) ~[flinkcdc-0.0.1-SNAPSHOT.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370) ~[flinkcdc-0.0.1-SNAPSHOT.jar:?]

**Comment by fsk119** [comment]
这报错看样子不是cdc的问题吧？
