### ISSUE TITLE
Serialized size (> 1682584050 bytes) exceeds JVM heap space

### ISSUE THREAD

**Issue by rafael81** [ververica/flink-cdc-connectors#1738]
**Describe the bug(Please use English)**

Serialization is failed while operating MySQL CDC.

**Environment :**
 - Flink version :  1.15.2
 - Flink CDC version: 2.2.1
 - Database and version: MySQL 8.0.22

**To Reproduce**
1. The test data :
2. The test code :
3. The error :
2022-11-15 01:13:02,923 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator receives finished split offsets FinishedSnapshotSplitsReportEvent{finishedOffsets={storeplatform_stat.payment:2={ts_sec=0, file=mysql-bin.007601, pos=463826145, gtids=, row=0, event=0}}} from subtask 0.
2022-11-15 01:13:02,924 WARN  org.apache.flink.runtime.checkpoint.CheckpointFailureManager [] - Failed to trigger or complete checkpoint 15 for job 80b7ba600e3c4a9fd5c4dcfa1a1dc691. (0 consecutive failed attempts so far)
org.apache.flink.runtime.checkpoint.CheckpointException: An Exception occurred while triggering the checkpoint. IO-problem detected.
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.getCheckpointException(CheckpointCoordinator.java:2157) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.onTriggerFailure(CheckpointCoordinator.java:930) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.onTriggerFailure(CheckpointCoordinator.java:908) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.lambda$startTriggeringCheckpoint$7(CheckpointCoordinator.java:636) ~[flink-dist-1.15.2.jar:1.15.2]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) [?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) [?:1.8.0_275]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_275]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.io.IOException: Failed to serialize element. Serialized size (> **1682584050** bytes) exceeds JVM heap space
	at org.apache.flink.core.memory.DataOutputSerializer.resize(DataOutputSerializer.java:319) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.core.memory.DataOutputSerializer.write(DataOutputSerializer.java:124) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.core.memory.DataOutputSerializer.write(DataOutputSerializer.java:115) ~[flink-dist-1.15.2.jar:1.15.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.state.PendingSplitsStateSerializer.writeMySqlSplits(PendingSplitsStateSerializer.java:311) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.connectors.mysql.source.assigners.state.PendingSplitsStateSerializer.serializeSnapshotPendingSplitsState(PendingSplitsStateSerializer.java:152) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.connectors.mysql.source.assigners.state.PendingSplitsStateSerializer.serializeHybridPendingSplitsState(PendingSplitsStateSerializer.java:162) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.connectors.mysql.source.assigners.state.PendingSplitsStateSerializer.serialize(PendingSplitsStateSerializer.java:83) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.connectors.mysql.source.assigners.state.PendingSplitsStateSerializer.serialize(PendingSplitsStateSerializer.java:45) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.writeCheckpointBytes(SourceCoordinator.java:462) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.toBytes(SourceCoordinator.java:447) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$checkpointCoordinator$6(SourceCoordinator.java:321) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$9(SourceCoordinator.java:406) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40) ~[flink-dist-1.15.2.jar:1.15.2]
	... 7 more
Caused by: java.lang.OutOfMemoryError: **Java heap space**
**Additional Description**
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/36774/201816981-36e85d4d-10ae-4786-b5b3-fbee8252e67b.png">

**Comment by rafael81** [comment]
Increasing the memory size doesn't solve it

**Comment by rafael81** [comment]
I resolved this issue myself.
You CANNOT declare column as DECIMAL.
JUST USE DOUBLE

**Comment by Vincent-Woo** [comment]
@rafael81 Hello, you mentioned that the issue is caused by the DECIMAL type. Do you know the actual underlying reason? We seem to have encountered a similar issue, I would appreciate it if you could explain it in detail.
