### ISSUE TITLE
unsupported authentication method: sha256_password

### ISSUE THREAD

**Issue by liushuaihang** [ververica/flink-cdc-connectors#1780]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.15.1
 - Flink CDC version: 2.3.0
 - Database and version: MySQL8.0.31

**Additional Description**

Caused by: java.lang.RuntimeException: SplitFetcher thread 1 received unexpected exception while polling the records
at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150)
at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 more

Caused by: io.debezium.DebeziumException: Failed to authenticate to the MySQL database at ip:3306 with user 'mysqluser'
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.execute(MySqlStreamingChangeEventSource.java:1148)
at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.execute(MySqlBinlogSplitReadTask.java:80)
at com.ververica.cdc.connectors.mysql.debezium.reader.BinlogSplitReader.lambda$submitSplit$0(BinlogSplitReader.java:12
4)

Caused by: com.github.shyiko.mysql.binlog.network.AuthenticationException: unsupported authentication method: sha256_password
at com.github.shyiko.mysql.binlog.network.Authenticator.switchAuthentication(Authenticator.java:174)
at com.github.shyiko.mysql.binlog.network.Authenticator.readResult(Authenticator.java:87)
at com.github.shyiko.mysql.binlog.network.Authenticator.authenticate(Authenticator.java:70)
at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:537)
at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857)
... 1 more

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
