### ISSUE TITLE
Flink CDC mysql Unable to connect to the MySQL database

### ISSUE THREAD

**Issue by h6021** [ververica/flink-cdc-connectors#1781]
Describe the bug(Please use English)
Unable to connect to the MySQL database at zhangbei.rds.aliyuncs.com:3306 with user 'dbqa': Socket closed

Environment 

Flink version : 1.15.2
Flink CDC version: 2.3.0
Database and version: MySQL8.0.31

Additional Description

io.debezium.DebeziumException: Unable to connect to the MySQL database at rm-8vba3v3tin6v07hb964460.mysql.zhangbei.rds.aliyuncs.com:3306 with user 'ylzdbqa': Socket closed
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.execute(MySqlStreamingChangeEventSource.java:1160) ~[flink-connector-mysql-cdc-2.3.0.jar:1.6.4.Final]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.execute(MySqlBinlogSplitReadTask.java:80) ~[flink-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.BinlogSplitReader.lambda$submitSplit$0(BinlogSplitReader.java:124) ~[flink-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_341]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_341]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_341]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_341]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[?:1.8.0_341]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_341]
	at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:57) ~[flink-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:222) ~[mysql-binlog-connector-java-0.25.3.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:203) ~[mysql-binlog-connector-java-0.25.3.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:51) ~[mysql-binlog-connector-java-0.25.3.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.read(PacketChannel.java:65) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.readResultSet(BinaryLogClient.java:1072) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.setMasterServerId(BinaryLogClient.java:722) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.setupConnection(BinaryLogClient.java:618) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:557) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	... 1 more

**Comment by ruanhang1993** [comment]
Have you ever checked the network? This may not be a problem in connector.

If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
