### ISSUE TITLE
flink-shaded-guava造成的版本冲突

### ISSUE THREAD

**Issue by TimLiu520** [ververica/flink-cdc-connectors#1845]
flink-streaming-scala_2.11:1.13.3中使用  flink-shaded-guava 18.0-13.0版本

flink-connector-mysql-cdc 2.3.0中使用  30.1.1-jre-16.0   版本

造成版本冲突，排除哪个版本都会报错

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/shaded/guava18/com/google/common/collect/Lists
	at org.apache.flink.streaming.api.transformations.UnionTransformation.<init>(UnionTransformation.java:57)
	at org.apache.flink.streaming.api.datastream.DataStream.union(DataStream.java:243)
	at org.apache.flink.streaming.api.scala.DataStream.union(DataStream.scala:358)
	at com.eav.streaming.SyncWarehouseStreamingJob$.main(SyncWarehouseStreamingJob.scala:61)
	at com.eav.streaming.SyncWarehouseStreamingJob.main(SyncWarehouseStreamingJob.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.shaded.guava18.com.google.common.collect.Lists

**Comment by li57598** [comment]
same problem

**Comment by dorajamie** [comment]
I've met the same problem

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
