### ISSUE TITLE
oracle-cdc  java.lang.NoSuchFieldError: DEFAULT

### ISSUE THREAD

**Issue by Aria0717** [ververica/flink-cdc-connectors#1855]
**Describe the bug(Please use English)**
using flink-oracle-cdc connect oracle appear this bug,

![image](https://user-images.githubusercontent.com/41320786/210918355-1c8fe549-9638-44e5-b814-f79f0beb89f2.png)

![image](https://user-images.githubusercontent.com/41320786/210918913-89ea9cce-48df-41ed-9d0c-0848529ea7b4.png)

	at org.apache.kafka.connect.runtime.WorkerConfig.baseConfigDef(WorkerConfig.java:284)
	at io.debezium.embedded.EmbeddedEngine$EmbeddedConfig.<clinit>(EmbeddedEngine.java:1101)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:600)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:81)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:302)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:218)
	at io.debezium.embedded.ConvertingEngineBuilder.build(ConvertingEngineBuilder.java:151)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:421)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Database and version: 11.2

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by Aria0717** [comment]
java.lang.NoSuchFieldError: DEFAULT
	at org.apache.kafka.connect.runtime.WorkerConfig.baseConfigDef(WorkerConfig.java:284)
	at io.debezium.embedded.EmbeddedEngine$EmbeddedConfig.<clinit>(EmbeddedEngine.java:1101)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:600)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:81)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:302)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:218)
	at io.debezium.embedded.ConvertingEngineBuilder.build(ConvertingEngineBuilder.java:151)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:421)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)



code:

        Properties properties = new Properties();
        properties.setProperty("debezium.log.mining.continuous.mine", "true");
        properties.setProperty("debezium.database.tablename.case.insensitive", "false");
        properties.setProperty("debezium.log.mining.strategy", "online_catalog");
        properties.setProperty("database.tablename.case.insensitive", "false");
        properties.setProperty("database.connection.adapter", "logminer");
        properties.setProperty("log.mining.strategy", "online_catalog");
        properties.setProperty("log.mining.continuous.mine", "true");

        SourceFunction<String> sourceFunction =
                OracleSource.<String>builder()
                        .hostname("")
                        .port(1521)
                        .database("") // monitor XE database
                        .schemaList("") // monitor inventory schema
                        .tableList("") // monitor products table
                        .username("")
                        .password("")
                        .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                        .debeziumProperties(properties)
                        .build();

        DataStream<String> stream = environment.addSource(sourceFunction).setParallelism(1);
