### ISSUE TITLE
SLF4J: Failed toString() invocation on an object of type [io.debezium.pipeline.DataChangeEvent]

### ISSUE THREAD

**Issue by Aria0717** [ververica/flink-cdc-connectors#1884]
**Describe the bug(Please use English)**
when test flink-oracle-cdc，appear this bug

**Environment :**
 - Flink version :  1.12.5
 - Flink CDC version: 2.2
 - Database and version: oracle 11

**To Reproduce**
1. The test data :
2. The test code :

sourceFunction =
                OracleSource.<String>builder()
                        .hostname(host)
                        .port(Integer.parseInt(port))
                        .database(database) // monitor XE database
                        .schemaList(schema) // monitor inventory schema
                        .tableList(table) // monitor products table
                        .username(username)
                        .password(password)
                        .deserializer(jdd) // converts SourceRecord to JSON String
                        .debeziumProperties(debeziumProperties)
                        .build();

DataStream<String> source = env.addSource(sourceFunction);
        DataStream<Order> stream = source.map((MapFunction<String, Order>) value ->
        {
            Order order = MAPPER.convertValue(MAPPER.readTree(value).get("payload").get("after"), Order.class);
            order.setReadTime(new Timestamp(System.currentTimeMillis()));
            return order;
        });

4. The error :

Reported exception:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at shade.org.apache.kafka.connect.data.Struct.toString(Struct.java:283)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at shade.org.apache.kafka.connect.connector.ConnectRecord.toString(ConnectRecord.java:139)
	at shade.org.apache.kafka.connect.source.SourceRecord.toString(SourceRecord.java:134)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at io.debezium.pipeline.DataChangeEvent.toString(DataChangeEvent.java:24)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:124)
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:228)
	at io.debezium.connector.base.ChangeEventQueue.doEnqueue(ChangeEventQueue.java:200)
	at io.debezium.connector.base.ChangeEventQueue.enqueue(ChangeEventQueue.java:173)
	at io.debezium.pipeline.EventDispatcher$BufferingSnapshotChangeRecordReceiver.changeRecord(EventDispatcher.java:402)
	at io.debezium.pipeline.EventDispatcher$1.changeRecord(EventDispatcher.java:165)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitReadRecord(RelationalChangeRecordEmitter.java:88)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:48)
	at io.debezium.pipeline.EventDispatcher.dispatchSnapshotEvent(EventDispatcher.java:155)
	at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEventsForTable(RelationalSnapshotChangeEventSource.java:377)
	at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:305)
	at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:138)
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:71)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:110)
	at io.debezium.pipeline.ChangeEventSourceCoordinator$$Lambda$452/1837023620.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
SLF4J: Failed toString() invocation on an object of type [io.debezium.pipeline.DataChangeEvent]

**Additional Description**

**Comment by msmoving** [comment]
I also meet this question in oracle cdc, increase memory is not useful, I have seen you close this issue, Do you resolved it, Can you give some suggestion? tks
