### ISSUE TITLE
[mysql-cdc] SQL syntax error when snapshot

### ISSUE THREAD

**Issue by LiangQinghai** [ververica/flink-cdc-connectors#1894]
**Describe the bug(Please use English)**
An error occurred when MySQL table primary key is the key word（You have an error in your SQL syntax）

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version:  2.2.1
 - Database and version:  mysql-8.0

**To Reproduce**
1. The test data :  test table ddl: 
```
CREATE TABLE `test` (
      `key` varchar(255) NOT NULL,
      `value` text NOT NULL,
      UNIQUE KEY `ux_key_value_store_key` (`key`)
    ) ENGINE=InnoDB;
```
2. The test code : 
3. The error :
```
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key >= 'CONFIG_ORDER_2010017_20211002141041' AND NOT (key = 'CONFIG_ORDER_202001' at line 1
	    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	    at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	    at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:228)
	    ... 10 more
```

**Additional Description**
I saw a PR at #1709

In order to solve this proplem I hack the code in `com.ververica.cdc.connectors.mysql.source.utils.StatementUtils#addPrimaryKeyColumnsToCondition` and add quote when building snapshot sql.

```
    private static void addPrimaryKeyColumnsToCondition(
            RowType pkRowType, StringBuilder sql, String predicate) {
        for (Iterator<String> fieldNamesIt = pkRowType.getFieldNames().iterator();
             fieldNamesIt.hasNext(); ) {
            // fix SQL syntax
            sql.append(quote(fieldNamesIt.next())).append(predicate);
            if (fieldNamesIt.hasNext()) {
                sql.append(" AND ");
            }
        }
    }
```

**Comment by ruanhang1993** [comment]
Thanks. This has been fixed.
