### ISSUE TITLE
[Bug] flinkcdc读取oracle10g报错

### ISSUE THREAD

**Issue by ZhiYinZhang** [ververica/flink-cdc-connectors#1919]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.4-SNAPSHOT

### Database and its version

oracle 10.2.0.1.0

### Minimal reproduce step

ERROR io.debezium.connector.oracle.logminer.LogMinerHelper         [] - Mining session stopped due to the java.sql.SQLException: ORA-06550: 第 1 行, 第 39 列: 
PLS-00201: 必须声明标识符 'DBMS_LOGMNR_D.STORE_IN_REDO_LOGS'
ORA-06550: 第 1 行, 第 7 列: 
PL/SQL: Statement ignored
17:36:09,883 ERROR io.debezium.pipeline.ErrorHandler                            [] - Producer failure
java.sql.SQLException: ORA-06550: 第 1 行, 第 39 列: 
PLS-00201: 必须声明标识符 'DBMS_LOGMNR_D.STORE_IN_REDO_LOGS'
ORA-06550: 第 1 行, 第 7 列: 
PL/SQL: Statement ignored
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:705) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.buildDataDictionary(LogMinerHelper.java:99) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.initializeRedoLogsForMining(LogMinerStreamingChangeEventSource.java:363) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:162) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask$RedoLogSplitReadTask.execute(OracleStreamFetchTask.java:123) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask.execute(OracleStreamFetchTask.java:71) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:86) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]

### What did you expect to see?

正常获取增量数据

### What did you see instead?

Error

### Anything else?

是不支持oracle10g，还是有什么参数要设置

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
