### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Adam3300** [ververica/flink-cdc-connectors#1949]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.3

### Database and its version

mysql '1.1'
postgres '2.1'
elasticsearch '7.6.0'
 
more information [here](https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html#id2)

### Minimal reproduce step

Followed this [guide](https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html) 

### What did you expect to see?

SQL client 

### What did you see instead?

george@george-VirtualBox:~/Downloads/test/flink-1.16.0/bin$ ./sql-client.sh 
Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: org.apache.flink.table.api.TableException: Could not instantiate the executor. Make sure a planner module is on the classpath
	at org.apache.flink.table.client.gateway.context.ExecutionContext.lookupExecutor(ExecutionContext.java:165)
	at org.apache.flink.table.client.gateway.context.ExecutionContext.createTableEnvironment(ExecutionContext.java:102)
	at org.apache.flink.table.client.gateway.context.ExecutionContext.<init>(ExecutionContext.java:66)
	at org.apache.flink.table.client.gateway.context.SessionContext.create(SessionContext.java:246)
	at org.apache.flink.table.client.gateway.local.LocalContextUtils.buildSessionContext(LocalContextUtils.java:87)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.openSession(LocalExecutor.java:87)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:88)
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
	... 1 more
Caused by: org.apache.flink.table.api.TableException: Unexpected error when trying to load service provider for factories.
	at org.apache.flink.table.factories.FactoryUtil.lambda$discoverFactories$19(FactoryUtil.java:820)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.apache.flink.table.factories.FactoryUtil.discoverFactories(FactoryUtil.java:806)
	at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:524)
	at org.apache.flink.table.client.gateway.context.ExecutionContext.lookupExecutor(ExecutionContext.java:154)
	... 8 more
Caused by: java.util.ServiceConfigurationError: org.apache.flink.table.factories.Factory: Provider com.ververica.cdc.connectors.postgres.table.PostgreSQLTableFactory could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at org.apache.flink.table.factories.ServiceLoaderUtil.load(ServiceLoaderUtil.java:42)
	at org.apache.flink.table.factories.FactoryUtil.discoverFactories(FactoryUtil.java:805)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: com/ververica/cdc/debezium/table/DebeziumChangelogMode
	at com.ververica.cdc.connectors.postgres.table.PostgreSQLTableFactory.<clinit>(PostgreSQLTableFactory.java:106)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.ververica.cdc.debezium.table.DebeziumChangelogMode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more

### Anything else?

The instructions work using the connectors below: 

- flink-sql-connector-mysql-cdc-2.4-SNAPSHOT
- flink-sql-connector-postgres-cdc-2.4-SNAPSHOT

However, they don't work when using these connectors for 2.3 

Also, the download links for the above-mentioned connectors do not work. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
