### ISSUE TITLE
Caused by: java.sql.SQLException: Invalid column type

### ISSUE THREAD

**Issue by dongkelun** [ververica/flink-cdc-connectors#1975]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

数据能查出来，但是会抛出下面这个异常，看起来像是字段类型的问题。但是我将字段类型全部建成varchar(string)，有同样的问题

flink 1.14.3
oracle-cdc 2.3.0
Caused by: java.sql.SQLException: Invalid column type
	at oracle.jdbc.driver.Redirector$2.redirect(Redirector.java:261) ~[ojdbc7.jar:12.1.0.1.0]
	at oracle.jdbc.driver.Representation.getObject(Representation.java:423) ~[ojdbc7.jar:12.1.0.1.0]
	at oracle.jdbc.driver.Accessor.getObject(Accessor.java:986) ~[ojdbc7.jar:12.1.0.1.0]
	at oracle.jdbc.driver.OracleStatement.getObject(OracleStatement.java:6521) ~[ojdbc7.jar:12.1.0.1.0]
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.getObject(InsensitiveScrollableResultSet.java:909) ~[ojdbc7.jar:12.1.0.1.0]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.lambda$getSystime$0(LogMinerHelper.java:207) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:649) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:517) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.getSystime(LogMinerHelper.java:205) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:202) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask$RedoLogSplitReadTask.execute(OracleStreamFetchTask.java:123) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask.execute(OracleStreamFetchTask.java:71) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:86) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dongkelun** [comment]
已解决
