### ISSUE TITLE
[Bug] Rediscover " java.lang.ClassNotFoundException: org.apache.kafka.connect.data.Schema" Problem in new version

### ISSUE THREAD

**Issue by xuanqiang** [ververica/flink-cdc-connectors#2039]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0-2.12

### Flink CDC version

2.3.0

### Database and its version

Oracle 19C
oracle is deployed in rac + cdb mode

### Minimal reproduce step

/data1/flink/bin/sql-client.sh embedded
CREATE TABLE products11 (

id INT,

name STRING

) WITH (

'connector' = 'oracle-cdc',

'hostname' = '192.168.136.112',

'port' = '1521',

'username' = 'c##flinkuser',

'password' = 'flinkpw',

'database-name' = 'racdb',

'schema-name' = 'flink_test',

'table-name' = 'TEST0323',

'debezium.database.pdb.name' = 'cldb'

);

select * from products11;

### What did you expect to see?

select   out result set

### What did you see instead?

Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.data.Schema
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_271]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_271]
        at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_271]
        at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1644) ~[?:1.8.0_271]
        at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:79) ~[?:1.8.0_271]
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:520) ~[?:1.8.0_271]
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494) ~[?:1.8.0_271]

<img width="736" alt="image" src="https://user-images.githubusercontent.com/6870162/227408506-844fe020-7e26-4d29-a801-3431f4066345.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xuanqiang** [comment]
This issue has been resolved. 
Because shouldn't  import flink-connector-oracle-cdc-2.3.0.jar to flink/lib

**Comment by mkan-su** [comment]
This issue resurfaced in current version 2.4.2. I was using Mysql CDC connector ([flink-connector-mysql-cdc-2.4.2.jar] and facing same problem
