### ISSUE TITLE
MySQL 大批量新增数据时，CDC 报错

### ISSUE THREAD

**Issue by Han-MeiM** [ververica/flink-cdc-connectors#204]
```text
2021-06-04 14:45:16
org.apache.kafka.connect.errors.ConnectException: Encountered change event for table data_sync.sls_sync_moments whose schema isn't known to this connector
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:600)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1130)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:978)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:860)
	at java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.ConnectException: Encountered change event for table data_sync.sls_sync_moments whose schema isn't known to this connector
	at io.debezium.connector.mysql.BinlogReader.informAboutUnknownTableIfRequired(BinlogReader.java:858)
	at io.debezium.connector.mysql.BinlogReader.handleUpdateTableMetadata(BinlogReader.java:832)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:583)
	... 5 more
```
![image](https://user-images.githubusercontent.com/27951114/120757748-892f6f00-c543-11eb-84a6-025101494062.png)

```java
SourceFunction<String> sourceFunction = MySQLSource.<String>builder()
                .hostname("")
                .port()
                .databaseList("")
                .tableList("")
                .username("")
                .password("")
                .deserializer()
                .build();
```

当天大概2小时内数据库新增了 4000万 条数据，导致 cdc 一直报错。

**Comment by Han-MeiM** [comment]
![image](https://user-images.githubusercontent.com/27951114/120964557-18cc5c00-c796-11eb-962e-256055917eb4.png)

再补一张图，数据量大的时候调整并发度对 source 没有影响，导致发生反压的情况，Checkpoint 一直失败

**Comment by fsk119** [comment]
Hi @Han-MeiM. You can use [event.deserialization.failure.handling.mode ](https://debezium.io/documentation/reference/connectors/mysql.html#mysql-property-event-deserialization-failure-handling-mode) to filter out the dirty data. 

Recently @leonardBang improved the implementation of the Mysql connector, you can make a try.
