### ISSUE TITLE
[Bug]  ERROR com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader - Execute snapshot read task for mysql split MySqlSnapshotSplit

### ISSUE THREAD

**Issue by AprilOneDay** [ververica/flink-cdc-connectors#2090]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

5.6

### Minimal reproduce step

public static void main(String[] args) throws Exception {

        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        Properties prop = new Properties();
        prop.setProperty("useSSL", "false");
        prop.setProperty("characterEncoding", "UTF-8");
        prop.setProperty("useUnicode", "true");
        prop.setProperty("tinyInt1isBit", "false");
        prop.setProperty("allowPublicKeyRetrieval", "true");

        MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .jdbcProperties(prop)
                .serverTimeZone("Asia/Shanghai")
                .hostname("127.0.0.1")
                .port(3306)
                .databaseList("new_qn") // set captured database
                .tableList("new_qn.rb_user_bus") // set captured table
                .username("xxx")
                .password("xxx")
                //从最新binlog读取，增量方式:latest
                .startupOptions(StartupOptions.initial())
                .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                .build();

        // enable checkpoint
        env.enableCheckpointing(3000);

        DataStreamSource<String> mySqlDS  =  env.fromSource(mySqlSource, WatermarkStrategy.noWatermarks(),"MySQL Source");

//        mySqlDS.print().setParallelism(1);

        mySqlDS.addSink(new CDCDataSink());

        env.execute("Print MySQL Snapshot + Binlog");
    }

### What did you expect to see?

怎么让他们正常工作
How to make them work normally

### What did you see instead?

10:48:02.591 [debezium-reader-2] ERROR com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader - Execute snapshot read task for mysql split MySqlSnapshotSplit{tableId=new_qn.rb_user_bus, splitId='new_qn.rb_user_bus:23', splitKeyType=[`user_id` BIGINT NOT NULL], splitStart=[1072607], splitEnd=[1119242], highWatermark=null} fail
io.debezium.DebeziumException: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Snapshotting of table new_qn.rb_user_bus failed
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:120) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.lambda$submitSplit$0(SnapshotSplitReader.java:130) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Snapshotting of table new_qn.rb_user_bus failed
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:265) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 7 more
Caused by: java.sql.SQLException: Can not read response from server. Expected to read 482 bytes, read 427 bytes before connection was unexpectedly lost.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:230) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 7 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 482 bytes, read 427 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessageLocal(SimplePacketReader.java:137) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:102) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:45) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readMessage(TimeTrackingPacketReader.java:62) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readMessage(TimeTrackingPacketReader.java:41) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readMessage(MultiPacketReader.java:66) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readMessage(MultiPacketReader.java:44) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:75) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:230) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 7 more
10:48:02.777 [Source Data Fetcher for Source: MySQL Source -> Sink: Unnamed (3/4)#22] ERROR org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150) ~[flink-connector-base-1.16.1.jar:1.16.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105) [flink-connector-base-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.flink.util.FlinkRuntimeException: Read split MySqlSnapshotSplit{tableId=new_qn.rb_user_bus, splitId='new_qn.rb_user_bus:23', splitKeyType=[`user_id` BIGINT NOT NULL], splitStart=[1072607], splitEnd=[1119242], highWatermark=null} error due to com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Snapshotting of table new_qn.rb_user_bus failed.
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.checkReadException(SnapshotSplitReader.java:306) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.pollSplitRecords(SnapshotSplitReader.java:253) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:76) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58) ~[flink-connector-base-1.16.1.jar:1.16.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142) ~[flink-connector-base-1.16.1.jar:1.16.1]
	... 7 more
Caused by: io.debezium.DebeziumException: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Snapshotting of table new_qn.rb_user_bus failed
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:120) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.lambda$submitSplit$0(SnapshotSplitReader.java:130) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 6 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: Snapshotting of table new_qn.rb_user_bus failed
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:265) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.lambda$submitSplit$0(SnapshotSplitReader.java:130) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 6 more
Caused by: java.sql.SQLException: Can not read response from server. Expected to read 482 bytes, read 427 bytes before connection was unexpectedly lost.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:230) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.lambda$submitSplit$0(SnapshotSplitReader.java:130) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 6 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 482 bytes, read 427 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessageLocal(SimplePacketReader.java:137) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:102) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:45) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readMessage(TimeTrackingPacketReader.java:62) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readMessage(TimeTrackingPacketReader.java:41) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readMessage(MultiPacketReader.java:66) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.MultiPacketReader.readMessage(MultiPacketReader.java:44) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:75) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1587) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1600) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1654) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1000) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEventsForTable(MySqlSnapshotSplitReadTask.java:230) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.createDataEvents(MySqlSnapshotSplitReadTask.java:193) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:154) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:115) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.lambda$submitSplit$0(SnapshotSplitReader.java:130) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	... 6 more
10:48:02.779 [Source Data Fetcher for Source: MySQL Source -> Sink: Unnamed (3/4)#22] ERROR com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader - Close snapshot reader error
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1837) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1694) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:713) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at io.debezium.jdbc.JdbcConnection.lambda$doClose$3(JdbcConnection.java:963) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gong** [comment]
@AprilOneDay Hi.
```
splitKeyType=[user_id BIGINT NOT NULL], splitStart=[1072607], splitEnd=[1119242], highWatermark=null} fail
```
1119242 - 1072607 = 46635. 
I think chunk data size is too long cause your db kill the connection session. You can reduce snapshot chunk size.
