### ISSUE TITLE
[Bug]  DML statement couldn't be parsed You can set internal.log.mining.dml.parser='legacy' as a workaround until the parse error is fixed

### ISSUE THREAD

**Issue by Jiafan** [ververica/flink-cdc-connectors#2115]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

Oracle Database 11g

### step 0:  catch oracle table change like below:
```
SourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .url(String.format("jdbc:oracle:thin:@%s/dcepdb", System.getenv("ORACLE_HOST")))
                .port(Integer.parseInt(System.getenv("ORACLE_PORT")))
                .database("dcepdb")
                .schemaList("biflinkuser, cbtss")
                .tableList("biflinkuser.test") 
                .username(System.getenv("ORACLE_USER"))
                .password(System.getenv("ORACLE_PWD"))
                .debeziumProperties(prepareDebeziumProperties())
                .deserializer(new JsonDebeziumDeserializationSchema())
                .startupOptions(com.ververica.cdc.connectors.base.options.StartupOptions.initial())
                .build();
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        DataStreamSource<String> ds = env.addSource(sourceFunction);

private static Properties prepareDebeziumProperties(){
        Properties properties = new Properties();
        properties.setProperty("decimal.handling.mode", "double");
        properties.setProperty("debezium.log.mining.strategy","online_catalog");
        properties.setProperty("debezium.log.mining.continuous.mine","true");
        return properties;
    }

```

### step1: alter target table (biflinkuser.test)

```
ALTER TABLE BIFLINKUSER.TEST ADD TTT int ;
```

### step2: update a row and set a value for column TTT;

`update BIFLINKUSER.TEST set TTT = 111 where ID = '3' and NAME = 'test0033';
commit ;`

### What did you expect to see?

{
    "before": {
        "ID": 3.0,
        "NAME": "test0033",
        "CREATE_TIME": 1681291449000000,
        "UPDATE_TIME": 1681291449000000
},
    "after":
    {
        "ID": 3.0,
        "NAME": "test0033",
        "CREATE_TIME": 1681291449000000,
        "UPDATE_TIME": 1681291649000000,
        "TTT":111
    },
    "source":
    {
        "version": "1.6.4.Final",
        "connector": "oracle",
        "name": "oracle_logminer",
        "ts_ms": 1681291649000,
        "snapshot": "true",
        "db": "DCEPDB",
        "sequence": null,
        "schema": "BIFLINKUSER",
        "table": "TEST",
        "txId": null,
        "scn": "35210385729",
        "commit_scn": null,
        "lcr_position": null
    },
    "op": "r",
    "ts_ms": 1681291649000,
    "transaction": null
}

### job failed

```
[debezium-oracleconnector-oracle_logminer-change-event-source-coordinator] ERROR io.debezium.connector.oracle.logminer.LogMinerHelper - Mining session stopped due to the {}
io.debezium.connector.oracle.logminer.parser.DmlParserException: DML statement couldn't be parsed. Please open a Jira issue with the statement 'update "BIFLINKUSER"."TEST" set "TTT" = '111' where "ID" = '3' and "NAME" = 'test0033' and "CREATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "UPDATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "TTT" IS NULL;'. You can set internal.log.mining.dml.parser='legacy' as a workaround until the parse error is fixed.
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:407)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.lambda$processResult$0(LogMinerQueryResultProcessor.java:268)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.lambda$registerDmlOperation$0(TransactionalBuffer.java:159)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.registerEvent(TransactionalBuffer.java:655)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.registerDmlOperation(TransactionalBuffer.java:155)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.processResult(LogMinerQueryResultProcessor.java:267)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:280)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:71)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:160)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: Failed to parse update DML: 'update "BIFLINKUSER"."TEST" set "TTT" = '111' where "ID" = '3' and "NAME" = 'test0033' and "CREATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "UPDATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "TTT" IS NULL;'
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parseUpdate(LogMinerDmlParser.java:155)
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parse(LogMinerDmlParser.java:77)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:397)
	... 14 more
Caused by: io.debezium.DebeziumException: No column 'TTT' found in table 'DCEPDB.BIFLINKUSER.TEST'
	at io.debezium.connector.oracle.logminer.LogMinerHelper.getColumnIndexByName(LogMinerHelper.java:752)
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parseSetClause(LogMinerDmlParser.java:390)
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parseUpdate(LogMinerDmlParser.java:132)
	... 16 more
[debezium-oracleconnector-oracle_logminer-change-event-source-coordinator] ERROR io.debezium.pipeline.ErrorHandler - Producer failure
io.debezium.connector.oracle.logminer.parser.DmlParserException: DML statement couldn't be parsed. Please open a Jira issue with the statement 'update "BIFLINKUSER"."TEST" set "TTT" = '111' where "ID" = '3' and "NAME" = 'test0033' and "CREATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "UPDATE_TIME" = TO_TIMESTAMP('2023-04-12 09:24:09.') and "TTT" IS NULL;'. You can set internal.log.mining.dml.parser='legacy' as a workaround until the parse error is fixed.
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:407)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.lambda$processResult$0(LogMinerQueryResultProcessor.java:268)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.lambda$registerDmlOperation$0(TransactionalBuffer.java:159)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.registerEvent(TransactionalBuffer.java:655)
	at io.debezium.connector.oracle.logminer.TransactionalBuffer.registerDmlOperation(TransactionalBuffer.java:155)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.processResult(LogMinerQueryResultProcessor.java:267)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:280)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:71)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:160)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

### set properties as log ,but useless

log tip:
`set internal.log.mining.dml.parser='legacy'`

actually , I set the property like this 
`properties.setProperty("debezium.log.mining.continuous.mine","true");`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1965.
