### ISSUE TITLE
Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: DML statement couldn't be parsed. Please open a Jira issue with the statement 'update

### ISSUE THREAD

**Issue by wsczm** [ververica/flink-cdc-connectors#2140]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.1

### Flink CDC version

        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-sql-connector-oracle-cdc</artifactId>
            <version>2.3.0</version>
        </dependency>

### Database and its version

oracle 11g

### Minimal reproduce step

step 1: flink sql table 
tEnv.executeSql(
      s"""
         |CREATE TABLE ORACLE_T_WF_APPROVALASSIGN(
         |FAPPROVALASSIGNID	varchar(500)	,
         |FASSIGNID	varchar(500)	,
         |FOBJECTTYPEID	varchar(500)	,
         |FKEYVALUE	varchar(500)	,
         |FVARIABLENAME	varchar(500)	,
         |FDEFAULTRESULT	varchar(500)	,
         |FRESULT	varchar(500)	,
         |FDISPOSITION	string	,
         |FISLOCKED	varchar(10)	,
         |FLOCKEDUSERID	double	,
         |FISALLOWLOCK	varchar(10)	,
         |FISALLOWFORWARD	varchar(10)	,
         |FISALLOWBATCHDEAL	varchar(10)	,
         |FCANSPECIFYNEXT	varchar(10)	,
         |FOPERATIONNUMBER	varchar(500)	,
         |FDEALTIME	timestamp	,
         |FTIMEOUTDEAL	varchar(10)	,
         |FTIMEOUTHOURS	double	,
         |FTIMEOUTSTRATEGY	double	,
         |FAUTOAPPROVAL	varchar(500)	,
         |FTIMEOUTDEALWITH	double	,
         |FCANADDPARTICIPANT	varchar(10)	,
         |FNOTICETYPE	double	,
         |FSENDMAILTIME	double	,
         |FSENDSMSTIME	double	,
         |FMAILNOTICESTATUS	varchar(10)	,
         |FSMSNOTICESTATUS	varchar(10)	,
         |FISALLOWPASSROUND	varchar(10)	,
         |FSENDXUNTONGTIME	double	,
         |FXUNTONGNOTICESTATUS	varchar(10)	,
         |FHASADDSIGN	varchar(10)	,
         |FISALLOWADDSIGN	varchar(10)	,
         |FREJECTRETURNACT	double	,
         |FSENDMAILMINUTE	double	,
         |FSENDSMSMINUTE	double	,
         |FTIMEOUTMINUTE	double	,
         |FSENDXUNTONGMINUTE	double	,
         |FCALENDARID	double	,
         |FDEALDATEHOURS	double	,
         |FCOSTHOURS	double	,
         |FAPPROVALWITHGUI	varchar(10)	,
         |FREPEATNOTICEMINUTE	double	,
         |FREPEATNOTICETIMES	double	,
         |FREPEATNOTICEMAX	double	,
         |FMSGNOTICETIME timestamp,
         |PRIMARY KEY (FAPPROVALASSIGNID) NOT ENFORCED
         |) WITH (
         |'connector'     =  'oracle-cdc',
         |'hostname'      =  '${parameterTool.get(PropertiesConstants.ORACLE_HOST)}',
         |'port'          =  '${parameterTool.get(PropertiesConstants.ORACLE_PORT)}',
         |'username'      =  '${parameterTool.get(PropertiesConstants.ORACLE_USERNAME)}',
         |'password'      =  '${parameterTool.get(PropertiesConstants.ORACLE_PASSWORD)}',
         |'database-name' =  '${parameterTool.get(PropertiesConstants.ORACLE_DATABASE)}',
         |'schema-name'   =  '${parameterTool.get(PropertiesConstants.ORACLE_SCHEMA)}',
         |'scan.startup.mode' = 'latest-offset',
         |'debezium.database.tablename.case.insensitive' = 'false',
         |'debezium.log.mining.strategy'='online_catalog',
         |'debezium.log.mining.continuous.mine'='true',
         |'debezium.internal.log.mining.dml.parser'='legacy',
         |'table-name'    =  'T_WF_APPROVALASSIGN')""".stripMargin)
step 2 : oracle table:
FAPPROVALASSIGNID	VARCHAR2
FASSIGNID	VARCHAR2
FOBJECTTYPEID	VARCHAR2
FKEYVALUE	VARCHAR2
FPOLICYXML	(USER-DEFINED)
FAPPROVALACTION	(USER-DEFINED)
FVARIABLENAME	NVARCHAR2
FDEFAULTRESULT	NVARCHAR2
FRESULT	NVARCHAR2
FDISPOSITION	NVARCHAR2
FISLOCKED	CHAR
FLOCKEDUSERID	NUMBER
FISALLOWLOCK	CHAR
FISALLOWFORWARD	CHAR
FISALLOWBATCHDEAL	CHAR
FCANSPECIFYNEXT	CHAR
FOPERATIONNUMBER	NVARCHAR2
FDEALTIME	DATE
FTIMEOUTDEAL	CHAR
FTIMEOUTHOURS	NUMBER
FTIMEOUTSTRATEGY	NUMBER
FAUTOAPPROVAL	NVARCHAR2
FTIMEOUTDEALWITH	NUMBER
FCANADDPARTICIPANT	CHAR
FNOTICETYPE	NUMBER
FSENDMAILTIME	NUMBER
FSENDSMSTIME	NUMBER
FMAILNOTICESTATUS	CHAR
FSMSNOTICESTATUS	CHAR
FISALLOWPASSROUND	CHAR
FSENDXUNTONGTIME	NUMBER
FXUNTONGNOTICESTATUS	CHAR
FHASADDSIGN	CHAR
FISALLOWADDSIGN	CHAR
FREJECTRETURNACT	NUMBER
FSENDMAILMINUTE	NUMBER
FSENDSMSMINUTE	NUMBER
FTIMEOUTMINUTE	NUMBER
FSENDXUNTONGMINUTE	NUMBER
FCALENDARID	NUMBER
FDEALDATEHOURS	NUMBER
FCOSTHOURS	NUMBER
FAPPROVALWITHGUI	CHAR
FREPEATNOTICEMINUTE	NUMBER
FREPEATNOTICETIMES	NUMBER
FREPEATNOTICEMAX	NUMBER
FMSGNOTICETIME	DATE
step 3:
when insert data to oracle table   if the column name eq  FDISPOSITION (NVARCHAR2)  and value eq "当我设置FDISPOSITION的值为汉字时，就会报类型解析错误"
step 4: error info
Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: Cannot parse DML: update "KINGDEE1"."T_WF_APPROVALASSIGN" a set a."FRESULT" = 'Consent', a."FDISPOSITION" = UNISTR('\\6309S2211110004\\751F\\4EA7\\5F52\\8FD8\\FF0CBOM\\4E0ES221111000402\\7248\\672C\\4FDD\\6301\\4E00\\81F4'), a."FCOSTHOURS" = '.44' where a."FAPPROVALASSIGNID" = '646427d09f1076' and a."FASSIGNID" = '646427d09f1075' and a."FOBJECTTYPEID" = 'SAL_SaleOrder' and a."FKEYVALUE" = '291778' and a."FVARIABLENAME" = 'ActionResult' and a."FDEFAULTRESULT" = 'Consent' and a."FRESULT" IS NULL and a."FDISPOSITION" IS NULL and a."FISLOCKED" = '0' and a."FLOCKEDUSERID" = '0' and a."FISALLOWLOCK" = '0' and a."FISALLOWFORWARD" = '1' and a."FISALLOWBATCHDEAL" = '1' and a."FCANSPECIFYNEXT" = '1' and a."FOPERATIONNUMBER" = ' ' and a."FDEALTIME" = TO_DATE('2023-05-17 09:03:12', 'YYYY-MM-DD HH24:MI:SS') and a."FTIMEOUTDEAL" = '0' and a."FTIMEOUTHOURS" = '0' and a."FTIMEOUTSTRATEGY" = '0' and a."FAUTOAPPROVAL" = ' ' and a."FTIMEOUTDEALWITH" IS NULL and a."FCANADDPARTICIPANT" = '0' and a."FNOTICETYPE" = '4' and a."FSENDMAILTIME" = '0' and a."FSENDSMSTIME" = '0' and a."FMAILNOTICESTATUS" = '0' and a."FSMSNOTICESTATUS" = '0' and a."FISALLOWPASSROUND" = '0' and a."FSENDXUNTONGTIME" = '0' and a."FXUNTONGNOTICESTATUS" = '0' and a."FHASADDSIGN" = '0' and a."FISALLOWADDSIGN" = '0' and a."FREJECTRETURNACT" = '0' and a."FSENDMAILMINUTE" = '0' and a."FSENDSMSMINUTE" = '0' and a."FTIMEOUTMINUTE" = '0' and a."FSENDXUNTONGMINUTE" = '0' and a."FCALENDARID" = '0' and a."FDEALDATEHOURS" = '0' and a."FCOSTHOURS" = '0' and a."FAPPROVALWITHGUI" = '0' and a."FREPEATNOTICEMINUTE" = '0' and a."FREPEATNOTICETIMES" = '0' and a."FREPEATNOTICEMAX" = '0' and a."FMSGNOTICETIME" IS NULL;
	at io.debezium.connector.oracle.logminer.parser.SimpleDmlParser.parse(SimpleDmlParser.java:123)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:397)
	... 14 more
Caused by: java.lang.NumberFormatException: For input string: "\630"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
 

### What did you expect to see?

When the inserted value is in Chinese characters, the following error message will be prompted

Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: Cannot parse DML: update "KINGDEE1"."T_WF_APPROVALASSIGN" a set a."FRESULT" = 'Consent', a."FDISPOSITION" = UNISTR('\\6309S2211110004\\751F\\4EA7\\5F52\\8FD8\\FF0CBOM\\4E0ES221111000402\\7248\\672C\\4FDD\\6301\\4E00\\81F4'), a."FCOSTHOURS" = '.44' where a."FAPPROVALASSIGNID" = '646427d09f1076' and a."FASSIGNID" = '646427d09f1075' and a."FOBJECTTYPEID" = 'SAL_SaleOrder' and a."FKEYVALUE" = '291778' and a."FVARIABLENAME" = 'ActionResult' and a."FDEFAULTRESULT" = 'Consent' and a."FRESULT" IS NULL and a."FDISPOSITION" IS NULL and a."FISLOCKED" = '0' and a."FLOCKEDUSERID" = '0' and a."FISALLOWLOCK" = '0' and a."FISALLOWFORWARD" = '1' and a."FISALLOWBATCHDEAL" = '1' and a."FCANSPECIFYNEXT" = '1' and a."FOPERATIONNUMBER" = ' ' and a."FDEALTIME" = TO_DATE('2023-05-17 09:03:12', 'YYYY-MM-DD HH24:MI:SS') and a."FTIMEOUTDEAL" = '0' and a."FTIMEOUTHOURS" = '0' and a."FTIMEOUTSTRATEGY" = '0' and a."FAUTOAPPROVAL" = ' ' and a."FTIMEOUTDEALWITH" IS NULL and a."FCANADDPARTICIPANT" = '0' and a."FNOTICETYPE" = '4' and a."FSENDMAILTIME" = '0' and a."FSENDSMSTIME" = '0' and a."FMAILNOTICESTATUS" = '0' and a."FSMSNOTICESTATUS" = '0' and a."FISALLOWPASSROUND" = '0' and a."FSENDXUNTONGTIME" = '0' and a."FXUNTONGNOTICESTATUS" = '0' and a."FHASADDSIGN" = '0' and a."FISALLOWADDSIGN" = '0' and a."FREJECTRETURNACT" = '0' and a."FSENDMAILMINUTE" = '0' and a."FSENDSMSMINUTE" = '0' and a."FTIMEOUTMINUTE" = '0' and a."FSENDXUNTONGMINUTE" = '0' and a."FCALENDARID" = '0' and a."FDEALDATEHOURS" = '0' and a."FCOSTHOURS" = '0' and a."FAPPROVALWITHGUI" = '0' and a."FREPEATNOTICEMINUTE" = '0' and a."FREPEATNOTICETIMES" = '0' and a."FREPEATNOTICEMAX" = '0' and a."FMSGNOTICETIME" IS NULL;
	at io.debezium.connector.oracle.logminer.parser.SimpleDmlParser.parse(SimpleDmlParser.java:123)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:397)
	... 14 more
Caused by: java.lang.NumberFormatException: For input string: "\630"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)

### What did you see instead?

Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: Cannot parse DML: update "KINGDEE1"."T_WF_APPROVALASSIGN" a set a."FRESULT" = 'Consent', a."FDISPOSITION" = UNISTR('\\6309S2211110004\\751F\\4EA7\\5F52\\8FD8\\FF0CBOM\\4E0ES221111000402\\7248\\672C\\4FDD\\6301\\4E00\\81F4'), a."FCOSTHOURS" = '.44' where a."FAPPROVALASSIGNID" = '646427d09f1076' and a."FASSIGNID" = '646427d09f1075' and a."FOBJECTTYPEID" = 'SAL_SaleOrder' and a."FKEYVALUE" = '291778' and a."FVARIABLENAME" = 'ActionResult' and a."FDEFAULTRESULT" = 'Consent' and a."FRESULT" IS NULL and a."FDISPOSITION" IS NULL and a."FISLOCKED" = '0' and a."FLOCKEDUSERID" = '0' and a."FISALLOWLOCK" = '0' and a."FISALLOWFORWARD" = '1' and a."FISALLOWBATCHDEAL" = '1' and a."FCANSPECIFYNEXT" = '1' and a."FOPERATIONNUMBER" = ' ' and a."FDEALTIME" = TO_DATE('2023-05-17 09:03:12', 'YYYY-MM-DD HH24:MI:SS') and a."FTIMEOUTDEAL" = '0' and a."FTIMEOUTHOURS" = '0' and a."FTIMEOUTSTRATEGY" = '0' and a."FAUTOAPPROVAL" = ' ' and a."FTIMEOUTDEALWITH" IS NULL and a."FCANADDPARTICIPANT" = '0' and a."FNOTICETYPE" = '4' and a."FSENDMAILTIME" = '0' and a."FSENDSMSTIME" = '0' and a."FMAILNOTICESTATUS" = '0' and a."FSMSNOTICESTATUS" = '0' and a."FISALLOWPASSROUND" = '0' and a."FSENDXUNTONGTIME" = '0' and a."FXUNTONGNOTICESTATUS" = '0' and a."FHASADDSIGN" = '0' and a."FISALLOWADDSIGN" = '0' and a."FREJECTRETURNACT" = '0' and a."FSENDMAILMINUTE" = '0' and a."FSENDSMSMINUTE" = '0' and a."FTIMEOUTMINUTE" = '0' and a."FSENDXUNTONGMINUTE" = '0' and a."FCALENDARID" = '0' and a."FDEALDATEHOURS" = '0' and a."FCOSTHOURS" = '0' and a."FAPPROVALWITHGUI" = '0' and a."FREPEATNOTICEMINUTE" = '0' and a."FREPEATNOTICETIMES" = '0' and a."FREPEATNOTICEMAX" = '0' and a."FMSGNOTICETIME" IS NULL;
	at io.debezium.connector.oracle.logminer.parser.SimpleDmlParser.parse(SimpleDmlParser.java:123)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:397)
	... 14 more
Caused by: java.lang.NumberFormatException: For input string: "\630"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1965.
