### ISSUE TITLE
Flink cdc 为啥把kafka 0.10 以及0.11版本去掉了？

### ISSUE THREAD

**Issue by 812406210** [ververica/flink-cdc-connectors#217]
`) WITH (
   'connector' = 'kafka',
   'topic' = 'user_changelog_json',
   'scan.startup.mode' = 'latest-offset',
   'properties.bootstrap.servers' = 'uat-datacenter1:9092',
   'format' = 'changelog-json'
)`
同一个程序，在1.11版本，kafka0.10 可以使用，在flink1.12 kafka指定为kafka就会出现下面的问题，这个怎么解决了？是不是把0.10的干掉了哦？
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema.<init>(Lorg/apache/flink/table/types/logical/RowType;Lorg/apache/flink/formats/json/TimestampFormat;)V
	at com.alibaba.ververica.cdc.formats.json.ChangelogJsonSerializationSchema.<init>(ChangelogJsonSerializationSchema.java:56)
	at com.alibaba.ververica.cdc.formats.json.ChangelogJsonFormatFactory$2.createRuntimeEncoder(ChangelogJsonFormatFactory.java:112)
	at com.alibaba.ververica.cdc.formats.json.ChangelogJsonFormatFactory$2.createRuntimeEncoder(ChangelogJsonFormatFactory.java:97)
	at org.apache.flink.streaming.connectors.kafka.table.KafkaDynamicSink.createSerialization(KafkaDynamicSink.java:320)
	at org.apache.flink.streaming.connectors.kafka.table.KafkaDynamicSink.getSinkRuntimeProvider(KafkaDynamicSink.java:160)
	at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:77)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.scala:103)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.scala:43)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNode$class.translateToPlan(ExecNode.scala:59)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlan(StreamExecSink.scala:43)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:66)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:65)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.delegation.StreamPlanner.translateToPlan(StreamPlanner.scala:65)
	at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:162)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:676)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:767)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:666)
	at hive.mysql2hive$.main(mysql2hive.scala:84)
	at hive.mysql2hive.main(mysql2hive.scala)

**Comment by leonardBang** [comment]
你这是kafka connector 版本和 flink 版本不匹配问题，不是CDC问题

**Comment by 812406210** [comment]
> 你这是kafka connector 版本和 flink 版本不匹配问题，不是CDC问题
嗯嗯。。。但是我看flink1.12的cdc只支持kafka,和upsertkafka,我的kafka是0.10版本，只能升级kafkab版本解决吗？

**Comment by 812406210** [comment]
> 你这是kafka connector 版本和 flink 版本不匹配问题，不是CDC问题

你好，我kafka升级了，还是不行，还会显示上面的错误。
![image](https://user-images.githubusercontent.com/22192011/122707877-834cc400-d28d-11eb-876d-6b4e59627b9c.png)
` val createMysqlUserTabel =
      """
        |CREATE TABLE `user` (
        |    id INT,
        |    name STRING,
        |    create_time TIMESTAMP(3)
        |) WITH (
        |    'connector' = 'mysql-cdc',
        |    'hostname' = 'localhost',
        |    'port' = '3306',
        |    'username' = 'root',
        |    'password' = 'root',
        |    'database-name' = 'test',
        |    'table-name' = 'user',
        |    'server-time-zone' = 'Asia/Shanghai'
        |)
    """.stripMargin

    //changelog-json
    val createUser2Kafka =
      """
        |CREATE TABLE kafkaUser (
        |    id INT,
        |    name STRING,
        |    create_time TIMESTAMP(3),
        |    primary key(id) not ENFORCED
        |) WITH (
        |   'connector' = 'kafka',
        |   'topic' = 'user_changelog_json',
        |   'properties.group.id' = 'testGroup',
        |   'scan.startup.mode' = 'latest-offset',
        |   'properties.bootstrap.servers' = 'hadoop103:9092',
        |   'format' = 'changelog-json'
        |)
    """.stripMargin


    val kafkaUserSql =
      """
        |insert into kafkaUser
        |    select id,name,create_time
        |    from `user`
      """.stripMargin`

**Comment by leonardBang** [comment]
sql 作业应该用 SQL connector, 你这是datastream connector的依赖

**Comment by 812406210** [comment]
> sql 作业应该用 SQL connector, 你这是datastream connector的依赖

好吧，我看flink1.11使用这个没有问题，所以以为table api和sql 可以共用这个

**Comment by 812406210** [comment]
> sql 作业应该用 SQL connector, 你这是datastream connector的依赖

大佬，我修改format值，把changelog-json改为debezium-json就可以，是不是flinkcdc1.12版本之后changelog-json就不支持了？
