### ISSUE TITLE
flink-connector-postgres-cdc（2.3.0）and flink-connector-kafka（1.17.1）conflicte

### ISSUE THREAD

**Issue by wlfei0502** [ververica/flink-cdc-connectors#2186]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.3.0

### Database and its version

Postgresql（14）

### Minimal reproduce step

pom.xml:
```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <target.java.version>11</target.java.version>
    <maven.compiler.source>${target.java.version}</maven.compiler.source>
    <maven.compiler.target>${target.java.version}</maven.compiler.target>
    <scala.binary.version>2.12</scala.binary.version>
    <flink.version>1.17.1</flink.version>
    <flink.cdc.postgres.version>2.3.0</flink.cdc.postgres.version>
    <flink.kafka.version>3.0.0-1.17</flink.kafka.version>
    <kafka.clients.version>3.4.1</kafka.clients.version>
    <log4j.version>2.20.0</log4j.version>
</properties>
<dependencies>
    <!-- Apache Flink dependencies -->
    <!-- These dependencies are provided, because they should not be packaged into the JAR file. -->
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-streaming-java</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-clients</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-table-api-java-bridge</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-runtime-web</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-connector-kafka</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.flink</groupId>
	    <artifactId>flink-connector-base</artifactId>
	    <version>${flink.version}</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
	    <groupId>org.apache.kafka</groupId>
	    <artifactId>kafka-clients</artifactId>
	    <version>${kafka.clients.version}</version>
    </dependency>
    <!-- Add connector dependencies here. They must be in the default scope (compile). -->
    <dependency>
	    <groupId>com.ververica</groupId>
	    <artifactId>flink-connector-postgres-cdc</artifactId>
	    <version>${flink.cdc.postgres.version}</version>
    </dependency>
    <dependency>
	    <groupId>com.ververica</groupId>
	    <artifactId>flink-sql-connector-postgres-cdc</artifactId>
	    <version>${flink.cdc.postgres.version}</version>
    </dependency>
<dependencies>
```

Run flink job, then throw exception :
java.lang.NoClassDefFoundError: Could not initialize class io.debezium.embedded.EmbeddedEngine$EmbeddedConfig
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:600)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:81)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:302)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:218)
	at io.debezium.embedded.ConvertingEngineBuilder.build(ConvertingEngineBuilder.java:151)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:420)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333)

### What did you expect to see?

Job run successfully！

### What did you see instead?

Job run failure，and restart continuously!

### Anything else?

when I remove flink-connector-kafka from dependenies，everything is ok！

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by menghe999** [comment]
I met the same error

**Comment by ruanhang1993** [comment]
Hi, @wlfei0502.
We only need `flink-sql-connector-postgres-cdc` or `flink-connector-postgres-cdc` in dependencies.

**Comment by menghe999** [comment]
> Hi, @ruanhang1993 . We only need to choose one `flink-sql-connector-postgres-cdc` or `flink-connector-postgres-cdc` in dependencies. No need to contain both two dependencies.

I used cdc 2.4.0 and flink 1.16 and postgresql 14 , import `flink-connector-postgres-cdc` dependence
```
CREATE TABLE t_user (
  id INT,
  name STRING,
  age INT,
  ts DATE
) WITH (
  'connector' = 'postgres-cdc',
  'hostname' = 'xxx',
  'port' = '5432',
  'username' = 'myuser',
  'password' = 'mypass',
  'database-name' = 'mydb',
  'schema-name' = 'public',
  'table-name' = 't_user',
  'slot.name' = 'xxx_test_slot05',
  'decoding.plugin.name' = 'pgoutput',
  'debezium.slot.drop.on.stop' = 'true',
   -- experimental feature: incremental snapshot (default off)
  'scan.incremental.snapshot.enabled' = 'false'
)
```
when config the `scan.incremental.snapshot.enabled=true` , it's fine.  `scan.incremental.snapshot.enabled=false` , It will report an error , as follow

```
java.lang.NoClassDefFoundError: Could not initialize class io.debezium.embedded.EmbeddedEngine$EmbeddedConfig
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:600)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:81)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:302)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:218)
	at io.debezium.embedded.ConvertingEngineBuilder.build(ConvertingEngineBuilder.java:151)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:421)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333)
```

**Comment by ruanhang1993** [comment]
Could you find the class `io.debezium.embedded.EmbeddedEngine$EmbeddedConfig` in your classpath?
If you do not use the sql jar, the dependencies should be added by yourself.
The dependencies we need could be found at the`pom.xml` in `flink-sql-connector-postgres-cdc`.

```xml
                      <artifactSet>
                                <includes>
                                    <include>io.debezium:debezium-api</include>
                                    <include>io.debezium:debezium-embedded</include>
                                    <include>io.debezium:debezium-core</include>
                                    <include>io.debezium:debezium-connector-postgres</include>
                                    <include>com.ververica:flink-cdc-base</include>
                                    <include>com.ververica:flink-connector-debezium</include>
                                    <include>com.ververica:flink-connector-postgres-cdc</include>
                                    <include>com.zaxxer:HikariCP</include>
                                    <include>com.google.protobuf:protobuf-java</include>
                                    <include>com.google.guava:*</include>
                                    <include>org.apache.kafka:*</include>
                                    <include>org.postgresql:postgresql</include>
                                    <include>com.fasterxml.*:*</include>
                                    <!--  Include fixed version 30.1.1-jre-14.0 of flink shaded guava  -->
                                    <include>org.apache.flink:flink-shaded-guava</include>
                                </includes>
                            </artifactSet>
```

**Comment by menghe999** [comment]
thanks, it's my project dependencies  trouble, now have solved。@ruanhang1993

**Comment by tfbi** [comment]
> 

请问你如何解决的，我也出现了这个问题

**Comment by loserwang1024** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
