### ISSUE TITLE
Flink SQL 执行snapshot时java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by zmr518** [ververica/flink-cdc-connectors#224]
Flink 版本1.11.2，cdc版本1.1.0
表数据量20万条，有没有办法分批执行？
java.lang.OutOfMemoryError: Java heap space
	at com.mysql.jdbc.Buffer.(Buffer.java:62)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2024)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3368)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:464)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3070)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2338)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2725)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023)
	at org.apache.flink.api.java.io.jdbc.JDBCInputFormat.open(JDBCInputFormat.java:247)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(SourceFile:85)
	at org.apache.flink.streaming.api.operators.StreamSource.run(SourceFile:103)
	at org.apache.flink.streaming.api.operators.StreamSource.run(SourceFile:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceFile:196)

**Comment by Aria0717** [comment]
hello，这个有解决吗？
