### ISSUE TITLE
[Bug] an exception occurred when restore job from a snapshot which previously sync multiple tables and set scan.incremental.close-idle-reader.enabled=true 

### ISSUE THREAD

**Issue by cygnusdark** [ververica/flink-cdc-connectors#2243]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.7.1

### Flink CDC version

2.4.0

### Database and its version

MySQL 5.7

### Minimal reproduce step

1. start a cdc job wich syncs multiple tables, and has a parallelism more than 1, some configs include:
```
scan.newly-added-table.enabled=true
scan.incremental.close-idle-reader.enabled=true
```
3. stop with a savepoint
4. restart the job with savepoint, add a new table and do not change the previous parallelism
5. an exception occurred:Can not restore vertex Source: MySQL Source -> Process -> (test: Writer -> test: Committer, test2: Writer -> test2: Committer)(cbc357ccb763df2852fee8c4fc7d55f2) which contain mixed operator finished state: [ALL_RUNNING, PARTIALLY_FINISHED]

### What did you expect to see?

The job syncs all the tables, including newly added tables.

### What did you see instead?

An Exception occurred:
org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
	at org.apache.flink.runtime.jobmaster.DefaultJobMasterServiceProcess.lambda$new$0(DefaultJobMasterServiceProcess.java:97)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Can not restore vertex Source: MySQL Source -> Process -> (test: Writer -> test: Committer, test2: Writer -> test2: Committer)(cbc357ccb763df2852fee8c4fc7d55f2) which contain mixed operator finished state: [ALL_RUNNING, PARTIALLY_FINISHED]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	... 3 more
Caused by: org.apache.flink.util.FlinkRuntimeException: Can not restore vertex Source: MySQL Source -> Process -> (test: Writer -> test: Committer, test2: Writer -> test2: Committer)(cbc357ccb763df2852fee8c4fc7d55f2) which contain mixed operator finished state: [ALL_RUNNING, PARTIALLY_FINISHED]
	at org.apache.flink.runtime.checkpoint.VertexFinishedStateChecker$VerticesFinishedStatusCache.calculateFinishedState(VertexFinishedStateChecker.java:190)
	at org.apache.flink.runtime.checkpoint.VertexFinishedStateChecker$VerticesFinishedStatusCache.lambda$getOrUpdate$0(VertexFinishedStateChecker.java:171)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.apache.flink.runtime.checkpoint.VertexFinishedStateChecker$VerticesFinishedStatusCache.getOrUpdate(VertexFinishedStateChecker.java:169)
	at org.apache.flink.runtime.checkpoint.VertexFinishedStateChecker.validateOperatorsFinishedState(VertexFinishedStateChecker.java:70)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.restoreLatestCheckpointedStateInternal(CheckpointCoordinator.java:1737)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.restoreSavepoint(CheckpointCoordinator.java:1873)
	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.tryRestoreExecutionGraphFromSavepoint(DefaultExecutionGraphFactory.java:223)
	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.createAndRestoreExecutionGraph(DefaultExecutionGraphFactory.java:198)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:365)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:210)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:136)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:152)
	at org.apache.flink.runtime.jobmaster.DefaultSlotPoolServiceSchedulerFactory.createScheduler(DefaultSlotPoolServiceSchedulerFactory.java:119)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:371)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:348)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.internalCreateJobMasterService(DefaultJobMasterServiceFactory.java:123)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.lambda$createJobMasterService$0(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:112)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more

### Anything else?

中文描述：
从现象上看，使用scan.incremental.close-idle-reader.enabled=true参数，作业会自动释放资源，但是释放资源后，就不能再返回最初的多并行度状态了。而实际的生产需求往往是：高并行度同步一批表 -> 释放多余资源，恢复并行度1  -> 新增同步一批表，高并行度再次同步完 -> 释放多余资源，恢复并行度1   -> 循环此过程...

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by cygnusdark** [comment]
I carefully followed through this problem, and found the solution to avoid this exception. Here is the step-to-step solution:
1. After snapshot read done, the idle resource will be automatically released.
2. Stop the job with a savepoint
3. Modify scan.incremental.close-idle-reader.enabled = false, and restart the job with latest savepoint.
4. After at least one checkpoint done, stop the job with a savepoint.
5. Then you can add new tables in sync list. However, you ned to make sure scan.incremental.close-idle-reader.enabled=false. If it is set to true, you will find that the new added tables skip the snapshot reading step(you will not find keyword like: snapshot step 1 /step 2 /step 3 in taskmanager.log), and directly read the binlog.

**Comment by ruanhang1993** [comment]
@cygnusdark Thanks for reporting. We will take a look at this.

**Comment by ruanhang1993** [comment]
@cygnusdark This close idle readers feature is only supported in the flink 1.14 or newer version.
But I found another bug when testing. 

Please update the flink version and use the new PR to test. Thanks~
