### ISSUE TITLE
issue: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by Jiabao-Sun** [ververica/flink-cdc-connectors#226]
ClassCastException raises when mapping a MYSQL Integer type to Flink SQL BigInt Type.

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.convertToLong(RowDataDebeziumDeserializeSchema.java:231) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.lambda$wrapIntoNullableConverter$7b91dc26$1(RowDataDebeziumDeserializeSchema.java:394) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.convertField(RowDataDebeziumDeserializeSchema.java:384) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.lambda$createRowConverter$508c5858$1(RowDataDebeziumDeserializeSchema.java:371) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.lambda$wrapIntoNullableConverter$7b91dc26$1(RowDataDebeziumDeserializeSchema.java:394) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.extractAfterRow(RowDataDebeziumDeserializeSchema.java:127) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.deserialize(RowDataDebeziumDeserializeSchema.java:102) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:217) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:151) ~[classes/:?]
    at com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:420) ~[classes/:?]
    at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-streaming-java_2.11-1.13.0.jar:1.13.0]
    at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) ~[flink-streaming-java_2.11-1.13.0.jar:1.13.0]
    at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269) ~[flink-streaming-java_2.11-1.13.0.jar:1.13.0]
```

```sql
# MySQL Table
CREATE TABLE int_type (
    id INT AUTO_INCREMENT NOT NULL,
    int11_c INT(11) ,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;

# Flink SQL Table
CREATE TABLE int_type_source (
    id INT NOT NULL,
    int11_c BIGINT
) WITH (
    'connector' = 'mysql-cdc',
    'table-name' = 'int_type',
    ....
);

CREATE TABLE int_type_sink (
    id INT NOT NULL,
    int11_c BIGINT
) WITH (
    ...
);

```

**Comment by leonardBang** [comment]
Fixed in master: ff9bf31b19e43026ea92b1d42cce21c44bec29cd
