### ISSUE TITLE
[Bug] Caused by: com.mongodb.MongoCommandException: Command failed with error 40576 (Location40576): 'Resume of change stream was not possible, as the resume point may no longer be in the oplog.

### ISSUE THREAD

**Issue by jwsmai** [ververica/flink-cdc-connectors#2279]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

org.apache.flink:flink-java:1.16.1
org.apache.flink:flink-streaming-java:1.16.1

### Flink CDC version

com.ververica:flink-connector-mongodb-cdc:2.4.0

### Database and its version

mongodb 4.0.3 4.0.3-cmongo-

### Minimal reproduce step

```
MongoDBSource<String> mongoSource = MongoDBSource.<String>builder()
                .hosts(config.mongo.hosts)// Set the MongoDB connection URI
                .username(config.mongo.username)
                .password(config.mongo.password)
                .databaseList(config.mongo.database)
                .collectionList(config.mongo.collection)
                .startupOptions(StartupOptions.timestamp(startTime)) // Start from latest offset
                .connectionOptions("authSource=task")
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        // enable checkpoint
        env.enableCheckpointing(3000);
        DataStream<String> dataStream = env.fromSource(mongoSource, WatermarkStrategy.noWatermarks(), "MongoDBIncrementalSource");

 dataStream
                .flatMap(new NestedStructureProcessingFunction())
                .print()
                .setParallelism(1);

        env.execute("mongoDB CDC");
```

### What did you expect to see?

Normal cdc

### What did you see instead?

Caused by: com.mongodb.MongoCommandException: Command failed with error 40576 (Location40576): 'Resume of change stream was not possible, as the resume point may no longer be in the oplog. '
Caused by: org.apache.flink.util.FlinkRuntimeException: Open change stream failed

	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:195) ~[mongodb-driver-core-4.3.4.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:400) ~[mongodb-driver-core-4.3.4.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:324) ~[mongodb-driver-core-4.3.4.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114) ~[mongodb-driver-core-4.3.4.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:604) ~[mongodb-driver-core-4.3.4.jar:?]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuxiqian** [comment]
Seems this error message indicates that MongoDB can't determine exactly startup position. Is that timestamp in the past, and within the available oplog records' time range?

According to [MongoDB documents](https://www.mongodb.com/docs/manual/changeStreams/#resumeafter-for-change-streams), *The oplog must have enough history to locate the operation associated with the token or the timestamp, if the timestamp is in the past.*
