### ISSUE TITLE
io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot

### ISSUE THREAD

**Issue by MorningGlow** [ververica/flink-cdc-connectors#2287]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.15.2    

### Flink CDC version

flink cdc 2.4.0

### Database and its version

oracle 19c

### Minimal reproduce step

CREATE TABLE WIPTRANSACTION_CDC
(
  `SYSID` STRING COMMENT '系统ID'
    ,`FROMID` STRING COMMENT '来源ID'
    ,`LOTID` STRING COMMENT '批次ID'
    ,`WIPLOT` STRING COMMENT '批次'
    ,`STEPID` STRING COMMENT '站点'
    ,`LOCATION` STRING COMMENT '位置'
    ,`EQUIPMENT` STRING COMMENT '设备'
    ,`FIXTURE` STRING COMMENT '载具'
    ,`RULESORT` DECIMAL(38,0) COMMENT 'Rule序号'
    ,`OPERATIONTIME` TIMESTAMP COMMENT '操作时间'
    ,`QTY` DECIMAL(38,0) COMMENT '数量'
    ,`LOTSTATE` STRING COMMENT '批次状态'
    ,`PARENT` STRING COMMENT '合批'
    ,`BATCH` STRING COMMENT 'BATCH'
    ,`REMARK` STRING COMMENT '备注'
    ,`CREATIONID` STRING COMMENT '创建者'
    ,`CREATIONDATE` TIMESTAMP COMMENT '创建日期'
    ,`STEPCODE` STRING COMMENT '站点编号'
    ,`STEPNAME` STRING COMMENT '站名称'
    ,`UNITSEQ` STRING COMMENT '穴位号'
    ,`MINLOCATION` STRING COMMENT '最小位置'
    ,`MINCODE` STRING COMMENT '最小编号'
    ,`MIDCODE` STRING COMMENT '中间编号'
    ,`MIDLOCATION` STRING COMMENT '中间位置'
    ,`MAXCODE` STRING COMMENT '最大编号'
    ,`MAXLOCATION` STRING COMMENT '最大位置'
    ,`RULENAME` STRING
    ,`UNITID` STRING
    ,`PANELID` STRING
    ,`WORKORDER` STRING COMMENT '工单'
    ,`PRODUCTCODE` STRING COMMENT '产品'
    ,`FLOWCODE` STRING COMMENT '工艺'
    ,`SEQUENCE` STRING COMMENT '站点序号'
    ,`BOXSEQ` STRING COMMENT '箱号'
    ,`REELID` STRING COMMENT 'reelid'
    ,`SHIPPINGID` STRING COMMENT '出货id'
    ,`CUSTOMER` STRING COMMENT '客户编号'
    ,`REWORKFLAG` STRING COMMENT '重工标识'
    ,`PASSCOUNT` STRING COMMENT '过站次数'
    ,`UNIT_HT` STRING
    ,PRIMARY KEY ( `SYSID` ) NOT ENFORCED)
WITH(
'connector'='oracle-cdc',
'hostname'='xxxxxxx',
'port'='1521',
'username'='flinkuser',
'password'='xxxxx',
'database-name'='dshwlcsp1',
'scan.startup.mode'='initial',
'schema-name'='baixi',
'debezium.log.mining.batch.size.min'='5000000',
'debezium.log.mining.batch.size.default'='8000000',
'debezium.log.mining.batch.size.max'='10000000',
'debezium.log.mining.sleep.time.increment.ms' = '300000',
'table-name'='WIPTRANSACTION',
'debezium.database.tablename.case.insensitive'='false',
'debezium.log.mining.strategy'='online_catalog',
'debezium.scan.incremental.snapshot.enabled' = 'false'
);

CREATE TABLE WIPTRANSACTION_HUDI (
  `SYSID` STRING COMMENT '系统ID'
    ,`FROMID` STRING COMMENT '来源ID'
    ,`LOTID` STRING COMMENT '批次ID'
    ,`WIPLOT` STRING COMMENT '批次'
    ,`STEPID` STRING COMMENT '站点'
    ,`LOCATION` STRING COMMENT '位置'
    ,`EQUIPMENT` STRING COMMENT '设备'
    ,`FIXTURE` STRING COMMENT '载具'
    ,`RULESORT` DECIMAL(38,0) COMMENT 'Rule序号'
    ,`OPERATIONTIME` STRING COMMENT '操作时间'
    ,`QTY` DECIMAL(38,0) COMMENT '数量'
    ,`LOTSTATE` STRING COMMENT '批次状态'
    ,`PARENT` STRING COMMENT '合批'
    ,`BATCH` STRING COMMENT 'BATCH'
    ,`REMARK` STRING COMMENT '备注'
    ,`CREATIONID` STRING COMMENT '创建者'
    ,`CREATIONDATE` STRING COMMENT '创建日期'
    ,`STEPCODE` STRING COMMENT '站点编号'
    ,`STEPNAME` STRING COMMENT '站名称'
    ,`UNITSEQ` STRING COMMENT '穴位号'
    ,`MINLOCATION` STRING COMMENT '最小位置'
    ,`MINCODE` STRING COMMENT '最小编号'
    ,`MIDCODE` STRING COMMENT '中间编号'
    ,`MIDLOCATION` STRING COMMENT '中间位置'
    ,`MAXCODE` STRING COMMENT '最大编号'
    ,`MAXLOCATION` STRING COMMENT '最大位置'
    ,`RULENAME` STRING
    ,`UNITID` STRING
    ,`PANELID` STRING
    ,`WORKORDER` STRING COMMENT '工单'
    ,`PRODUCTCODE` STRING COMMENT '产品'
    ,`FLOWCODE` STRING COMMENT '工艺'
    ,`SEQUENCE` STRING COMMENT '站点序号'
    ,`BOXSEQ` STRING COMMENT '箱号'
    ,`REELID` STRING COMMENT 'reelid'
    ,`SHIPPINGID` STRING COMMENT '出货id'
    ,`CUSTOMER` STRING COMMENT '客户编号'
    ,`REWORKFLAG` STRING COMMENT '重工标识'
    ,`PASSCOUNT` STRING COMMENT '过站次数'
    ,`UNIT_HT` STRING
    ,`DT` STRING
    ,PRIMARY KEY ( `SYSID` ) NOT ENFORCED)
PARTITIONED BY (`DT`)
WITH (
  'compaction.schedule.enabled' = 'true',
  'hoodie.clean.automatic' = 'true',
  'read.streaming.enabled' = 'true',
  'path' = 'hdfs://ks2p-hadoop01:9000/data/hudi_flink/baixi/WIPTRANSACTION',
  'hoodie.parquet.small.file.limit' = '52428800',
  'hive_sync.enable' = 'true',
  'hoodie.cleaner.commits.retained' = '4',
  'server-time-zone' = 'Asia/Shanghai',
  'connector' = 'hudi',
  'read.streaming.check-interval' = '3',
  'hive_sync.metastore.uris' = 'thrift://ks2p-hadoop01:9083',
  'hive_sync.table' = 'WIPTRANSACTION_HIVE',
  'hoodie.archive.merge.enable' = 'true',
  'hoodie.logfile.max.size' = '134217728',
  'hoodie.keep.min.commits' = '10',
  'compaction.tasks' = '2',
  'hive_sync.db' = 'ods',
  'compaction.trigger.strategy' = 'num_commits',
  'changelog.enabled' = 'true',
  'write.rate.limit' = '100000',
  'hive_sync.support_timestamp' = 'true',
  'write.tasks' = '2',
  'compaction.async.enabled' = 'true',
  'compaction.max_memory' = '512',
  'hoodie.parquet.max.file.size' = '104857600',
  'hoodie.keep.max.commits' = '20',
    'write.operation' = 'upsert',
  'hoodie.datasource.write.recordkey.field' = 'SYSID',
  'hoodie.datasource.write.precombine.field' = 'CREATIONDATE',
  'compaction.delta_commits' = '2',
  'clean.retain_commits' = '4',
  'table.type' = 'MERGE_ON_READ',
  'hive_sync.mode' = 'hms'
);

insert into WIPTRANSACTION_HUDI select 
SYSID,FROMID,LOTID,WIPLOT,STEPID,LOCATION,EQUIPMENT,FIXTURE,RULESORT,DATE_FORMAT(OPERATIONTIME,'yyyy-MM-dd HH:mm:ss'),QTY,
LOTSTATE,PARENT,BATCH,REMARK,CREATIONID,DATE_FORMAT(CREATIONDATE,'yyyy-MM-dd HH:mm:ss'),STEPCODE,STEPNAME,UNITSEQ,MINLOCATION,
MINCODE,MIDCODE,MIDLOCATION,MAXCODE,MAXLOCATION,RULENAME,UNITID,PANELID,WORKORDER,PRODUCTCODE,
FLOWCODE,SEQUENCE,BOXSEQ,REELID,SHIPPINGID,CUSTOMER,REWORKFLAG,PASSCOUNT,UNIT_HT, DATE_FORMAT(CREATIONDATE,'yyyy-MM-dd') 
from WIPTRANSACTION_CDC;

java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:225)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:130)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:519)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:804)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:753)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:59)
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.validateAndLoadDatabaseHistory(OracleSourceFetchTaskContext.java:283)
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.configure(OracleSourceFetchTaskContext.java:117)
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.submitTask(IncrementalSourceStreamFetcher.java:84)
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:138)
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:70)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142)
	... 6 more

### What did you expect to see?

bug fixed

### What did you see instead?

bug fixed

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
