### ISSUE TITLE
OceanBase CDC Connector  Subscription oracle mode data exception

### ISSUE THREAD

**Issue by yuangjiang** [ververica/flink-cdc-connectors#2314]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink versoin 1.14.2

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

OceanBase Enterprise 3.2.3.2
OBProxy Enterprise 3.2.7.1

### Minimal reproduce step

CREATE TABLE tserv_task_obj_dtl (
    id INT,
    root_task_id INT,
    task_id INT,
    obj_type INT,
    obj_idty STRING,
    obj_name STRING,
    prop STRING,
    obj_task_inf STRING,
    org_id INT,
    add_user INT,
    add_time DATE,
    add_mode INT,
    src_idty STRING,
    assn_user INT,
    assn_time DATE,
    assn_mode INT,
    serv_prsn INT,
    serv_mode INT,
    serv_time DATE,
    exec_user INT,
    task_stat INT,
    memo STRING,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
      'connector' = 'oceanbase-cdc',
      'scan.startup.mode' = 'initial',
      'username' = 'test',
      'password' = '123456',
      'tenant-name' = 'test',
      'database-name' = 'test',
      'table-name' = 't_user_info',
      'hostname' = '192.168.157.104',
      'port' = '2883',
      'jdbc.driver' = 'com.oceanbase.jdbc.Driver',
      'compatible-mode' = 'oracle',
      'config-url' = 'http://192.168.157.104:8080/services?Action=ObRootServiceInfo&User_ID=alibaba&UID=ocpmaster&ObRegion=test',
      'rootserver-list' = '192.168.157.104:2883',
      'logproxy.host' = '192.168.157.104',
      'logproxy.port' = '2883'
);

CREATE TABLE print_table WITH ('connector' = 'print')
    LIKE tserv_task_obj_dtl (EXCLUDING ALL);

insert into print_table select  * from tserv_task_obj_dtl ;

### What did you expect to see?

By executing the above SQL, the content in the table can be output normally

### What did you see instead?

[Thread-8] INFO com.oceanbase.clogproxy.client.connection.ClientStream - Reconnect successfully
[log-proxy-client-worker-1-thread-1] INFO com.oceanbase.clogproxy.client.connection.ClientHandler - ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873: cluster_url=http://192.168.157.104:8080/services?Action=ObRootServiceInfo&User_ID=alibaba&UID=ocpmaster&ObRegion=swhy_test connecting LogProxy: 192.168.154.54:2883
[log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - Unsupported protocol version: 18944
[log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - Exception occurred ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873: cluster_url=http://192.168.157.104:8080/services?Action=ObRootServiceInfo&User_ID=alibaba&UID=ocpmaster&ObRegion=swhy_test, with LogProxy: 192.168.154.54:2883
com.oceanbase.clogproxy.client.exception.LogProxyClientException: Unsupported protocol version: 18944
	at com.oceanbase.clogproxy.client.connection.ClientHandler.checkHeader(ClientHandler.java:268)
	at com.oceanbase.clogproxy.client.connection.ClientHandler.handleHeader(ClientHandler.java:185)
	at com.oceanbase.clogproxy.client.connection.ClientHandler.channelRead(ClientHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)
[log-proxy-client-worker-1-thread-1] INFO com.oceanbase.clogproxy.client.connection.ClientHandler - Channel closed with ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873, LogProxy: 192.168.154.54:2883
[Thread-8] INFO com.oceanbase.clogproxy.client.connection.ClientStream - Try to reconnect
[Thread-8] INFO com.oceanbase.clogproxy.client.connection.ClientStream - Reconnect successfully
[log-proxy-client-worker-1-thread-1] INFO com.oceanbase.clogproxy.client.connection.ClientHandler - ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873: cluster_url=http://192.168.157.104:8080/services?Action=ObRootServiceInfo&User_ID=alibaba&UID=ocpmaster&ObRegion=swhy_test connecting LogProxy: 192.168.154.54:2883
[log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - Unsupported protocol version: 18944
[log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - Exception occurred ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873: cluster_url=http://192.168.157.104:8080/services?Action=ObRootServiceInfo&User_ID=alibaba&UID=ocpmaster&ObRegion=swhy_test, with LogProxy: 192.168.154.54:2883
com.oceanbase.clogproxy.client.exception.LogProxyClientException: Unsupported protocol version: 18944
	at com.oceanbase.clogproxy.client.connection.ClientHandler.checkHeader(ClientHandler.java:268)
	at com.oceanbase.clogproxy.client.connection.ClientHandler.handleHeader(ClientHandler.java:185)
	at com.oceanbase.clogproxy.client.connection.ClientHandler.channelRead(ClientHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)
[log-proxy-client-worker-1-thread-1] INFO com.oceanbase.clogproxy.client.connection.ClientHandler - Channel closed with ClientId: 10.9.5.51_20208_1689647263_1_livebos#swhy_test:1662615873, LogProxy: 192.168.154.54:2883
[Checkpoint Timer] INFO org.apache.flink.runtime.checkpoint.CheckpointCoordinator - Triggering checkpoint 5 (type=CHECKPOINT) @ 1689647290256 for job 3095632d9701276a77dd55be3d186729.
[Source: TableSourceScan(table=[[default_catalog, default_database, tserv_task_obj_dtl_mapping]], fields=[id, root_task_id, task_id, obj_type, obj_idty, obj_name, prop, obj_task_inf, org_id, add_user, add_time, add_mode, src_idty, assn_user, assn_time, assn_mode, serv_prsn, serv_mode, serv_time, exec_user, task_stat, memo]) -> NotNullEnforcer(fields=[id]) -> Sink: Sink(table=[default_catalog.default_database.print_table], fields=[id, root_task_id, task_id, obj_type, obj_idty, obj_name, prop, obj_task_inf, org_id, add_user, add_time, add_mode, src_idty, assn_user, assn_time, assn_mode, serv_prsn, serv_mode, serv_time, exec_user, task_stat, memo]) (1/1)#0] INFO com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction - snapshotState checkpoint: 5 at resolvedTimestamp: 0
[jobmanager-io-thread-7] INFO org.apache.flink.runtime.checkpoint.CheckpointCoordinator - Completed checkpoint 5 for job 3095632d9701276a77dd55be3d186729 (212 bytes, checkpointDuration=1 ms, finalizationTime=1 ms).
[PermanentBlobCache shutdown hook] INFO org.apache.flink.runtime.blob.PermanentBlobCache - Shutting down BLOB cache

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by whhe** [comment]
The error message `Unsupported protocol version` shows the `oblogproxy` you used is not compatible with your OceanBase server. 

AFAIK, the enterprise edition of `oblogproxy` is only available for OB Cloud users, you can contact your SA for a confirm.
