### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/flink/api/common/state/CheckpointListener

### ISSUE THREAD

**Issue by HikariB** [ververica/flink-cdc-connectors#234]
Hi，我在运行readme中的示例时，当版本时1.1.0时，运行正常。
```
 <dependency>
            <groupId>com.alibaba.ververica</groupId>
            <artifactId>flink-connector-mysql-cdc</artifactId>
            <version>1.1.0</version>
</dependency>
```
当我想要配置.startupOptions(StartupOptions.earliest())时，我发现需要更高的版本，分别尝试了1.2.0，1.3.0。都遇到了相同的Exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/api/common/state/CheckpointListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.ververica.cdc.connectors.mysql.MySQLSource$Builder.build(MySQLSource.java:220)
	at cdc.MySqlBinlogSourceExample.main(MySqlBinlogSourceExample.java:29)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.api.common.state.CheckpointListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
```
其他运行环境：
flink-1.13.1
<dependency>
    <groupId>org.apache.flink</groupId>
    <artifactId>flink-streaming-java_2.11</artifactId>
    <version>1.9-byted-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.apache.flink</groupId>
    <artifactId>flink-core</artifactId>
    <version>1.9-byted-SNAPSHOT</version>
</dependency>

**Comment by leonardBang** [comment]
This should not relate to cdc, please check your dependencies
