### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by supercena** [ververica/flink-cdc-connectors#2368]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.17.0

### Flink CDC version

flink-connector-oracle-cdc 2.4.0

### Database and its version

oracle 11g 

### Minimal reproduce step

   JdbcIncrementalSource<String> oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname("127.0.0.1")
                        .port(1521)
                        .databaseList("orcl")
                        .tableList("FLINKUSER.C") 
                        .username("flinkuser")
                        .password("oracle")
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(false) // output the schema changes as well
                        .startupOptions(StartupOptions.initial())
                        .debeziumProperties(debeziumProperties)
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.enableCheckpointing(3000);

         DataStreamSink<String> oracleParallelSource = env.fromSource(
                oracleChangeEventSource,
                WatermarkStrategy.noWatermarks(),
                "OracleParallelSource")
                .setParallelism(1).print();
//        env.enableCheckpointing(1000);
        env.execute("Print Oracle Snapshot + RedoLog");

### What did you expect to see?

拉取 oracle  日志，需要 什么file 字段？
JdbcSourceEventDispatcher.schemaChangeRecordValue() 
String fileName = sourceInfo.getString(BINLOG_FILENAME_OFFSET_KEY);
            Long pos = sourceInfo.getInt64(BINLOG_POSITION_OFFSET_KEY);

### What did you see instead?

org.apache.kafka.connect.errors.DataException: file is not a valid field name
	at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254)
	at org.apache.kafka.connect.data.Struct.getCheckType(Struct.java:261)
	at org.apache.kafka.connect.data.Struct.getString(Struct.java:158)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeRecordValue(JdbcSourceEventDispatcher.java:193)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(JdbcSourceEventDispatcher.java:223)
	at io.debezium.connector.oracle.OracleSchemaChangeEventEmitter.emitSchemaChangeEvent(OracleSchemaChangeEventEmitter.java:122)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:147)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:62)
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.dispatchSchemaChangeEventAndGetTableForNewCapturedTable(AbstractLogMinerEventProcessor.java:1018)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by supercena** [comment]
已解决

**Comment by WilliamTan778** [comment]
@supercena 您好,如何解决的

**Comment by ighack** [comment]
@supercena 
How do you fix it

**Comment by mengfanyu** [comment]
@supercena  How do you fix it

**Comment by supercena** [comment]
修改源码 源码做了判断 重新编译
