### ISSUE TITLE
[Bug] Oracle-cdc  truncate source table, task is fail

### ISSUE THREAD

**Issue by WilliamTan778** [ververica/flink-cdc-connectors#2380]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.1

### Database and its version

oracle-11g

### Minimal reproduce step

-- oracle 100万
CREATE TABLE DEBEZIUM.cdc_source_100 (
  id NUMBER(11) NOT NULL,
  name VARCHAR2(255) NOT NULL,
  age NUMBER(11) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  CONSTRAINT cdc_source_100_pk PRIMARY KEY (id)
);

--mysql
CREATE TABLE `cdc_target_100` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `age` int(11) NOT NULL,
  `address` varchar(255) NOT NULL,
  `create_time` datetime NOT NULL,
  `update_time` datetime NOT NULL,
  `insert_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE CATALOG target WITH( 
       'type' = 'jdbc', 
       'default-database' = 'test', 
       'username' = 'root', 
       'password' = 'yunli2@AUG', 
       'base-url' = 'jdbc:mysql://172.30.13.182:3306' 
);

CREATE TABLE cdc_source (
  ID INT,
  NAME STRING,
  AGE INT,
  ADDRESS STRING,
  CREATE_TIME TIMESTAMP(3),
  UPDATE_TIME TIMESTAMP(3),
  PRIMARY KEY (ID) NOT ENFORCED
) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = '172.30.13.181', 
    'port' = '11521',           
    'username' = 'debezium',         
    'password' = '123456',   
    'database-name' = 'HELOWIN',  
    'schema-name' = 'DEBEZIUM',
    'table-name' = 'CDC_SOURCE_100',
    -- 降低延迟使用
    'debezium.log.mining.strategy'='online_catalog',
    'debezium.log.mining.continuous.mine'='true'
);

-- 执行写入操作
insert into target.test.cdc_target_100 select *,now() as insert_time from cdc_source;

-- 当我truncate 源表的之后, 任务就挂了,
<img width="1362" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/41814775/3a1aaea9-46ea-4746-a9f2-ba5117bafd22">

2023-08-10 10:36:37,424 INFO  org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher [] - Split fetcher 0 exited.
2023-08-10 10:36:37,424 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: cdc_source[1] -> DropUpdateBefore[2] -> Calc[3] -> ConstraintEnforcer[4] -> Sink: cdc_target_100[4] (1/1)#8 (2ba4cdad332afac1b9ec2e641636aeff_cbc357ccb763df2852fee8c4fc7d55f2_0_8) switched from RUNNING to FAILED with failure cause:
java.lang.NullPointerException: null
	at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.deserialize(RowDataDebeziumDeserializeSchema.java:137) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitElement(IncrementalSourceRecordEmitter.java:154) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.processElement(IncrementalSourceRecordEmitter.java:117) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:87) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:56) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:144) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:417) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) [flink-dist-1.17.1.jar:1.17.1]
	at java.lang.Thread.run(Unknown Source) [?:?]

### What did you expect to see?

I hope to synchronize data normally after the truncate operation

### What did you see instead?

-- 当我truncate 源表的之后, 任务就挂了,
<img width="1362" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/41814775/3a1aaea9-46ea-4746-a9f2-ba5117bafd22">

2023-08-10 10:36:37,424 INFO  org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher [] - Split fetcher 0 exited.
2023-08-10 10:36:37,424 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: cdc_source[1] -> DropUpdateBefore[2] -> Calc[3] -> ConstraintEnforcer[4] -> Sink: cdc_target_100[4] (1/1)#8 (2ba4cdad332afac1b9ec2e641636aeff_cbc357ccb763df2852fee8c4fc7d55f2_0_8) switched from RUNNING to FAILED with failure cause:
java.lang.NullPointerException: null
	at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.deserialize(RowDataDebeziumDeserializeSchema.java:137) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitElement(IncrementalSourceRecordEmitter.java:154) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.processElement(IncrementalSourceRecordEmitter.java:117) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:87) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:56) ~[flink-sql-connector-oracle-cdc-2.4.1.jar:2.4.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:144) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:417) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) [flink-dist-1.17.1.jar:1.17.1]
	at java.lang.Thread.run(Unknown Source) [?:?]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by WilliamTan778** [comment]
修改源码 RowDataDebeziumDeserializeSchema 类里面的public void deserialize(SourceRecord record, Collector<RowData> out) throws Exception 方法,增加是否为空判断, truncate 操作过滤掉此类事件
![image](https://github.com/ververica/flink-cdc-connectors/assets/41814775/90a93d6b-145a-4f6a-a09e-08ea2f115e00)
