### ISSUE TITLE
[Bug][mysql-cdc]  Unsupported table metadata field type 138

### ISSUE THREAD

**Issue by hanpi14** [ververica/flink-cdc-connectors#2406]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.16.2

### Flink CDC version

2.4.0 and 24.1

### Database and its version

Baidu xdb database

### Minimal reproduce step

My side is the normal parameters to connect the corresponding data to capture data, but the error description when obtaining binlog log type is not supported

### What did you expect to see?

Data normal acquisition

### What did you see instead?

java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:225) ~[flink-connector-files-1.16.2.jar:1.16.2]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169) ~[flink-connector-files-1.16.2.jar:1.16.2]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:130) ~[flink-connector-files-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:545) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:836) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:785) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:914) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550) ~[flink-dist-1.16.2.jar:1.16.2]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150) ~[flink-connector-files-1.16.2.jar:1.16.2]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105) ~[flink-connector-files-1.16.2.jar:1.16.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler.setProducerThrowable(MySqlErrorHandler.java:85) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1553) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1064) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	... 1 more
Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1692171216000, eventType=TABLE_MAP, serverId=2232045869, headerLength=19, dataLength=492, nextPosition=215445478, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1488) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1553) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1064) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	... 1 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1692171216000, eventType=TABLE_MAP, serverId=2232045869, headerLength=19, dataLength=492, nextPosition=215445478, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:341) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:313) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:237) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:259) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1051) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	... 1 more
Caused by: java.io.IOException: Unsupported table metadata field type 138
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:52) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:59) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:37) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:335) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:313) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:237) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:259) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1051) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	... 1 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Hi, @hanpi14 . Thanks for reporting the bug.

This exception will be thrown when the binlog client cannot deserialize the table map event right. 
Could you provide the version of MySQL ?

**Comment by hanpi14** [comment]
Sorry, we are using Baidu's cloud database here, there is an incompatibility, resulting in an error in binlog capture

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
