### ISSUE TITLE
[Bug] [oracle-cdc-2.3.0] no log file has been specified for the current LogMiner session

### ISSUE THREAD

**Issue by Dsrong** [ververica/flink-cdc-connectors#2414]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.3.0

### Database and its version

oracle-19c

### Minimal reproduce step

1、cancel application
2、restart from savepoint

### What did you expect to see?

restart  susscess

### What did you see instead?

com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:325) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:71) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:160) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:122) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_382]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: java.sql.SQLException: ORA-01292: no log file has been specified for the current LogMiner session
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:705) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerHelper.startLogMining(LogMinerHelper.java:237) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:258) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
	... 8 more
Caused by: oracle.jdbc.OracleDatabaseException: ORA-01292: no log file has been specified for the current LogMiner session
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Dsrong** [comment]
This is  cdc code configuretion：  
      proper.setProperty("decimal.handling.mode", "STRING");
        proper.setProperty("log.mining.strategy", "online_catalog");
        proper.setProperty("log.mining.continuous.mine", "true");
        proper.setProperty("debezium.log.mining.continuous.mine", "true");
        proper.setProperty("database.tablename.case.insensitive" ,"false");

**Comment by TammyBice** [comment]
>    This is  cdc code configuretion：  
> 
>       proper.setProperty("decimal.handling.mode", "STRING");
> 
>         proper.setProperty("log.mining.strategy", "online_catalog");
> 
>         proper.setProperty("log.mining.continuous.mine", "true");
> 
>         proper.setProperty("debezium.log.mining.continuous.mine", "true");
> 
>         proper.setProperty("database.tablename.case.insensitive" ,"false");

**Comment by huanzui** [comment]
We have the same problem, because this problem had to give up using flikcdc

**Comment by cooltnt** [comment]
oracle 19c , try to set log.mining.continuous.mine = false

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
