### ISSUE TITLE
Caused by: java.io.EOFException org.apache.flink.core.memory.DataInputDeserializer.readBoolean 

### ISSUE THREAD

**Issue by tttzzzwww** [ververica/flink-cdc-connectors#2422]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

mysql 2.4

### Database and its version

8.0.20

### Minimal reproduce step

Based on the JAVA code for submission

### What did you expect to see?

Does this question need to modify the cdc source code

### What did you see instead?

#1211 

### Anything else?

2023-08-22 19:41:15
org.apache.flink.util.FlinkRuntimeException: Failed to deserialize value
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState$DeserializingIterator.next(SimpleVersionedListState.java:140)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.flink.util.CollectionUtil.iterableToList(CollectionUtil.java:101)
	at org.apache.flink.streaming.api.operators.SourceOperator.open(SourceOperator.java:313)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:731)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:706)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:672)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:904)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException
	at org.apache.flink.core.memory.DataInputDeserializer.readBoolean(DataInputDeserializer.java:125)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserializeSplit(MySqlSplitSerializer.java:164)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:123)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:47)
	at org.apache.flink.core.io.SimpleVersionedSerialization.readVersionAndDeSerialize(SimpleVersionedSerialization.java:227)
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState$DeserializingIterator.next(SimpleVersionedListState.java:138)
	... 13 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tttzzzwww** [comment]
此问题是mysql cdc 2.3 开始，内部出现了同名不同包类冲突的问题，可参考：https://github.com/ververica/flink-cdc-connectors/issues/2423
