### ISSUE TITLE
java.lang.NoSuchMethodError: io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.(Lio/debezium/config/Configuration;Ljava/util/Properties;)V

### ISSUE THREAD

**Issue by tttzzzwww** [ververica/flink-cdc-connectors#2423]
### Search before asking

- [x] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

mysql cdc 2.4

### Database and its version

8.0.20

### Minimal reproduce step

基于上述版本，通过JAVA提交FlinkSQL到Flink平台环境，任务报：
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:225)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:130)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:545)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:836)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:785)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:914)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.<init>(Lio/debezium/config/Configuration;Ljava/util/Properties;)V
	at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.createMySqlConnection(DebeziumUtils.java:85)
	at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.createMySqlConnection(DebeziumUtils.java:78)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.getSnapshotSplitReader(MySqlSplitReader.java:229)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.pollSplitRecords(MySqlSplitReader.java:113)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:80)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

CDC 2.4和对应的debezium-connector-mysql-1.9.7.Final.jar 都存在MySqlConnectionConfiguration类，其构造参数不一致。
排查发现是此合并请求修改了内部jar包类名，错误来源内部jar包类冲突了。
https://github.com/ververica/flink-cdc-connectors/commit/5415bcf0f43db627cd3604697245cc07a630f808#diff-0b6884f030e284e9bd484475c9eb5036eed7320320ad7da6a81435da9e031a6e

根据上述合并请求将其类名还原后，还存在其他类似的问题，构造参数缺失。
@VervericaINFRA 

### What did you expect to see?

no response

### What did you see instead?

no response

### Anything else?

no response

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tttzzzwww** [comment]
问题已解决，不能单独放置cdc jar和对应的debezium-connector-mysql-1.9.7.Final.jar，可将对应版本分支代码下载后自行打包（fat jar），将其依赖一起打包，即可避免此问题。
打包fat jar可参考：https://zhuanlan.zhihu.com/p/43238220

**Comment by luckydarnell** [comment]
> 问题已解决，不能单独放置cdc jar和对应的debezium-connector-mysql-1.9.7.Final.jar，可将对应版本分支代码下载后自行打包（fat jar），将其依赖一起打包，即可避免此问题。 打包fat jar可参考：https://zhuanlan.zhihu.com/p/43238220
> 使用了中央仓库的flink-sql-connector-mysql-cdc-2.4.1.jar后，并删除debezium-connector-mysql-1.9.7.Final.jar、flink-connector-mysql-cdc-2.4.1.jar。提交任务，会接着报Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig。
fat jar 的pom文件能提供一下吗？

**Comment by tttzzzwww** [comment]
&nbsp; &nbsp; &nbsp; 中央仓库提供的cdc jar包仅包含自身，其他依赖jar包是通过pom文件加载，但flink平台不会执行pom，则需要自己添加相关依赖jar，但这样可能会出现类名冲突等问题。
&nbsp; &nbsp; &nbsp; &nbsp;放置在flink平台的jar包，最好包含自身和依赖jar，你得自己拉取cdc最新的4.1分支到本地自行打个jar（包含自身所有依赖jar 可以称之为fat jar），拉取后直接通过maven生成jar，生成后仅在flink平台放置flink-sql-connector-mysql-cdc-2.4.1-snaphot.jar。
&nbsp; &nbsp;可通过更改拉取仓库源码内地子项目flink-sql-connector-mysql-cdc的pom文件来觉得添加哪些依赖（一般全部）。




---Original---
From: ***@***.***&gt;
Date: Thu, Sep 28, 2023 11:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ververica/flink-cdc-connectors] java.lang.NoSuchMethodError:io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.(Lio/debezium/config/Configuration;Ljava/util/Properties;)V(Issue #2423)




  
问题已解决，不能单独放置cdc jar和对应的debezium-connector-mysql-1.9.7.Final.jar，可将对应版本分支代码下载后自行打包（fat jar），将其依赖一起打包，即可避免此问题。 打包fat jar可参考：https://zhuanlan.zhihu.com/p/43238220
 使用了中央仓库的flink-sql-connector-mysql-cdc-2.4.1.jar后，并删除debezium-connector-mysql-1.9.7.Final.jar、flink-connector-mysql-cdc-2.4.1.jar。提交任务，会接着报Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig。
 fat jar 的pom文件能提供一下吗？

**Comment by luckydarnell** [comment]
在项目flink-connector-mysql-cdc的pom文件中添加下面的plugin，重新打包:
```    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>io.debezium:debezium-connector-mysql</include>
                                    <include>com.ververica:flink-connector-debezium</include>
                                </includes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
使用新打的包替换掉原来的debezium-connector-mysql-1.9.7.Final.jar、flink-connector-mysql-cdc-2.4.1.jar

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
