### ISSUE TITLE
oceanbase全量获取的时候数据量大的时候内存溢出。

### ISSUE THREAD

**Issue by jikuanyu** [ververica/flink-cdc-connectors#2429]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink1.17.1

### Flink CDC version

flink-sql-connector-mysql-cdc-2.4.1

### Database and its version

5.7.25-OceanBase_CE-v4.1.0.1

### Minimal reproduce step

023-08-25 05:05:49,459 ERROR com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction [] - Read snapshot from table `nrms`.`t_urc_item_label` failed
java.sql.SQLException: Java heap space
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:553) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:496) ~[flink-sql-connector-mysql-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction.readSnapshotRecordsByTable(OceanBaseRichSourceFunction.java:269) [flink-sql-connector-oceanbase-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction.lambda$readSnapshotRecords$0(OceanBaseRichSourceFunction.java:250) [flink-sql-connector-oceanbase-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction$$Lambda$1224/1140429037.accept(Unknown Source) [flink-sql-connector-oceanbase-cdc-2.4.1.jar:2.4.1]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_43]
	at com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction.readSnapshotRecords(OceanBaseRichSourceFunction.java:247) [flink-sql-connector-oceanbase-cdc-2.4.1.jar:2.4.1]
	at com.ververica.cdc.connectors.oceanbase.source.OceanBaseRichSourceFunction.run(OceanBaseRichSourceFunction.java:162) [flink-sql-connector-oceanbase-cdc-2.4.1.jar:2.4.1]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333) [flink-dist-1.17.1.jar:1.17.1]
Caused by: java.lang.OutOfMemoryError: Java heap space

### What did you expect to see?

oceanbase全量获取的时候数据量大的时候内存溢出。

### What did you see instead?

需要多次获取，不要一次把数据放入内存。否则数据量大的时候内存溢出。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jikuanyu** [comment]
期待新版本中，有好的体验。
