### ISSUE TITLE
[Bug] FLINK_MYSQL_CDC unexpected input error

### ISSUE THREAD

**Issue by kendn1993** [ververica/flink-cdc-connectors#2446]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

   <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-connector-mysql-cdc</artifactId>
            <version>2.4.1</version>
        </dependency>

### Database and its version

mysql 5.7.32-log

### Minimal reproduce step

after running for awhile,this question occures

### What did you expect to see?

[INFO] 2023-08-30 13:38:40.158 +0800 -  -> 
	------------------------------------------------------------
	 The program finished with the following exception:
	
	org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 101c0f5730d726c44cc40474f0c79280)
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
		at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
		at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:105)
		at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:851)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:245)
		at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1095)
		at org.apache.flink.client.cli.CliFrontend.lambda$mainInternal$9(CliFrontend.java:1189)
		at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
		at org.apache.flink.client.cli.CliFrontend.mainInternal(CliFrontend.java:1189)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1157)
	Caused by: java.util.concurrent.ExecutionException: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 101c0f5730d726c44cc40474f0c79280)
		at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
		at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
		at org.apache.flink.client.program.StreamContextEnvironment.getJobExecutionResult(StreamContextEnvironment.java:171)
		at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:122)
		at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2058)
		at com.chinaentropy.binlog.BinlogParseMain.main(BinlogParseMain.java:218)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
		... 9 more
	Caused by: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 101c0f5730d726c44cc40474f0c79280)
		at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:130)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
		at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperationWithDelay$6(FutureUtils.java:302)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
		at org.apache.flink.client.program.rest.RestClusterClient.lambda$pollResourceAsync$32(RestClusterClient.java:787)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
		at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperationWithDelay$6(FutureUtils.java:302)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
		at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
		at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
		at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
		at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
		at org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:128)
		... 24 more
	Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by FixedDelayRestartBackoffTimeStrategy(maxNumberRestartAttempts=3, backoffTimeMS=10000)
		at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:139)
		at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:83)
		at org.apache.flink.runtime.scheduler.DefaultScheduler.recordTaskFailure(DefaultScheduler.java:258)
		at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:249)
		at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:242)
		at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:748)
		at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:725)
		at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:80)
		at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:479)
		at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:309)
		at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
		at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:307)
		at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:222)
		at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:84)
		at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:168)
		at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
		at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
		at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
		at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
		at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
		at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
		at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
		at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
		at akka.actor.Actor.aroundReceive(Actor.scala:537)
		at akka.actor.Actor.aroundReceive$(Actor.scala:535)
		at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
		at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
		at akka.actor.ActorCell.invoke(ActorCell.scala:547)
		at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
		at akka.dispatch.Mailbox.run(Mailbox.scala:231)
		at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Caused by: java.lang.IllegalArgumentException: Unexpected input: m
		at io.debezium.relational.TableIdParser$ParsingState$3.handleCharacter(TableIdParser.java:144)
		at io.debezium.relational.TableIdParser$TableIdTokenizer.tokenize(TableIdParser.java:64)
		at io.debezium.text.TokenStream.start(TokenStream.java:446)
		at io.debezium.relational.TableIdParser.parse(TableIdParser.java:31)
		at io.debezium.relational.TableId.parseParts(TableId.java:51)
		at io.debezium.relational.TableId.parse(TableId.java:40)
		at io.debezium.relational.TableId.parse(TableId.java:27)
		at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.readTableSchemas(MySqlSplitSerializer.java:203)
		at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserializeSplit(MySqlSplitSerializer.java:140)
		at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:123)
		at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:47)
		at org.apache.flink.runtime.source.event.AddSplitEvent.splits(AddSplitEvent.java:52)
		at org.apache.flink.streaming.api.operators.SourceOperator.handleAddSplitsEvent(SourceOperator.java:573)
		at org.apache.flink.streaming.api.operators.SourceOperator.handleOperatorEvent(SourceOperator.java:561)
		at org.apache.flink.streaming.runtime.tasks.OperatorEventDispatcherImpl.dispatchEventToHandlers(OperatorEventDispatcherImpl.java:72)
		at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.dispatchOperatorEvent(RegularOperatorChain.java:80)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$dispatchOperatorEvent$20(StreamTask.java:1473)
		at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
		at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
		at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMail(MailboxProcessor.java:398)
		at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:367)
		at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:352)
		at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:229)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788)
		at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)
		at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931)
		at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)
		at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
		at java.lang.Thread.run(Thread.java:748)
[INFO] 2023-08-30 13:38:40.163 +0800 - FINALIZE_SESSION

### What did you see instead?

nothing

### Anything else?

nothing

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by kendn1993** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/27141040/effb17f2-c6f0-4078-b2c4-f467aaf14c25)
caused by not standard tableName
