### ISSUE TITLE
[Bug] Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足。

### ISSUE THREAD

**Issue by YongkuiYang** [ververica/flink-cdc-connectors#2462]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.2.1

### Database and its version

Sqlserver2014

### Minimal reproduce step

1.  Create some table and enable cdc
2.  Continuously inserting and deleting rows in these table 
3. Create Flink sql job, The job structure is very simple, each job only synchronize one table. and it will be works fine at first
4. A few hours later(maybe a few days), this error happend:
    2023-09-05 09:29:44
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:292)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5427)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1758)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1016)
	at io.debezium.pipeline.source.spi.ChangeTableResultSet.next(ChangeTableResultSet.java:63)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.lambda$execute$1(SqlServerStreamingChangeEventSource.java:181)
	at io.debezium.jdbc.JdbcConnection.prepareQuery(JdbcConnection.java:608)
	at io.debezium.connector.sqlserver.SqlServerConnection.getChangesForTables(SqlServerConnection.java:226)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:171)
	... 7 more

### What did you expect to see?

The job always works fine without any exception

### What did you see instead?

the job will be restart when the exception occured

### Anything else?

 There is another bug with the same reproduce step.
 After the jobs run a few days, some jobs stop incremental synchronization for some reason. and there is no exception in flink log and db log.
We don't know how to investigate the root cause of the problem without any error or warn log

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wsczm** [comment]
laoge, have you ever encountered a situation where a table is locked

**Comment by YongkuiYang** [comment]
this issue fixed by upgrade cdc version to 2.4.1.
