### ISSUE TITLE
[Bug] The connector is trying to read binlog starting at Struct{version=1.9.7.Final,connector=mysql, ... } but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

### ISSUE THREAD

**Issue by live-github** [ververica/flink-cdc-connectors#2476]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Flink 1.14.6

### Flink CDC version

Flink CDC 2.4.1

### Database and its version

Aliyun RDS MySQL

### Minimal reproduce step

1. Using sql-client submit cdc for simple table
2. Switch the binlog file to a new file and delete the old file

### What did you expect to see?

CDC automatically detects new binlogs and continues to synchronize data

### What did you see instead?

CDC did not automatically detect new binlogs and attempted to consume old files

### Anything else?

Flink 1.14.6 CDC 2.4.1
[Bug] The connector is trying to read binlog starting at Struct{version=1.9.7.Final,connector=mysql, ... } but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

Aliyun RDS MySQL file mysql-bin.00xxx update, the CDC does not automatically update, resulting in the binlog being stuck in the old binlog file after deletion.

In addition, inconsistency between CDC data count(*) and database data count(*) after full synchronization.

Is there any setting for CDC???

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by esondeng** [comment]
I meet the same issue. Is there any solution?

**Comment by esondeng** [comment]
use StartupOptions.initial()， after run about 15 minutes， it could has this issue。Mysql parameter is
expire_logs_days = 3
max_binlog_size = 512M

2023-10-11 11:03:33,120 flink-akka.actor.default-dispatcher-18 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: mysqlSource (1/1) (26ea424192a50930339526044c4bf9a8_bc764cd8ddf7a0cff126f51c16239658_0_0) switched from RUNNING to FAILED on container_e12_1695360459197_0163_01_000002 @ flink-p2 (dataPort=43469).
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:261) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:131) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:417) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839) ~[drs-server.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788) ~[drs-server.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952) ~[drs-server.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931) ~[drs-server.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745) ~[drs-server.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) ~[drs-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_311]
Caused by: java.lang.RuntimeException: SplitFetcher thread 519 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:114) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_311]
	... 1 more
Caused by: java.lang.IllegalStateException: The connector is trying to read binlog starting at Struct{version=1.9.7.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1696993413099,db=,server_id=0,file=mysql-bin.049194,pos=1819370,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.loadStartingOffsetState(StatefulTaskContext.java:203) ~[drs-server.jar:?]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.configure(StatefulTaskContext.java:127) ~[drs-server.jar:?]
	at com.ververica.cdc.connectors.mysql.debezium.reader.BinlogSplitReader.submitSplit(BinlogSplitReader.java:105) ~[drs-server.jar:?]
	at com.ververica.cdc.connectors.mysql.debezium.reader.BinlogSplitReader.submitSplit(BinlogSplitReader.java:73) ~[drs-server.jar:?]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.pollSplitRecords(MySqlSplitReader.java:109) ~[drs-server.jar:?]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:80) ~[drs-server.jar:?]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:114) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_311]

**Comment by ruanhang1993** [comment]
This exception occurs when the binlog file expired before we consume it. Please try to set a longer expiration for it.

If this problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
