### ISSUE TITLE
Postgres Delete/Update操作未正常同步

### ISSUE THREAD

**Issue by Sdu0** [ververica/flink-cdc-connectors#25]
### 问题描述
- 当我在 PG 中创建了对应的数据库和表，也在 Flink 中创建了对应的表，之后提交了一个Flink 的 Job。我发现Insert的数据可以正常同步，但是我通过Delete 和 Update的数据不能正常同步。

### 环境
- Postgres ：来自于 https://github.com/ververica/flink-cdc-connectors/wiki/%E4%B8%AD%E6%96%87%E6%95%99%E7%A8%8B
- Flink：1.11.1
- Java: 1.8.0_181
- CDC: 1.0.0 和 1.1.0 

### Postgres 建表语句
```sql
create database seesaw_boh_test_report;

\c seesaw_boh_test_report;

create table store_caches
(
    id      bigserial not null primary key,
    geos    bigint[],
    geo0    bigint,
    geo1    bigint,
    geo2    bigint,
    branchs bigint[],
    branch0 bigint,
    branch1 bigint,
    branch2 bigint
);
create table sales_ticket_amounts
(
    id              bigserial                not null primary key,
    partner_id      bigint                   not null,
    scope_id        bigint                   not null,
    bus_date        date                     not null,
    bus_date_week   date                     not null,
    bus_date_month  date                     not null,
    bus_date_year   date                     not null,
    store_id        bigint                   not null,
    eticket_id      bigint                   not null unique,
    channel_id      bigint                   not null,
    channel_name    varchar(50)              not null,
    order_type      varchar(15)              not null,
    order_type_name varchar(15)              not null,
    order_time      timestamp                not null,
    refunded        boolean                  not null,
    gross_amount    numeric(38, 16)          not null,
    net_amount      numeric(38, 16)          not null,
    discount_amount numeric(38, 16)          not null,
    tip             numeric(38, 16)          not null,
    package_fee     numeric(38, 16)          not null,
    delivery_fee    numeric(38, 16)          not null,
    service_fee     numeric(38, 16)          not null,
    tax_fee         numeric(38, 16)          not null,
    other_fee       numeric(38, 16)          not null,
    pay_amount      numeric(38, 16)          not null,
    rounding        numeric(38, 16)          not null,
    overflow_amount numeric(38, 16)          not null,
    change_amount   numeric(38, 16)          not null,
    product_count   bigint                   not null,
    accessory_count bigint                   not null,
    eticket_count   bigint                   not null,
    created         TIMESTAMP                not null
);

-- store sales
create table store_sales
(
    bus_date date,
    store_id   bigint,
    gross_amount numeric(38, 16),
    net_amount numeric(38, 16),
    discount_amount numeric(38, 16),
    tip numeric(38, 16),
    package_fee numeric(38, 16),
    delivery_fee numeric(38, 16),
    service_fee numeric(38, 16),
    tax_fee numeric(38, 16),
    other_fee numeric(38, 16),
    pay_amount numeric(38, 16),
    rounding numeric(38, 16),
    overflow_amount numeric(38, 16),
    change_amount numeric(38, 16),
    order_count bigint,
    product_count bigint,
    accessory_count bigint,
    gross_amount_returned numeric(38, 16),
    net_amount_returned numeric(38, 16),
    discount_amount_returned numeric(38, 16),
    tip_returned numeric(38, 16),
    package_fee_returned numeric(38, 16),
    delivery_fee_returned numeric(38, 16),
    service_fee_returned numeric(38, 16),
    tax_fee_returned numeric(38, 16),
    other_fee_returned numeric(38, 16),
    pay_amount_returned numeric(38, 16),
    rounding_returned numeric(38, 16),
    overflow_amount_returned numeric(38, 16),
    change_amount_returned numeric(38, 16),
    order_count_returned bigint,
    primary key (bus_date, store_id)
)
```
### Postgres 测试数据
```sql
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4373457990955565057, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481,4373058975772442625}', 4373058638818836481, 4373058975772442625, 0);
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4374825247166169089, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481}', 4373058638818836481, 0, 0);
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4374825441484079105, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481}', 4373058638818836481, 0, 0);
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4374826876435169281, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481}', 4373058638818836481, 0, 0);
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4374828784109486081, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481}', 4373058638818836481, 0, 0);
INSERT INTO public.store_caches (id, geos, geo0, geo1, geo2, branchs, branch0, branch1, branch2) VALUES (4374830781730652161, '{4372623784113340417}', 4372623784113340417, 0, 0, '{4373058638818836481,4373059076356046849,4395459768047632385}', 4373058638818836481, 4373059076356046849, 4395459768047632385);
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388631539257212928, 0, 0, '0001-01-01', '0001-01-01', '0001-01-01', '0001-01-01', 4373457990955565057, 20200728042, 4378501562742341633, 'koubei', 'DINEIN', 'DINEIN', '0001-01-01 00:00:00.000000', false, 74.0000000000000000, 69.0000000000000000, 5.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 70.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000, 3, 3, 1, '2020-08-05 07:34:55.754688');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388636043784519680, 0, 0, '2020-08-05', '2020-08-07', '2020-08-01', '2020-01-01', 4373457990955565057, 2020072804211, 4378501562742341633, 'koubei', 'DINEIN', 'DINEIN', '2020-08-05 12:30:00.000000', false, 74.0000000000000000, 69.0000000000000000, 5.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 70.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000, 3, 3, 1, '2020-08-05 07:52:49.752072');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388640055850205184, 4183192445833445399, 0, '2020-08-05', '2020-08-07', '2020-08-01', '2020-01-01', 4373457990955565057, 20200728042111, 4378501562742341633, 'koubei', 'DINEIN', 'DINEIN', '2020-08-05 12:30:00.000000', false, 74.0000000000000000, 69.0000000000000000, 5.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 70.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000, 3, 3, 1, '2020-08-05 08:08:46.263721');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388632714543136768, 0, 0, '2020-08-05', '2020-08-07', '2020-08-01', '2020-01-01', 4373457990955565057, 202007280421, 4378501562742341633, 'koubei', 'DINEIN', 'DINEIN', '2020-08-05 12:30:00.000000', false, 74.0000000000000000, 69.0000000000000000, 5.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 70.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000, 3, 3, 1, '2020-08-05 07:39:35.997823');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388673806802124800, 4183192445833445399, 0, '2020-08-05', '2020-08-03', '2020-08-01', '2020-01-01', 4374830781730652161, 1234567, 4383963285460877313, 'INVALID', 'DINEIN', 'DINEIN', '2020-08-05 13:20:07.000000', false, 48.0000000000000000, 48.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 48.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1, 0, 1, '2020-08-05 10:22:53.157638');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388645720765267968, 4183192445833445399, 0, '2020-08-05', '2020-08-03', '2020-08-01', '2020-01-01', 4373457990955565057, 202007280421111, 4378501562742341633, 'koubei', 'DINEIN', 'DINEIN', '2020-08-05 12:30:00.000000', false, 74.0000000000000000, 69.0000000000000000, 5.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 70.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000, 3, 3, 1, '2020-08-05 08:31:16.924693');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388641911280271360, 4183192445833445399, 0, '2020-08-05', '2020-08-07', '2020-08-01', '2020-01-01', 4374825247166169089, 0, 4378501476008329217, 'eleme', 'TAKEOUT', 'TAKEOUT', '2020-08-05 14:11:17.000000', false, 38.0000000000000000, 26.7000007629394530, 11.3000001907348630, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 26.7000007629394530, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1, 0, 1, '2020-08-05 08:16:08.635261');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4388650429982998528, 4183192445833445399, 0, '2020-08-05', '2020-08-03', '2020-08-01', '2020-01-01', 4374825441484079105, 9223372036854775807, 4383963285460877313, 'INVALID', 'DINEIN', 'DINEIN', '2020-08-05 16:49:58.000000', false, 90.0000000000000000, 90.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 90.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 2, 0, 1, '2020-08-05 08:49:59.661589');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4389379207717748736, 4183192445833445399, 0, '2020-08-07', '2020-08-03', '2020-08-01', '2020-01-01', 4374828784109486081, 4389379206568509440, 4383963285460877313, 'INVALID', 'DINEIN', 'DINEIN', '2020-08-07 16:10:11.000000', false, 113.0000000000000000, 113.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 113.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 3, 0, 1, '2020-08-07 09:05:53.849608');
INSERT INTO public.sales_ticket_amounts (id, partner_id, scope_id, bus_date, bus_date_week, bus_date_month, bus_date_year, store_id, eticket_id, channel_id, channel_name, order_type, order_type_name, order_time, refunded, gross_amount, net_amount, discount_amount, tip, package_fee, delivery_fee, service_fee, tax_fee, other_fee, pay_amount, rounding, overflow_amount, change_amount, product_count, accessory_count, eticket_count, created) VALUES (4389379207168294912, 4183192445833445399, 0, '2020-08-07', '2020-08-03', '2020-08-01', '2020-01-01', 4374826876435169281, 4389379205146640384, 4383963285460877313, 'INVALID', 'SELFHELP', 'SELFHELP', '2020-08-07 12:18:01.000000', false, 33.0000000000000000, 0.0000000000000000, 33.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1, 0, 1, '2020-08-07 09:05:53.717730');
```

### Flink 建表
```sql
create table store_caches
(
    id      bigint primary key,
    geo0    bigint,
    geo1    bigint,
    geo2    bigint,
    branch0 bigint,
    branch1 bigint,
    branch2 bigint
)
WITH (
    'connector' = 'postgres-cdc',
    'hostname' = '127.0.0.1',
    'port' = '5432',
    'username' = 'postgres',
    'password' = 'postgres',
    'database-name' = 'seesaw_boh_test_report',
    'schema-name' = 'public',
    'table-name' = 'store_caches',
    'debezium.slot.name' = 'store_caches'
);

 create table sales_ticket_amounts
(
    id              bigint        primary key,
    partner_id      bigint          ,
    scope_id        bigint          ,
    bus_date        date            ,
    bus_date_week   date            ,
    bus_date_month  date            ,
    bus_date_year   date            ,
    store_id        bigint          ,
    eticket_id      bigint          ,
    channel_id      bigint          ,
    channel_name    varchar(50)     ,
    order_type      varchar(15)     ,
    order_type_name varchar(15)     ,
    order_time      timestamp       ,
    refunded        boolean         ,
    gross_amount    numeric(38, 16) ,
    net_amount      numeric(38, 16) ,
    discount_amount numeric(38, 16) ,
    tip             numeric(38, 16) ,
    package_fee     numeric(38, 16) ,
    delivery_fee    numeric(38, 16) ,
    service_fee     numeric(38, 16) ,
    tax_fee         numeric(38, 16) ,
    other_fee       numeric(38, 16) ,
    pay_amount      numeric(38, 16) ,
    rounding        numeric(38, 16) ,
    overflow_amount numeric(38, 16) ,
    change_amount   numeric(38, 16) ,
    product_count   bigint          ,
    accessory_count bigint          ,
    eticket_count   bigint          ,
    created         TIMESTAMP       
)
WITH (
    'connector' = 'postgres-cdc',
    'hostname' = '127.0.0.1',
    'port' = '5432',
    'username' = 'postgres',
    'password' = 'postgres',
    'database-name' = 'seesaw_boh_test_report',
    'schema-name' = 'public',
    'table-name' = 'sales_ticket_amounts',
    'debezium.slot.name' = 'sales_ticket_amounts'
);

create table store_sales
(
    bus_date date,
    store_id bigint,
    gross_amount numeric(38, 16),
    net_amount numeric(38, 16),
    discount_amount numeric(38, 16),
    tip numeric(38, 16),
    package_fee numeric(38, 16),
    delivery_fee numeric(38, 16),
    service_fee numeric(38, 16),
    tax_fee numeric(38, 16),
    other_fee numeric(38, 16),
    pay_amount numeric(38, 16),
    rounding numeric(38, 16),
    overflow_amount numeric(38, 16),
    change_amount numeric(38, 16),
    order_count bigint,
    product_count bigint,
    accessory_count bigint,
    gross_amount_returned numeric(38, 16),
    net_amount_returned numeric(38, 16),
    discount_amount_returned numeric(38, 16),
    tip_returned numeric(38, 16),
    package_fee_returned numeric(38, 16),
    delivery_fee_returned numeric(38, 16),
    service_fee_returned numeric(38, 16),
    tax_fee_returned numeric(38, 16),
    other_fee_returned numeric(38, 16),
    pay_amount_returned numeric(38, 16),
    rounding_returned numeric(38, 16),
    overflow_amount_returned numeric(38, 16),
    change_amount_returned numeric(38, 16),
    order_count_returned bigint,
    PRIMARY KEY(bus_date, store_id) NOT ENFORCED
)
WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:postgresql://127.0.0.1:5432/seesaw_boh_test_report',
    'username' = 'postgres',
    'password' = 'postgres',
    'table-name' = 'store_sales'
);
```

### Flink 添加 Job
```sql
INSERT INTO store_sales(
    bus_date,store_id,gross_amount,net_amount,discount_amount,tip,package_fee,delivery_fee,
    service_fee,tax_fee,other_fee,pay_amount,rounding,overflow_amount,change_amount,order_count,
    product_count,accessory_count,gross_amount_returned,net_amount_returned,discount_amount_returned,
    tip_returned,package_fee_returned,delivery_fee_returned,service_fee_returned,tax_fee_returned,
    other_fee_returned,pay_amount_returned,rounding_returned,overflow_amount_returned,change_amount_returned,
    order_count_returned
)
SELECT
    sales_ticket_amounts.bus_date AS bus_date,
    store_caches.id AS store_id,
    SUM(gross_amount) AS gross_amount,
    SUM(net_amount) AS net_amount,
    SUM(discount_amount) AS discount_amount,
    SUM(tip) AS tip,
    SUM(package_fee) AS package_fee,
    SUM(delivery_fee) AS delivery_fee,
    SUM(service_fee) AS service_fee,
    SUM(tax_fee) AS tax_fee,
    SUM(other_fee) AS other_fee,
    SUM(pay_amount) AS pay_amount,
    SUM(rounding) AS rounding,
    SUM(overflow_amount) AS overflow_amount,
    SUM(CASE WHEN refunded THEN 0 ELSE change_amount END) AS change_amount,
    SUM(CASE WHEN refunded THEN 0 ELSE eticket_count END) AS order_count,
    SUM(CASE WHEN refunded THEN 0 ELSE product_count END) AS product_count,
    SUM(CASE WHEN refunded THEN 0 ELSE accessory_count END) AS accessory_count,
    SUM(CASE WHEN refunded THEN gross_amount ELSE 0 END) AS gross_amount_returned,
    SUM(CASE WHEN refunded THEN net_amount ELSE 0 END) AS net_amount_returned,
    SUM(CASE WHEN refunded THEN discount_amount ELSE 0 END) AS discount_amount_returned,
    SUM(CASE WHEN refunded THEN tip ELSE 0 END) AS tip_returned,
    SUM(CASE WHEN refunded THEN package_fee ELSE 0 END) AS package_fee_returned,
    SUM(CASE WHEN refunded THEN delivery_fee ELSE 0 END) AS delivery_fee_returned,
    SUM(CASE WHEN refunded THEN service_fee ELSE 0 END) AS service_fee_returned,
    SUM(CASE WHEN refunded THEN tax_fee ELSE 0 END) AS tax_fee_returned,
    SUM(CASE WHEN refunded THEN other_fee ELSE 0 END) AS other_fee_returned,
    SUM(CASE WHEN refunded THEN pay_amount ELSE 0 END) AS pay_amount_returned,
    SUM(CASE WHEN refunded THEN rounding ELSE 0 END) AS rounding_returned,
    SUM(CASE WHEN refunded THEN overflow_amount ELSE 0 END) AS overflow_amount_returned,
    SUM(CASE WHEN refunded THEN change_amount ELSE 0 END) AS change_amount_returned,
    SUM(CASE WHEN refunded THEN eticket_count ELSE 0 END) AS order_count_returned
FROM
    sales_ticket_amounts
        LEFT JOIN store_caches ON sales_ticket_amounts.store_id = store_caches.id
GROUP BY
    sales_ticket_amounts.bus_date,
    store_caches.id
```

**Comment by Sdu0** [comment]
我找到原因了。原来是需要设置 Postgres 表的 REPLICA IDENTITY。
```sql
ALTER TABLE your_table REPLICA IDENTITY FULL;
```

**Comment by zzy-data-coder** [comment]
> 我找到原因了。原来是需要设置 Postgres 表的 REPLICA IDENTITY。
> 
> ```sql
> ALTER TABLE your_table REPLICA IDENTITY FULL;
> ```

您好，有个问题想向您请教下，我是从MySQL到postgresql同步数据，通过jdbc的方式，但是在执行flink job insert into插入到postgresql表的时候有报错，
报错如下：
```
2020-11-11 10:33:46
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:503)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:386)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:284)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:199)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:152)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.checkFlushException(JdbcBatchingOutputFormat.java:142)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.writeRecord(JdbcBatchingOutputFormat.java:148)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:87)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:86)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
	at StreamExecCalc$249.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:305)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:394)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.emitRecords(DebeziumChangeConsumer.java:159)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.emitRecordsUnderCheckpointLock(DebeziumChangeConsumer.java:145)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.handleBatch(DebeziumChangeConsumer.java:113)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:81)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:812)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.checkFlushException(JdbcBatchingOutputFormat.java:142)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.flush(JdbcBatchingOutputFormat.java:167)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.lambda$open$0(JdbcBatchingOutputFormat.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	... 3 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
```
我是直接部署flink1.11.2的版本，然后在flink sql client进行测试的，您这边可以通过jdbc的形式同步数据，请问您这边对于flink1.11的包又添加什么文件了或者修改什么东西了吗？还望指点一下，谢谢。
