### ISSUE TITLE
[Bug] org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out

### ISSUE THREAD

**Issue by yanye666** [ververica/flink-cdc-connectors#2535]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.17.1

### Flink CDC version

flink cdc 2.4.1

### Database and its version

PostgreSQL 12.13 (Debian 12.13-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Minimal reproduce step

``````

create table test
(
    id      bigserial,
    card_no text
);
INSERT INTO public.test (id, card_no)
VALUES (1, '1');

    create table test
(
    id      BIGINT,
    card_no STRING
) WITH (
      'connector' = 'postgres-cdc', 
      'hostname' = 'localhost', 
      'port' = '5432', 
      'username' = 'postgres', 
      'password' = 'password', 
      'database-name' = 'sales_db0', 
      'schema-name' = 'public', 
      'table-name' = 'public.test', 
      'slot.name' = 'flink_cdc1', 
      'decoding.plugin.name' = 'pgoutput',
      'scan.incremental.snapshot.enabled' = 'true'
    );



``````

### What did you expect to see?

The console has data output, and the task execution status is normal.

### What did you see instead?

There is no output in the console. An error was reported after waiting for a period of time.
<img width="1410" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/42414099/d10ee231-7c32-490e-98fe-8a1906e4e42e">
<img width="978" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/42414099/52878a5c-2d6b-4a2f-9f5b-03035a1b083e">

Task is automatically canceled, no error log

<img width="1156" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/42414099/533fb6ef-c6aa-4a15-b9f0-85ecfe05190d">
<img width="1191" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/42414099/962362d2-43a7-4f5f-9152-0eec47449208">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yanye666** [comment]
[flink-yanlun-taskexecutor-14-MacBook-Pro-5.local.log](https://github.com/ververica/flink-cdc-connectors/files/12836973/flink-yanlun-taskexecutor-14-MacBook-Pro-5.local.log)
[flink-yanlun-standalonesession-14-MacBook-Pro-5.local.log](https://github.com/ververica/flink-cdc-connectors/files/12836974/flink-yanlun-standalonesession-14-MacBook-Pro-5.local.log)

**Comment by ilwyiworld** [comment]
我也碰到了，一模一样的日志
**Flink version**
flink 1.18.0

**Flink CDC version**
flink cdc 2.4.0

**Database and its version**
PostgreSQL (版本 15.3 (Ubuntu 15.3-1.pgdg18.04+1))

**Comment by dyz1027543829** [comment]
i came across this problem too, but i was testing self-defined table&sql sinks. It works well under ide running env, however, when i tried in flink sql-client, it failed and returned:

`
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out: localhost/127.0.0.1:64563
`

I check logs in flink dashboard, and find exception log in taskManager's stdout:
`
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at com.openpie.SocketSourceFunction.run(SocketSourceFunction.java:67)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:114)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:71)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:338)
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at com.openpie.SocketSourceFunction.run(SocketSourceFunction.java:67)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:114)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:71)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:338)
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at com.openpie.SocketSourceFunction.run(SocketSourceFunction.java:67)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:114)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:71)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:338)
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at com.openpie.SocketSourceFunction.run(SocketSourceFunction.java:67)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:114)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:71)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:338)
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at com.openpie.SocketSourceFunction.run(SocketSourceFunction.java:67)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:114)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:71)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:338)
`

Flink version
flink 1.18.0

**Comment by loserwang1024** [comment]
@yanye666 , as @dyz1027543829 says, it seems not the problem of Flink cdc.  The port of your cdc source is 5432, while port of error message is 51042.

**Comment by loserwang1024** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
