### ISSUE TITLE
[Bug] Not possible to not choose a deserializer

### ISSUE THREAD

**Issue by karlam123** [ververica/flink-cdc-connectors#2555]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.1

### Database and its version

Mysql

### Minimal reproduce step

Just follow this example: https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html#datastream-source but don't specify a deserializer

### What did you expect to see?

A datastream of type SourceRecord

### What did you see instead?

One gets the following error
`org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: null
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:105)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:851)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:245)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1095)
        at org.apache.flink.client.cli.CliFrontend.lambda$mainInternal$9(CliFrontend.java:1189)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1898)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.mainInternal(CliFrontend.java:1189)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1157)
Caused by: java.lang.NullPointerException
        at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:59)
        at com.ververica.cdc.connectors.mysql.source.MySqlSourceBuilder.build(MySqlSourceBuilder.java:261)
        at com.af.dl.flink_test.Main$.main(Main.scala:136)
        at com.af.dl.flink_test.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
`

It seems to be caused by this check: https://github.com/ververica/flink-cdc-connectors/blob/release-2.4.1/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceBuilder.java#L261

### Anything else?

Not really sure if this is considered a bug... Our use case is that we want to use a single sink to read from many different tables with different schemas. If it were possible to have a sink of `SourceRecord`, it would be easier to create Side Outputs for the respective table.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by karlam123** [comment]
Will close this one, found a solution through this link: https://sap1ens.com/blog/2022/07/10/flink-cdc-for-postgres-lessons-learned/. The author there created a "passthrough" seriarlizer like this
```scala
class RawDebeziumDeserializationSchema extends DebeziumDeserializationSchema[SourceRecord] {
  override def deserialize(record: SourceRecord, out: Collector[SourceRecord]): Unit = {
    out.collect(record)
  }

  override def getProducedType: TypeInformation[SourceRecord] = {
    createTypeInformation[SourceRecord]
  }
}
```
that just worked!
