### ISSUE TITLE
io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Failed to start Oracle LogMiner session, retrying-->io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource :.java.sql.SQLException: ORA-01291: missing log file[Bug] 

### ISSUE THREAD

**Issue by jasonhewg** [ververica/flink-cdc-connectors#2615]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

<flink-connector-oracle-cdc.version>2.4.1</flink-connector-oracle-cdc.version>

### Database and its version

oracle19c

### Minimal reproduce step

2023-11-03 13:37:44.675 WARN [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator] io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Failed to start Oracle LogMiner session, retrying...
2023-11-03 13:37:45.286 ERROR[debezium-oracleconnector-oracle_logminer-change-event-source-coordinator] io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource : Failed to start Oracle LogMiner after '5' attempts.

java.sql.SQLException: ORA-01291: missing log file
ORA-06512: at "SYS.DBMS_LOGMNR", line 72
ORA-06512: at line 1

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[com.oracle.database.jdbc-ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[com.oracle.database.jdbc-ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]  

In addition, I clean the archive logs by executing commands from the rman tool command:
------------------------------------------------------------
Crosscheck archivelog all;
Delete noprompt archivelog until time 'sysdate -1';
------------------------------------------------------------

Through the above command, the archived logs were retained for one day. During the insertion, deletion, and modification of the table within one day, I also encountered the issue of losing the logs mentioned above.

May I ask how to solve this problem。

### What did you expect to see?

flink cdc normal run

### What did you see instead?

java.sql.SQLException: ORA-01291: missing log file
ORA-06512: at "SYS.DBMS_LOGMNR", line 72
ORA-06512: at line 1

 io.debezium.connector.common.BaseSourceTask : Going to restart connector after 10 sec. after a retriable exception
2023-11-03 16:09:11.458 INFO [pool-18-thread-1] io.debezium.jdbc.JdbcConnection : Connection gracefully closed
2023-11-03 16:09:11.459 INFO [debezium-engine] io.debezium.embedded.EmbeddedEngine : Retrieable exception thrown, connector will be restarted
org.apache.kafka.connect.errors.RetriableException: An exception occurred in the change event producer. This connector will be restarted.
        at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:46) ~[debezium-core-1.9.7.Final.jar!/:1.9.7.Final]

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Naros** [comment]
Hi @jasonhewg, there have been several changes to the Debezium Oracle connector since 1.9.7.Final, which includes several critical bugs around log management that could cause this error.

I would suggest (if its possible) to move to Debezium 2.4.1.Final or 2.5.0.Alpha2 as a baseline for Oracle to get all the fixes that should address common issues around ORA-01291.

**Comment by jasonhewg** [comment]
> Hi @jasonhewg, there have been several changes to the Debezium Oracle connector since 1.9.7.Final, which includes several critical bugs around log management that could cause this error.
> 
> I would suggest (if its possible) to move to Debezium 2.4.1.Final or 2.5.0.Alpha2 as a baseline for Oracle to get all the fixes that should address common issues around ORA-01291.

so:
Do you want to upgrade Flink cdc connectors. com. verica. 2.4.1 debezium. version 1.9.7. Final to 2.4.1. Final? Which version is the corresponding flink-cdc-connectors.com.ververica

**Comment by Naros** [comment]
We are planning to cut a 2.4.2.Final next week as the last build in the Debezium 2.4 release stream -- once we do that I'll look at upgrading them here.

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

**Comment by jasonhewg** [comment]
> Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

execute me，how to resolved?
