### ISSUE TITLE
使用SPECIFIC_OFFSETS指定位点启动报错，org.apache.kafka.connect.errors.ConnectException: The binlog event does not contain expected number of columns

### ISSUE THREAD

**Issue by lufzhangzitao** [ververica/flink-cdc-connectors#265]
org.apache.kafka.connect.errors.ConnectException: The binlog event does not contain expected number of columns; the internal schema representation is probably out of sync with the real database schema, or the binlog contains events recorded with binlog_row_image other than FULL or the table in question is an NDB table
        at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:607) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1104) [blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:955) [blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) [blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) [blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.apache.kafka.connect.errors.ConnectException: The binlog event does not contain expected number of columns; the internal schema representation is probably out of sync with the real database schema, or the binlog contains events recorded with binlog_row_image other than FULL or the table in question is an NDB table
        at io.debezium.connector.mysql.RecordMakers$1.validateColumnCount(RecordMakers.java:362) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.RecordMakers$1.insert(RecordMakers.java:248) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.RecordMakers$RecordsForTable.create(RecordMakers.java:480) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.BinlogReader.handleInsert(BinlogReader.java:941) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]
        at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:590) ~[blob_p-3e79fe64ccd7ae5485ba6d4f414c02dba7d9a03b-24b5b62492e6cb4bb94a72a41eee6d91:?]

**Comment by leonardBang** [comment]
please pay attention to use this option in  production：

One is that the table structure corresponding to the earliest binlog offset may be inconsistent with the current table structure, and errors will occur at this time.

In addition, the DBA in production will configure the binlog cleanup time (TTL), and the pulled binlog is incomplete in this case
