### ISSUE TITLE
[Build] Bump Flink version to 1.18.0

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2670]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Flink community has released its 1.18.0 version, let's bump our flink version to the latest stable version.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
I'm willing to take this task.

**Comment by gtk96** [comment]
@Jiabao-Sun @leonardBang https://github.com/ververica/flink-cdc-connectors/pull/2463 Some developers have already mentioned pr

**Comment by maver1ck** [comment]
I'm on this, but I think we are missing flink-connector-jdbc version 1.18 to proceed.
https://github.com/apache/flink-connector-jdbc/pull/76

**Comment by Jiabao-Sun** [comment]
> I'm on this in #2463, but I think we are missing flink-connector-jdbc version 1.18 to proceed. [apache/flink-connector-jdbc#76](https://github.com/apache/flink-connector-jdbc/pull/76)

The e2e case was blocked by flink-connector-jdbc, 1.18 version has no release yet.
Shall we waiting for that release or ignore the 1.18 e2e test cases?
WDYT @leonardBang .

**Comment by leonardBang** [comment]
> The e2e case was blocked by flink-connector-jdbc, 1.18 version has no release yet.
> Shall we waiting for that release or ignore the 1.18 e2e test cases?
> WDYT @leonardBang .

Could we try flink-connector-jdbc  1.17 version in our e2e tests? if it's ok, I tend to support Flink 1.18 firstly and then bump the flink-connector-jdbc version after its 1.18 released. Because this is only a test dependency, it should not be the blocker for bumping flink version.

**Comment by maver1ck** [comment]
@leonardBang I tried it. Without success.
https://github.com/ververica/flink-cdc-connectors/pull/2463/files#diff-b91356c8ba49353da58e90503636aac862f6f6fc17c2c19d8801bddc4099d2c5R35

**Comment by maver1ck** [comment]
@Jiabao-Sun 
You need to have this part. It's creating jdbc-connector_1.18.0.jar
https://github.com/ververica/flink-cdc-connectors/pull/2463/files#diff-b91356c8ba49353da58e90503636aac862f6f6fc17c2c19d8801bddc4099d2c5R278

**Comment by Jiabao-Sun** [comment]
Could not initialize class org.apache.flink.connector.jdbc.utils.JdbcTypeUtil
```
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: java.lang.NoClassDefFoundError: Could not initialize class org.apache.flink.connector.jdbc.utils.JdbcTypeUtil
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.wrapIntoNullableExternalConverter(AbstractJdbcRowConverter.java:197) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.createNullableExternalConverter(AbstractJdbcRowConverter.java:192) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.<init>(AbstractJdbcRowConverter.java:69) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.internal.converter.MySQLRowConverter.<init>(MySQLRowConverter.java:38) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.dialect.mysql.MySqlDialect.getRowConverter(MySqlDialect.java:56) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createSimpleRowExecutor(JdbcOutputFormatBuilder.java:211) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.lambda$createUpsertRowExecutor$3(JdbcOutputFormatBuilder.java:190) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at java.util.Optional.map(Unknown Source) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createUpsertRowExecutor(JdbcOutputFormatBuilder.java:190) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createBufferReduceExecutor(JdbcOutputFormatBuilder.java:152) ~[?:?]
119847 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.lambda$build$d2919689$1(JdbcOutputFormatBuilder.java:104) ~[?:?]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.createAndOpenStatementExecutor(JdbcOutputFormat.java:170) ~[?:?]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:144) ~[?:?]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction.open(GenericJdbcSinkFunction.java:52) ~[?:?]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:101) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.table.runtime.operators.sink.SinkOperator.open(SinkOperator.java:58) ~[flink-table-runtime-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:753) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:728) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:693) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:922) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) ~[flink-dist-1.18.0.jar:1.18.0]
119848 [docker-java-stream--650170431] INFO  com.ververica.cdc.connectors.tests.utils.FlinkContainerTestEnvironment - STDOUT: 	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

I checked the 1.17 jdbc-connector, which seems to lack the dependency of guava30.
![image](https://github.com/ververica/flink-cdc-connectors/assets/27403841/18a9ba76-b316-400c-9065-d04eef70f923)

**Comment by maver1ck** [comment]
Funny. This was removed: 
https://github.com/apache/flink-connector-jdbc/pull/40/files

**Comment by Jiabao-Sun** [comment]
> Funny. This was removed: https://github.com/apache/flink-connector-jdbc/pull/40/files But in version 3.1.1. I bumped jdbc connector to this version in integration tests

Cool~

**Comment by maver1ck** [comment]
All checks have passed :)

**Comment by scampb3ll** [comment]
Hi, 
I'm using flink-connector-mongodb-cdc. Could you guys provide an estimate on when you will release with the guava update so that it's usable? Currently it's completely unusable for me unless you have a workaround. We have already moved to Flink 18...
