### ISSUE TITLE
I use OracleCdc to read partition table from oracle11,error occurs，but it`s OK when read non partition table

### ISSUE THREAD

**Issue by YunhChen** [ververica/flink-cdc-connectors#2704]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17

### Flink CDC version

2.42

### Database and its version

oracle11

### Minimal reproduce step

oracle11
flink1.7
cdc 2.42
it `s OK to read non partition data,but bug occurs when read partition table.

### What did you expect to see?

能够正确读取分区表

### What did you see instead?

Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:59) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.validateAndLoadDatabaseHistory(OracleSourceFetchTaskContext.java:282) ~[flink-sql-connector-oracle-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.configure(OracleSourceFetchTaskContext.java:116) ~[flink-sql-connector-oracle-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.submitTask(IncrementalSourceStreamFetcher.java:84) ~[flink-sql-connector-oracle-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:138) ~[flink-sql-connector-oracle-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:70) ~[flink-sql-connector-oracle-cdc-2.4.2.jar:2.4.2]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162) ~[flink-connector-files-1.17.1.jar:1.17.1]

### Anything else?

public static void main(String[] args) throws Exception {
        Properties debeziumProperties = new Properties();
        debeziumProperties.setProperty("log.mining.strategy", "online_catalog");

        JdbcIncrementalSource<String> oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname("172.17.0.2")
                        .schemaList("flinkuser")
                        .tableList("flinkuser.TABLE_PARTITION")
                        .databaseList("helowin")
                        .port(1521)
                        .username("flinkuser")
                        .password("flinkpw")
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(true) // output the schema changes as well
                        .startupOptions(StartupOptions.initial())
                        .debeziumProperties(debeziumProperties)
                        .splitSize(2)
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        // enable checkpoint
        env.enableCheckpointing(3000L);
        // set the source parallelism to 4
        env.fromSource(
                        oracleChangeEventSource,
                        WatermarkStrategy.noWatermarks(),
                        "OracleParallelSource")
                .setParallelism(1)
                .print()
                .setParallelism(1);
        env.execute("Print Oracle Snapshot + RedoLog");

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by itpe** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by ChenYunHey** [comment]
> 我也遇到了这个问题，请问解决了吗

他自身的问题，可以通过源码修复

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1737.
