### ISSUE TITLE
[Bug] oracle 增量同步一段时间后内部从LogMiner中获取更改的循环报NULL指针异常

### ISSUE THREAD

**Issue by tttzzzwww** [ververica/flink-cdc-connectors#2715]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.16.2

### Flink CDC version

cdc 2.4

### Database and its version

oracle 19

### Minimal reproduce step

提交代码
EXECUTE CDCSOURCE SUCCEZ_TEST.sqlplus-BZDIP.testOracle_1 WITH (
   'connector' = 'oracle-cdc',
   'hostname' = '192.168.10.205',
   'port' = '1521',
   'username' = 'succez_test',
   'password' = 'xxxxxx',
   'database-name' = 'orcl',
   'parallelism' = '2',
   'checkpoint' = '30',
   'scan.startup.mode' = 'initial',
   'table-name' = 'SUCCEZ_TEST\.TEST_TABLE',
   'debezium.database.history.store.only.captured.tables.ddl' = 'true',
   'debezium.database.tablename.case.insensitive' = 'false',
   'debezium.log.mining.strategy' = 'online_catalog',
   'debezium.decimal.handling.mode' = 'string',
   'debezium.connector.buffer.size' = '2048',
   'sink.table.prefix' = 'ODS_',
   'sink.table-name' ='BZDIP.${tableName}',
   'sink.connector' = 'jdbc',
   'sink.url' = 'jdbc:oracle:thin:@//192.168.10.25:1521/ws',
   'sink.username' = 'bzdip',
   'sink.password' = 'xxxxxx')

### What did you expect to see?

能过解决此问题

### What did you see instead?

oracle增量同步，运行一段时间后，就报了此错误

2023-11-17 15:10:17,763 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: Oracle CDC Source -> Map -> Process -> (Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map) (1/1) (d18d12b9f1b7edb7aa81ca0c6b1ef526_cbc357ccb763df2852fee8c4fc7d55f2_0_3) switched from RUNNING to FAILED on localhost:10657-22f939 @ localhost (dataPort=11178).
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[flink-sql-connector-mysql-cdc-2.4-

SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:261) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:70) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:141) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.NullPointerException

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tttzzzwww** [comment]
原本异常内部被优化了，需要增加JVM启动参数后才能将实际的异常输出，看着是row为空导致的null异常。
`java.lang.NullPointerException: null
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processRow(AbstractLogMinerEventProcessor.java:278) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processResults(AbstractLogMinerEventProcessor.java:262) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.process(AbstractLogMinerEventProcessor.java:198) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:247) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:70) ~[flink-sql-connector-oracle-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:141) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109) ~[flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
