### ISSUE TITLE
flink cdc 的应用程序，能在非flink集群中运行吗？

### ISSUE THREAD

**Issue by sandyustc** [ververica/flink-cdc-connectors#2726]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.3.0

### Database and its version

oracle  core 11.2.0.4.0 

### Minimal reproduce step

1. 把cdc 监控oracle 日志数据应用程序打包部署在其他集群中运行，出现cdc服务停止，现象如下

 **Caused by: java.sql.SQLException: 无效的列类型**

[INFO] 2023-11-21 17:52:51.219 org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Shut down cluster because application is in CANCELED, diagnostics DispatcherResourceManagerComponent has been closed..

        ... 5 more

Caused by: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.taskexecutor.DefaultJobLeaderService - Stop job leader service.

        at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.entrypoint.component.DispatcherResourceManagerComponent - Closing components.

        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:243)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.state.TaskExecutorLocalStateStoresManager - Shutting down TaskExecutorLocalStateStoresManager.

        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:63)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.dispatcher.runner.SessionDispatcherLeaderProcess - Stopping SessionDispatcherLeaderProcess.

        at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:160)

        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:122)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.resourcemanager.ResourceManagerServiceImpl - Stopping resource manager service.

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.dispatcher.StandaloneDispatcher - Stopping dispatcher akka://flink/user/rpc/dispatcher_25.

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.dispatcher.StandaloneDispatcher - Stopping all currently running jobs of dispatcher akka://flink/user/rpc/dispatcher_25.

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.resourcemanager.slotmanager.DeclarativeSlotManager - Closing the slot manager.

        at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 2023-11-21 17:52:51.220 org.apache.flink.runtime.resourcemanager.slotmanager.DeclarativeSlotManager - Suspending the slot manager.

### Caused by: java.sql.SQLException: 无效的列类型

        at oracle.jdbc.driver.Redirector$2.redirect(Redirector.java:261)

        at oracle.jdbc.driver.Representation.getObject(Representation.java:423)

        at oracle.jdbc.driver.Accessor.getObject(Accessor.java:986)

        at oracle.jdbc.driver.OracleStatement.getObject(OracleStatement.java:6521)

        at oracle.jdbc.driver.InsensitiveScrollableResultSet.getObject(InsensitiveScrollableResultSet.java:909)

        at io.debezium.connector.oracle.logminer.LogMinerHelper.lambda$getSystime$0(LogMinerHelper.java:207)

        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:649)

        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:517)

        at io.debezium.connector.oracle.logminer.LogMinerHelper.getSystime(LogMinerHelper.java:205)

        at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:156)

​

### What did you expect to see?

期望flink cdc 正常运行

### What did you see instead?

no error

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by loserwang1024** [comment]
Please use English, and I don't know what you mean whether Flink cdc Application use in non-Flink cluster? Flink CDC 2.4.2 is just a connector, which should be load by Flink cluster. When parse SQL also need Flink SQL.

**Comment by basketballboy** [comment]
Is the problem solved I have the same issue with Flink CDC 2.4.2 that I use

**Comment by GOODBOY008** [comment]
@sandyustc As [loserwang1024](https://github.com/loserwang1024) said flink cdc just a connector ,it should run on flink.

Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
