### ISSUE TITLE
mysql做snapshot时,checkpoint容易超时Checkpoint 17 of job 9ee5f488e87f39d44f7cd9e6da6ff1cd expired before completing.

### ISSUE THREAD

**Issue by zmr518** [ververica/flink-cdc-connectors#273]
mysql做数据全量snapshot时，这时触发checkpoint就会失败，checkpoint时间间隔5min，超时时间3min
```
2021-07-26 17:01:57,627 INFO  [74] org.apache.flink.runtime.checkpoint.CheckpointCoordinator    - Triggering checkpoint 17 (type=CHECKPOINT) @ 1627290117546 for job 9ee5f488e87f39d44f7cd9e6da6ff1cd.
2021-07-26 17:04:57,627 INFO  [74] org.apache.flink.runtime.checkpoint.CheckpointCoordinator    - Checkpoint 17 of job 9ee5f488e87f39d44f7cd9e6da6ff1cd expired before completing.
2021-07-26 17:04:57,629 INFO  [69] org.apache.flink.runtime.jobmaster.JobMaster                 - Trying to recover from a global failure.
org.apache.flink.util.FlinkRuntimeException: Exceeded checkpoint tolerable failure threshold.
	at org.apache.flink.runtime.checkpoint.CheckpointFailureManager.handleJobLevelCheckpointException(SourceFile:66) ~[flink-dist_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.a(SourceFile:1673) ~[flink-dist_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.a(SourceFile:1650) ~[flink-dist_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.access$600(SourceFile:91) ~[flink-dist_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator$CheckpointCanceller.run(SourceFile:1783) ~[flink-dist_2.11-1.11.2.jar:1.11.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
```

**Comment by zmr518** [comment]
可以通过设置这两个参数规避
execution.checkpointing.interval: 5min   # checkpoint间隔时间
execution.checkpointing.tolerable-failed-checkpoints: 100  # checkpoint 失败容忍次数
