### ISSUE TITLE
java.lang.AbstractMethodError: Method com/yzf/kuducdc/cdc/util/MyJSONKeyValueDeserializationSchema.deserialize(Lorg/apache/flink/kafka/shaded/org/apache/kafka/clients/consumer/ConsumerRecord;)Ljava/lang/Object; is abstract

### ISSUE THREAD

**Issue by forrestlmj** [ververica/flink-cdc-connectors#285]
你好，我自定义了

MyJSONKeyValueDeserializationSchema方法，与JSONKeyValueDeserializationSchema一样，不过做了try catch处理：
`    @Override
    public ObjectNode deserialize(ConsumerRecord<byte[], byte[]> record) {
        if (mapper == null) {
            mapper = new ObjectMapper();
        }
        ObjectNode node = mapper.createObjectNode();
        if (record.key() != null) {
            try {
                node.set("key", mapper.readValue(record.key(), JsonNode.class));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        if (record.value() != null) {
            try {
                node.set("value", mapper.readValue(record.value(), JsonNode.class));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        if (includeMetadata) {
            node.putObject("metadata")
                    .put("offset", record.offset())
                    .put("topic", record.topic())
                    .put("partition", record.partition());
        }
        return node;
    }`

但是提交的时候报了这个错误：

2021-08-04 12:04:53
java.lang.AbstractMethodError: Method com/yzf/kuducdc/cdc/util/MyJSONKeyValueDeserializationSchema.deserialize(Lorg/apache/flink/kafka/shaded/org/apache/kafka/clients/consumer/ConsumerRecord;)Ljava/lang/Object; is abstract
	at com.yzf.kuducdc.cdc.util.MyJSONKeyValueDeserializationSchema.deserialize(MyJSONKeyValueDeserializationSchema.java)
	at org.apache.flink.streaming.connectors.kafka.KafkaDeserializationSchema.deserialize(KafkaDeserializationSchema.java:79)
	at org.apache.flink.streaming.connectors.kafka.internals.KafkaFetcher.partitionConsumerRecordsHandler(KafkaFetcher.java:179)
	at org.apache.flink.streaming.connectors.kafka.internals.KafkaFetcher.runFetchLoop(KafkaFetcher.java:142)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:826)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:263)

请问如何解决呢？
@wuchong

**Comment by forrestlmj** [comment]
这个问题是包冲突问题。

**Comment by ldwnt** [comment]
> 这个问题是包冲突问题。

你好，请问具体是什么问题，怎么解决的呢

**Comment by ChengkaiYang2022** [comment]
> 

你好，这个问题比较久，我尽量回忆下。应该是因为类加载器找不到我自定义的反序列化类，感觉可能是双亲委派相关，可以检查下flink中是的[classloader.resolve-order](https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/deployment/config/#classloader-resolve-order)是parent first 还是child first
