### ISSUE TITLE
PostgreSQL-cdc使用DataStream API启动报org.apache.kafka.connect.errors.ConnectException

### ISSUE THREAD

**Issue by langxf** [ververica/flink-cdc-connectors#290]
**根据flink官方教程给定方式初始化的项目：**
https://ci.apache.org/projects/flink/flink-docs-release-1.13/zh/docs/try-flink/datastream/
mvn archetype:generate \
    -DarchetypeGroupId=org.apache.flink \
    -DarchetypeArtifactId=flink-walkthrough-datastream-java \
    -DarchetypeVersion=1.13.0 \
    -DgroupId=frauddetection \
    -DartifactId=frauddetection \
    -Dversion=0.1 \
    -Dpackage=spendreport \
    -DinteractiveMode=false

将此项目中mysql-cdc 和 pg-cdc示例代码放到上方初始化的项目中，MySQL的Job可以正常运行，可以监控到binlog变化，但PostgreSQL的Job就会启动报错kafka连接错误：
14:22:07,949 ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    [] - Reporting error:
**org.apache.kafka.connect.errors.ConnectException**: Error configuring an instance of PostgresConnectorTask; check the logs for details
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:96) ~[flink-connector-postgres-cdc-1.4.0.jar:1.4.0]

请问：
1. Feature 中说 CDC connectors for DataStream API, users can consume changes on multiple databases and tables in a single job without Debezium and Kafka deployed. 说明cdc connector是不需要kafka的，但我这里为啥提示连接kafka错误？
2. 如果只是MySQL不需要Debezium and Kafka，PG必须kafka，那pg connector如何在代码中设置kafka连接？
谢谢宝贵时间解答。

**基于flink-cdc-connectors的源码**
![image](https://user-images.githubusercontent.com/13778377/128334643-c5304cb3-b5b5-4a6a-8875-110b79441ead.png)

**启动报错：**
2021-08-05 17:28:35
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:207)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:197)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:188)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:677)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:435)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.kafka.connect.errors.ConnectException: Error configuring an instance of PostgresConnectorTask; check the logs for details
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:96)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:758)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by langxf** [comment]
经过在本地搭建docker环境将 debezium/zookeeper , debezium/kafka 运行起来，并且将flink-cdc-connectors项目clone到本地，将flink-connector-postgres-cdc下的测试类PostgreSQLSourceTest跑通后。
将PostgreSQLCDCJob再次运行，还会报此问题。不过这次是在idea运行起来，看到日志更详细，发现第一个ERROR是：
[debezium-engine] ERROR io.debezium.connector.common.BaseSourceTask - The 'slot.name' value 'mspbots-flink-cdc' is invalid: Valid replication slot name must contain only digits, lowercase characters and underscores with length <= 63
![image](https://user-images.githubusercontent.com/13778377/128598180-0e5d0f9e-b12a-4b3f-9de9-3e90dc436019.png)

经过debug，发现原来是debezium对slot.name命名规则先限制，不能有中横线，否则就会报错，导致后续出现kafka连接错误。
![image](https://user-images.githubusercontent.com/13778377/128597939-6d9e71e5-cabe-4a29-8dce-1a90279190d9.png)
