### ISSUE TITLE
[Bug] starrocks  and doris  pipeline  connector   date format  bug

### ISSUE THREAD

**Issue by dickson-bit** [ververica/flink-cdc-connectors#2904]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

3.0.0

### Database and its version

starrocks    3.2.0

### Minimal reproduce step

sync  some tables  from mysql to  starrocks, which have  date  type  fields.

### What did you expect to see?

report the  error data,  continue  to  process the next  record.  

### What did you see instead?

i don't konw

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by guodeliang** [comment]
023-12-21 11:11:09,599 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - PostPartition -> Sink Writer: StarRocks Sink -> Sink Committer: StarRocks Sink (2/2)#0 (57480a1a94083a09b2fd3ddb06db45e4_0deb1b26a3d9eb3c8f0c11f7110b2903_1_0) switched from RUNNING to FAILED with failure cause:
java.lang.ArrayIndexOutOfBoundsException: 35
	at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453) ~[?:1.8.0_372]
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2393) ~[?:1.8.0_372]
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2308) ~[?:1.8.0_372]
	at java.util.Calendar.setTimeInMillis(Calendar.java:1804) ~[?:1.8.0_372]
	at java.util.Calendar.setTime(Calendar.java:1770) ~[?:1.8.0_372]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943) ~[?:1.8.0_372]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936) ~[?:1.8.0_372]
	at java.text.DateFormat.format(DateFormat.java:345) ~[?:1.8.0_372]
	at com.ververica.cdc.connectors.starrocks.sink.StarRocksUtils.lambda$createFieldGetter$60c5a152$9(StarRocksUtils.java:171) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.starrocks.sink.StarRocksUtils.lambda$createFieldGetter$21edff26$1(StarRocksUtils.java:204) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.starrocks.sink.EventRecordSerializationSchema.serializeRecord(EventRecordSerializationSchema.java:134) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.starrocks.sink.EventRecordSerializationSchema.applyDataChangeEvent(EventRecordSerializationSchema.java:116) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.starrocks.sink.EventRecordSerializationSchema.serialize(EventRecordSerializationSchema.java:78) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.starrocks.sink.EventRecordSerializationSchema.serialize(EventRecordSerializationSchema.java:45) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at com.starrocks.connector.flink.table.sink.v2.StarRocksWriter.write(StarRocksWriter.java:139) ~[flink-cdc-pipeline-connector-starrocks-3.0.0.jar:3.0.0]
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.processElement(SinkWriterOperator.java:161) ~[flink-dist-1.18.0.jar:1.18.0]

**Comment by guodeliang** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/2010095/5dc0f407-d314-4fec-af39-ec1e48c0f0f0)

**Comment by guodeliang** [comment]
https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksUtils.java#L115

**Comment by guodeliang** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/2010095/9c08d15b-827e-435a-ba48-131c990a0997)
I can't  understand,  DATETIME_FORMATTER  and  DATE_FORMATER， which used  two  format  class。

**Comment by guodeliang** [comment]
haha, doris has the same case.

**Comment by lvyanquan** [comment]
Thanks for your feedback. We would like to fix this issue. Can you provide the table creation SQL in MySQL to reproduce the bug？

**Comment by dickson-bit** [comment]
> Thanks for your feedback. We would like to fix this issue. Can you provide the table creation SQL in MySQL to reproduce the bug？

  CREATE TABLE `video_basic_info` (
  `name` varchar(255) NOT NULL DEFAULT '',
  `channelType` varchar(20) NOT NULL DEFAULT '',
  `releaseTime` date DEFAULT NULL,
  `offLineTime` date DEFAULT NULL,
  `oldFlag` tinyint(2) DEFAULT NULL,
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `editedFlag` tinyint(2) DEFAULT '1',
  `area` varchar(255) DEFAULT NULL,
  `editedField` text,
  `atlas` bit(1) DEFAULT b'0',
  `isVertical` tinyint(2) DEFAULT '0',
  `bcType` tinyint(2) DEFAULT NULL,
  `releasetime_yuanxian` date DEFAULT NULL,
  `sharePlatform` varchar(255) DEFAULT NULL,
  `isExclusive` tinyint(2) DEFAULT '0',
  `isEdition` tinyint(2) DEFAULT '2',
  `producedPlatform` varchar(100) DEFAULT NULL,
  `dayPlatform_start` varchar(100) DEFAULT NULL,
  `dayPlatform_all` varchar(100) DEFAULT NULL,
  `isMemberFree` varchar(10) DEFAULT '0',
  `episodeUpdate` tinyint(4) DEFAULT '0',
  `amountEndDate` date DEFAULT NULL,
  `vipDownTime` date DEFAULT NULL,
  `clock` tinyint(2) DEFAULT NULL,
  `releaseTime_start` date DEFAULT NULL,
  PRIMARY KEY (`name`,`channelType`),
  KEY `index_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8616727 DEFAULT CHARSET=utf8

the  column amountEndDate  have    null, empty  values

**Comment by lvyanquan** [comment]
Fixed by https://github.com/ververica/flink-cdc-connectors/pull/2954.
