### ISSUE TITLE
[Bug] ORA-01292: no log file has been specified for the current LogMiner session

### ISSUE THREAD

**Issue by Toroidals** [ververica/flink-cdc-connectors#2917]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.2

### Database and its version

oracle（cdb）：12c

### Minimal reproduce step

prop.setProperty("log.mining.strategy", "redo_log_catalog");
prop.setProperty("log.mining.continuous.mine", "false");
prop.setProperty("log.mining.batch.size.min", "20000");
prop.setProperty("log.mining.batch.size.max", "2300000000");
prop.setProperty("log.mining.batch.size.default", "100000");
prop.setProperty("database.tablename.case.insensitive","false");
prop.setProperty("heartbeat.interval.ms", "600000");
prop.setProperty("heartbeat.action.query", "update c##fms_prdcdc.log_mining_update set current_time=current_timestamp where id=1");
prop.setProperty("scan.incremental.close-idle-reader.enabled", "true");
prop.setProperty("snapshot.locking.mode", "none");
prop.setProperty("lob.enabled", "true");
prop.setProperty("database.dbname", connectInfo.get("orc_cdb"));
prop.setProperty("database.pdb.name", connectInfo.get("orc_pdb"));

### What did you expect to see?

Oracle CDC is synchronizing data normally.

### What did you see instead?

Oracle CDC is synchronizing data normally.Caused by: oracle.jdbc.OracleDatabaseException: ORA-01292: no log file has been specified for the current LogMiner session
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.jdbc.JdbcConnection.executeWithoutCommitting(JdbcConnection.java:1446) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.startSession(LogMinerAdapter.java:304) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
                                                                                                                                                                        19095,2-9     99%
        at io.debezium.connector.oracle.OracleSnapshotChangeEventSource.determineSnapshotOffset(OracleSnapshotChangeEventSource.java:38) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:113) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        ... 5 more
Caused by: java.sql.SQLException: ORA-01292: no log file has been specified for the current LogMiner session
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.jdbc.JdbcConnection.executeWithoutCommitting(JdbcConnection.java:1446) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.startSession(LogMinerAdapter.java:304) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.getPendingTransactionsFromLogs(LogMinerAdapter.java:361) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.determineSnapshotOffset(LogMinerAdapter.java:263) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.determineSnapshotOffset(LogMinerAdapter.java:158) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
@@@     
                                                                                                                                                                        19068,2-9     99%
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.determineSnapshotOffset(LogMinerAdapter.java:263) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.determineSnapshotOffset(LogMinerAdapter.java:158) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.OracleSnapshotChangeEventSource.determineSnapshotOffset(OracleSnapshotChangeEventSource.java:143) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.OracleSnapshotChangeEventSource.determineSnapshotOffset(OracleSnapshotChangeEventSource.java:38) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:113) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        ... 5 more
Caused by: oracle.jdbc.OracleDatabaseException: ORA-01292: no log file has been specified for the current LogMiner session
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 1

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.jdbc.JdbcConnection.executeWithoutCommitting(JdbcConnection.java:1446) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]
        at io.debezium.connector.oracle.logminer.LogMinerAdapter.startSession(LogMinerAdapter.java:304) ~[hand_flink_cdc_connector_kafka_oracle-1.0-SNAPSHOT.jar:?]

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Closing this issue as it requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
