### ISSUE TITLE
[Bug] flink job failed to recover from savepoint with specified binlog offset

### ISSUE THREAD

**Issue by ldwnt** [ververica/flink-cdc-connectors#2923]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.5

### Flink CDC version

2.4 (built based on commit 823f5a1e in branch release-2.4, with dependency org.apache.flink:flink-shaded-guava changed to 18.0-13.0 to work with flink 1.13)

### Database and its version

mysql 8.0.21

### Minimal reproduce step

1. start flink job with flink cdc (startup mode set to specified offset), events are received as expected, binlog filename and position found in logs.
2. stop and restart the flink job, flink cdc keeps logging errors.

### What did you expect to see?

after step 2, the job restarted and resuming from the offset previously recorded in savepoint.

### What did you see instead?

 flink cdc keeps logging errors and subsequent events not received from mysql
```
2023-12-25 14:24:19,860 INFO  [blc-xxx:3306] io.debezium.connector.mysql.MySqlStreamingChangeEventSource [1225] - Connected to MySQL binlog at xxx:3306, starting at MySqlOffsetContext [sourceInfoSchema=Schema{name=io.debezium.connector.mysql.Source, type=STRUCT, optional=false}, sourceInfo=SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin.008246, currentBinlogPosition=386200773, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], snapshotCompleted=false, transactionContext=TransactionContext [currentTransactionId=null, perTableEventCount={}, totalEventCount=0], restartGtidSet=1b2fd828-7496-11ed-bef5-00163e1487f9:1-28723416,1c2f578a-f078-11ec-8c3f-00163e12783f:1-27,208cd7f3-f078-11ec-900a-00163e249966:1-1161135761,92a63284-9cf9-11eb-87d8-00163e147fb0:1-78665182,a64821b2-7c37-11ed-8e09-00163e1fb04f:1848986854-1849038038, currentGtidSet=1b2fd828-7496-11ed-bef5-00163e1487f9:1-28723416,1c2f578a-f078-11ec-8c3f-00163e12783f:1-27,208cd7f3-f078-11ec-900a-00163e249966:1-1161135761,92a63284-9cf9-11eb-87d8-00163e147fb0:1-78665182,a64821b2-7c37-11ed-8e09-00163e1fb04f:1848986854-1849038038, restartBinlogFilename=mysql-bin.008246, restartBinlogPosition=386200773, restartRowsToSkip=0, restartEventsToSkip=0, currentEventLengthInBytes=0, inTransaction=false, transactionId=null, incrementalSnapshotContext =IncrementalSnapshotContext [windowOpened=false, chunkEndPosition=null, dataCollectionsToSnapshot=[], lastEventKeySent=null, maximumKey=null]]
2023-12-25 14:24:19,860 INFO  [binlog-reader-0] io.debezium.connector.mysql.MySqlStreamingChangeEventSource [949] - Waiting for keepalive thread to start
2023-12-25 14:24:19,861 INFO  [blc-xxx:3306] io.debezium.util.Threads [287] - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2023-12-25 14:24:19,862 ERROR [blc-xxx:3306] io.debezium.connector.mysql.MySqlStreamingChangeEventSource [1094] - Error during binlog processing. Last offset stored = null, binlog reader near position = /4
2023-12-25 14:24:19,864 ERROR [blc-xxx:3306] io.debezium.pipeline.ErrorHandler [35] - Producer failure
io.debezium.DebeziumException: Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID sets and the missing purged transactions are too long to print in this message. For more information, please see the master's error log or the manual for GTID_SUBTRACT Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1194) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1239) [debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID sets and the missing purged transactions are too long to print in this message. For more information, please see the master's error log or the manual for GTID_SUBTRACT
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 3 more
2023-12-25 14:24:19,869 INFO  [blc-xxx:3306] io.debezium.connector.mysql.MySqlStreamingChangeEventSource [1213] - Stopped reading binlog after 0 events, no new offset was recorded
2023-12-25 14:24:20,321 ERROR [tcher for Source: @s -> @p -> (Sink: @ds, Sink: @ls) (1/1)#0] org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager [117] - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-connector-base-1.13.5.jar:1.13.5]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) [flink-connector-base-1.13.5.jar:1.13.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler.setProducerThrowable(MySqlErrorHandler.java:85) ~[flink-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1239) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 1 more
Caused by: io.debezium.DebeziumException: Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID sets and the missing purged transactions are too long to print in this message. For more information, please see the master's error log or the manual for GTID_SUBTRACT Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1194) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1239) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 1 more
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Cannot replicate because the master purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID sets and the missing purged transactions are too long to print in this message. For more information, please see the master's error log or the manual for GTID_SUBTRACT
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
	... 1 more
```

### Anything else?

the binlog file exists and I can start a job with specified file and pos in the error log, as long as the job is not resumed from savepoint/checkpoing.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ldwnt** [comment]
It seem that when the job recovers from savepoint, gtids are read from it, which lead to the exception.
I execute "show master status" on mysql, the gtid have tx range 1-1851177970, while the log reports 1848986854-1849038038.

**Comment by ldwnt** [comment]
I figure it out. I build jar flink-connector-debezium-2.4-SNAPSHOT.jar and flink-connector-mysql-cdc-2.4-SNAPSHOT.jar and use them on my yarn classpath. Commit debd6ef4 contains overwritten files against original copy from debezium. The fixes in the cdc jar do not take effect since the cdc jar is behind the debezium jar in classpath. The workaround is to rename the cdc jar something like _xxx to make it ahead of the debezium jar.
