### ISSUE TITLE
[Bug] 同步mariadb报gtid位置错误

### ISSUE THREAD

**Issue by yanghuabang** [ververica/flink-cdc-connectors#2929]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

3.0

### Database and its version

mariadb 10.6.7

### Minimal reproduce step

mariadb做集群，节点A为主库，节点B为从库，主从同步方式为gtid，主键为UUID。
change master to 
       master_host = '192.168.1.50', 
       master_port = 3306, 
       master_user = 'copy', 
       master_password = '123456', 
       master_use_gtid=slave_pos;
主从之间的同步是正常的。

通过flink-doris-connector 1.5 从节点B同步多表到doris(https://doris.apache.org/zh-CN/docs/ecosystem/flink-doris-connector#mysql%E5%90%8C%E6%AD%A5%E7%A4%BA%E4%BE%8B)，初始化数据没问题，初始化完成后一段时间内同步也没有问题，但是一段时间后会出现以下报错
Caused by: io.debezium.DebeziumException: Failed to replace GTID event with backwards-compatible event: corrupt event.; the first event 'mariadb-bin.000138' at 35634798, the last event read from 'mariadb-bin.000138' at 36296335, the last byte read from 'mariadb-bin.000138' at 36296420. Error code: 1236; SQLSTATE: HY000.
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1488) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1544) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
目前搜索不到这个报错产生的原因，mariadb默认是开启了gtid，不知道还需要开启哪些配置

### What did you expect to see?

无

### What did you see instead?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yanghuabang** [comment]
SHOW BINLOG EVENTS IN 'mariadb-bin.000005' FROM 11351369  LIMIT 2
SHOW BINLOG EVENTS IN 'mariadb-bin.000005' FROM 23603144  LIMIT 2
SHOW BINLOG EVENTS IN 'mariadb-bin.000005' FROM 23603229  LIMIT 2

查询了出错时候的日志，发现最大的可能是日志的server_id不一样，因为我有两个主库互为主从，两个库都会写入数据，导致gtid编码为0-200-xxx和0-201-xxx，单一主库写入应该不会碰到我这个问题。

**Comment by yanghuabang** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/19543391/3558ee99-f963-4cca-94f5-547e738fd48a)

**Comment by yanghuabang** [comment]
我尝试忽略另一个个主库写入的binlog，然后碰到了XA_prepare的问题，也就是XA事务是没法忽略的，一样无法解析
![image](https://github.com/ververica/flink-cdc-connectors/assets/19543391/69b39299-a21a-48ee-8ac3-20c6b22e6892)

**Comment by yanghuabang** [comment]
去掉XA事务后同步就没问题了
