### ISSUE TITLE
[Bug] sqlservercdc throws DataException: "file is not a valid field name" when  schema is changed

### ISSUE THREAD

**Issue by edmond-kk** [ververica/flink-cdc-connectors#2942]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18.0

### Flink CDC version

3.0-SNAPSHOT

### Database and its version

sqlerver 2016

### Minimal reproduce step

1.change the table schema like:
`ALTER TABLE CRDB.dbo.testTable ADD Column2 varchar(100) NULL;`
2.create new cdc_instance
`
EXEC sys.sp_cdc_enable_table
     @source_schema = N'dbo',
     @source_name   = N'testTable',
     @role_name     = NULL,
     @capture_instance = N'dbo_testTable2'
`

### What did you expect to see?

Caused by: org.apache.kafka.connect.errors.DataException: file is not a valid field name
	at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254)
	at org.apache.kafka.connect.data.Struct.getCheckType(Struct.java:261)
	at org.apache.kafka.connect.data.Struct.getString(Struct.java:158)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeRecordValue(JdbcSourceEventDispatcher.java:193)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(JdbcSourceEventDispatcher.java:223)
	at io.debezium.connector.sqlserver.SqlServerSchemaChangeEventEmitter.emitSchemaChangeEvent(SqlServerSchemaChangeEventEmitter.java:47)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:147)
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:62)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.migrateTable(SqlServerStreamingChangeEventSource.java:491)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:233)
	... 10 more

### What did you see instead?

No exception is thrown，retrieve changed data from the new cdc_instance

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by edmond-kk** [comment]
Looks like it's being fixed  https://github.com/ververica/flink-cdc-connectors/pull/2315
