### ISSUE TITLE
[Bug] The assigner is not ready to offer finished split information, this should not be called

### ISSUE THREAD

**Issue by which520** [ververica/flink-cdc-connectors#2948]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.4.2

### Database and its version

mysql5.7

### Minimal reproduce step

使用cdc同步过程中，同步一段时间后，然后使用添加新的表，从保存点的位置恢复会报错，去掉新加的表后又能从保存点正常恢复：

### What did you expect to see?

能够正常的从保存点恢复，然后添加新的表

### What did you see instead?

org.apache.flink.util.FlinkRuntimeException: The assigner is not ready to offer finished split information, this should not be called
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getFinishedSplitInfos(MySqlSnapshotSplitAssigner.java:355) ~[blob_p-b0743893e0f56b7652b123057d70a4fdab65bf0a-8411938ca8b733928f6654b45cc4003d:?]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getFinishedSplitInfos(MySqlHybridSplitAssigner.java:139) ~[blob_p-b0743893e0f56b7652b123057d70a4fdab65bf0a-8411938ca8b733928f6654b45cc4003d:?]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.sendBinlogMeta(MySqlSourceEnumerator.java:251) ~[blob_p-b0743893e0f56b7652b123057d70a4fdab65bf0a-8411938ca8b733928f6654b45cc4003d:?]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSourceEvent(MySqlSourceEnumerator.java:145) ~[blob_p-b0743893e0f56b7652b123057d70a4fdab65bf0a-8411938ca8b733928f6654b45cc4003d:?]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by which520** [comment]
<img width="1288" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/44831650/b4b6870d-8224-43c9-aea9-227e2bcdb9b4">

**Comment by ruanhang1993** [comment]
Please make sure that the `scan.newly-added-table.enabled` has been opened. 

If the problem still exists, please raise an issue in Apache Flink jira and mark it as a Flink CDC Component. Thanks.
