### ISSUE TITLE
【Flink1.17.1 cdc2.4.2 】Caused by: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by xuanzhi201111** [ververica/flink-cdc-connectors#2970]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.71.1

### Flink CDC version

2.3-3.0

### Database and its version

mysql 8.0.28

### Minimal reproduce step

flink1.17.1运行pyflink脚本，使用flink cdc2.2.1，不间断启动任务，一直没有问题；但一样的数据库，一样的脚本，就是单纯更换了一下cdc的版本，启动第一个job永远没有问题，启动第二个，或者第三个就开始卡住了，然后最终报以下错误，拿报错的job脚本放在第一个启动它又没有问题的，这里完全排除网络问题，因为同一个flink服务器，只是更换了cdc版本，在2.3、2.4、2.4.2 、3.0都会报这个，2.2.1完全正常。
2023-12-27 17:03:48,531 WARN  com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory [] - Get connection failed, retry times 2
2023-12-27 17:03:48,537 WARN  com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory [] - Get connection failed, retry times 2
2023-12-27 17:04:18,531 ERROR com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory [] - Get connection failed after retry 3 times
2023-12-27 17:04:18,531 ERROR com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils    [] - Failed to open MySQL connection
org.apache.flink.util.FlinkRuntimeException: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:72) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:888) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:883) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:411) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:68) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.open(MySqlChunkSplitter.java:112) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.open(MySqlSnapshotSplitAssigner.java:181) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.open(MySqlHybridSplitAssigner.java:93) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.start(MySqlSourceEnumerator.java:92) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$1(SourceCoordinator.java:234) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:458) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40) [flink-dist-1.17.1.jar:1.17.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:59) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        ... 18 more
2023-12-27 17:04:18,532 ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Uncaught exception in the SplitEnumerator for Source Source: oms_order_detail[10] while starting the SplitEnumerator.. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: org.apache.flink.util.FlinkRuntimeException: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:71) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.open(MySqlChunkSplitter.java:112) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.open(MySqlSnapshotSplitAssigner.java:181) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.open(MySqlHybridSplitAssigner.java:93) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.start(MySqlSourceEnumerator.java:92) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$1(SourceCoordinator.java:234) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:458) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40) [flink-dist-1.17.1.jar:1.17.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: org.apache.flink.util.FlinkRuntimeException: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:72) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:888) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:883) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:411) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:68) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        ... 14 more
Caused by: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:59) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:888) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:883) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:411) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:68) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        ... 14 more
2023-12-27 17:04:18,532 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Source Source: oms_order_detail[10] registering reader for parallel task 0 (#1) @ localhost
2023-12-27 17:04:18,532 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Source Source: oms_order_detail[10] received split request from parallel task 0 (#1)
2023-12-27 17:04:18,533 INFO  org.apache.flink.runtime.jobmaster.JobMaster                 [] - Trying to recover from a global failure.
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: oms_order_detail[10] -> DropUpdateBefore[11] -> ConstraintEnforcer[12] -> Sink: crm_oms_order_detail[12]' (operator 2963852293169ba90d9d1e7d6308db5c).
        at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:600) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:237) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.failJob(SourceCoordinatorContext.java:374) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:472) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40) ~[flink-dist-1.17.1.jar:1.17.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
Caused by: org.apache.flink.util.FlinkRuntimeException: org.apache.flink.util.FlinkRuntimeException: java.sql.SQLTransientConnectionException: connection-pool-mysql-prod-read-private.aaaa.net:3306 - Connection is not available, request timed out after 30000ms.
        at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:71) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.open(MySqlChunkSplitter.java:112) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.open(MySqlSnapshotSplitAssigner.java:181) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.open(MySqlHybridSplitAssigner.java:93) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.start(MySqlSourceEnumerator.java:92) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$1(SourceCoordinator.java:234) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:458) ~[flink-dist-1.17.1.jar:1.17.1]

Cased by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6bd43365 rejected from java.util.concurrent ScheduledThreadPoolExecutor@9a6b4c7[Terminated, pool size= 0,active threads = 0 ,queued tasks = 0 ,completed tasks = 0]

### What did you expect to see?

无

### What did you see instead?

我

### Anything else?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 Flink 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
