### ISSUE TITLE
[Bug] ORACLE CDC 3.0 not support oracle table add columns or delete columns

### ISSUE THREAD

**Issue by ChenYunHey** [ververica/flink-cdc-connectors#2990]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.7.1

### Flink CDC version

oracle cdc 3.0.0

### Database and its version

oracle11g

### Minimal reproduce step

1,start cdc job
public static void main(String[] args) throws Exception {
        Properties debeziumProperties = new Properties();
        debeziumProperties.setProperty("log.mining.strategy", "online_catalog");

        JdbcIncrementalSource<String> oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname("localhost")
                        .port(1521)
                        .databaseList("HELOWIN")
                        .schemaList("FLINKUSER")
                        .tableList("FLINKUSER.T1")
                        .username("FLINKUSER")
                        .password("flinkpw")
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(true) // output the schema changes as well
                        .startupOptions(StartupOptions.initial())
                        .debeziumProperties(debeziumProperties)
                        .splitSize(2)
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        // enable checkpoint
        env.enableCheckpointing(3000L);
        // set the source parallelism to 4
        env.fromSource(
                        oracleChangeEventSource,
                        WatermarkStrategy.noWatermarks(),
                        "OracleParallelSource")
                .setParallelism(4)
                .print()
                .setParallelism(1);
        env.execute("Print Oracle Snapshot + RedoLog");

2 in my oracle table,i excute : ALTER TABLE T1 DROP COLUMN COL2;

### What did you expect to see?

data is captured correctly

### What did you see instead?

2024-01-11 14:50:06 WARN  IncrementalSourceReader:199 - The stream split StreamSplit{splitId='stream-split', offset={commit_scn=1758952:1:07000b004b030000, transaction_id=null, snapshot_scn=null, scn=1758934}, endOffset={commit_scn=0, lcr_position=null, scn=-9223372036854775808}} has table schemas yet, skip the table schema discovery
2024-01-11 14:50:06 ERROR LogMinerHelper:117 - Mining session stopped due to the com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name
2024-01-11 14:50:06 ERROR ErrorHandler:35 - Producer failure
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.getCheckType(Struct.java:261) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.getString(Struct.java:158) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeRecordValue(JdbcSourceEventDispatcher.java:193) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(JdbcSourceEventDispatcher.java:223) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.OracleSchemaChangeEventEmitter.emitSchemaChangeEvent(OracleSchemaChangeEventEmitter.java:122) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:147) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:62) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.handleSchemaChange(AbstractLogMinerEventProcessor.java:649) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.memory.MemoryLogMinerEventProcessor.handleSchemaChange(MemoryLogMinerEventProcessor.java:215) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processRow(AbstractLogMinerEventProcessor.java:307) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processResults(AbstractLogMinerEventProcessor.java:262) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.process(AbstractLogMinerEventProcessor.java:198) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:247) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask$RedoLogSplitReadTask.execute(OracleStreamFetchTask.java:133) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask.execute(OracleStreamFetchTask.java:71) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:89) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392-392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392-392]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392-392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392-392]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392-392]
2024-01-11 14:50:07 ERROR SplitFetcherManager:129 - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165) ~[flink-connector-files-1.17.1.jar:1.17.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:114) [flink-connector-files-1.17.1.jar:1.17.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392-392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392-392]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392-392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392-392]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392-392]
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:261) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask$RedoLogSplitReadTask.execute(OracleStreamFetchTask.java:133) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask.execute(OracleStreamFetchTask.java:71) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:89) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	... 5 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.getCheckType(Struct.java:261) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.getString(Struct.java:158) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeRecordValue(JdbcSourceEventDispatcher.java:193) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(JdbcSourceEventDispatcher.java:223) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.OracleSchemaChangeEventEmitter.emitSchemaChangeEvent(OracleSchemaChangeEventEmitter.java:122) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:147) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.relational.JdbcSourceEventDispatcher.dispatchSchemaChangeEvent(JdbcSourceEventDispatcher.java:62) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.handleSchemaChange(AbstractLogMinerEventProcessor.java:649) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.memory.MemoryLogMinerEventProcessor.handleSchemaChange(MemoryLogMinerEventProcessor.java:215) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processRow(AbstractLogMinerEventProcessor.java:307) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.processResults(AbstractLogMinerEventProcessor.java:262) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.processor.AbstractLogMinerEventProcessor.process(AbstractLogMinerEventProcessor.java:198) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:247) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask$RedoLogSplitReadTask.execute(OracleStreamFetchTask.java:133) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleStreamFetchTask.execute(OracleStreamFetchTask.java:71) ~[flink-sql-connector-oracle-cdc-3.0.0.jar:3.0.0]
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:89) ~[flink-sql-connector-postgres-cdc-3.0.0.jar:3.0.0]

### Anything else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xuzhigong** [comment]
I had a similar problem, Instead of adding or removing columns, it occurs in the incremental process:
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name.
my flink sql is:
CREATE TABLE IF NOT EXISTS REPORT_EXEC_LOG (
    `op_ts` TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
    `ID_` DECIMAL(20,0)
    ,`REPORT_ID_` DECIMAL(20,0) 
    ,`OPERATOR_ID_` STRING 
    ,`DURATION_TIME_` BIGINT 
    ,`OPERATION_PARAMS_` STRING 
    ,`OPERATION_SQL_` STRING 
    ,`OPERATION_TYPE_` STRING 
    ,`OPERATION_BEGIN_` TIMESTAMP 
    ,`OPERATION_END_` TIMESTAMP 
    ,`REMARK_` STRING 
    ,`APP_ID_` STRING 
    ,`TRACE_` STRING 
    ,`RESULT_COUNT_` BIGINT 
    ,`SUCCESS_FLAG_` INT 
    ,`ERROR_MSG_` STRING 
    ,`LOG_TYPE_` STRING 
    ,PRIMARY KEY ( `ID_` ) NOT ENFORCED
) COMMENT ''
 WITH (
    'connector' = 'oracle-cdc',
    'table-name' = 'TEST_REPORT_EXEC_LOG',
    'hostname' = 'xxx',
    'port' = '1521',
    'username' = 'flinkcdc',
    'password' = 'flinkcdc',
    'database-name' = 'orcl',
    'schema-name' = 'LOWCODE_OPT',
    'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true'
);

select * from REPORT_EXEC_LOG ;

**Comment by ChenYunHey** [comment]
the oracle cdc need  fix the problem

**Comment by ccczhouxin** [comment]
I has same problem,hope can fix it

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1792

**Comment by q2515045** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/25814461/e36c9278-b6bc-4f70-9fa1-0263d7a0bf3a)
The issue arises because the schema change-related code logic within flink cdc base is designed to utilize MySQL binlog version-specific information, which includes keywords such as 'file' and 'pos'. However, these keywords do not exist in the table structure change data of other databases, hence the error is thrown. Additionally, upon examining the table change data from an Oracle database, it was found that it does not contain actual table structure change details.

schema source info:
Struct{version=1.9.7.Final,connector=oracle,name=oracle_logminer,ts_ms=1707322384000,db=JYDB,schema=PRICE_FACTORY,table=SYS_PRICE_AKA0_FINAL,txId=0500080092d40d00,scn=10040901314308,commit_scn=10040901314308,ssn=0,redo_thread=1}
