### ISSUE TITLE
[Bug] 空指针报错

### ISSUE THREAD

**Issue by zhong2312** [ververica/flink-cdc-connectors#2996]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.4

### Flink CDC version

3.0.0

### Database and its version

8

### Minimal reproduce step

按照官网文档操作：https://ververica.github.io/flink-cdc-connectors/release-3.0/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html

### What did you expect to see?

成功执行

### What did you see instead?

空指针

### Anything else?

按照官网文档操作：https://ververica.github.io/flink-cdc-connectors/release-3.0/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html

如果使用3.0.0版本则报(flink1.18、1.15.4,1.17.2都是报这个错)：
java.lang.NullPointerException: null
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createReader(MySqlSource.java:185) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
	at org.apache.flink.streaming.api.operators.SourceOperator.initReader(SourceOperator.java:286) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask.init(SourceOperatorStreamTask.java:94) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:669) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:646) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:917) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563) ~[flink-dist-1.15.4.jar:1.15.4]

如果使用2.4.2版本+flink1.15.4则报
org.apache.flink.util.FlinkRuntimeException: Chunk splitting has encountered exception
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.checkSplitterErrors(MySqlSnapshotSplitAssigner.java:583) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:341) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:123) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:218) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$2(SourceCoordinator.java:230) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$9(SourceCoordinator.java:406) ~[flink-dist-1.15.4.jar:1.15.4]
	at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40) [flink-dist-1.15.4.jar:1.15.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_392]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.IllegalStateException: Error when splitting chunks for mydb.orders
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitTable(MySqlSnapshotSplitAssigner.java:307) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitChunksForRemainingTables(MySqlSnapshotSplitAssigner.java:566) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_392]
	... 3 more
Caused by: java.lang.RuntimeException: Fail to analyze table in chunk splitter.
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.analyzeTable(MySqlChunkSplitter.java:158) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.splitChunks(MySqlChunkSplitter.java:119) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitTable(MySqlSnapshotSplitAssigner.java:305) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitChunksForRemainingTables(MySqlSnapshotSplitAssigner.java:566) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_392]
	... 3 more
Caused by: java.lang.NullPointerException
	at com.ververica.cdc.connectors.mysql.source.utils.ChunkUtils.findChunkKeyColumn(ChunkUtils.java:97) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.utils.ChunkUtils.getChunkKeyColumn(ChunkUtils.java:65) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.analyzeTable(MySqlChunkSplitter.java:152) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.splitChunks(MySqlChunkSplitter.java:119) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitTable(MySqlSnapshotSplitAssigner.java:305) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitChunksForRemainingTables(MySqlSnapshotSplitAssigner.java:566) ~[flink-sql-connector-mysql-cdc-2.4.2.jar:2.4.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_392]

如果使用flink1.17.2+2.4.2则正常执行。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。

**Comment by jiangjin-f** [comment]
any news about this?
