### ISSUE TITLE
[Bug] flink-cdc-3.0 Unable to apply SchemaChangeEvent for table "xxx" without existing schema

### ISSUE THREAD

**Issue by yuyii** [ververica/flink-cdc-connectors#3014]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

3.0

### Database and its version

source: mysql 5.7.40
sink: starrocks 3.2.2

### Minimal reproduce step

1.  create yaml
source:
table: app_db.ord\.*
...
2. sync table begin with ord to starrocks ,everything is ok
3. change source mysql table ,alter table app_db.ttt add column .... (not capture this table)
4. schema change is be send to starrocks, then error occured.

some log:
2024-01-19 17:53:14,206 INFO  com.ververica.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler [] - Received schema change event request from table app_db.ttt. Start to buffer requests for others.
...
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to apply SchemaChangeEvent for table "app_db.ttt" without existing schema
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[?:?]
	at com.ververica.cdc.runtime.operators.schema.SchemaOperator.sendRequestToCoordinator(SchemaOperator.java:123) ~[?:?]

### What did you expect to see?

should not capture table ttt 

### What did you see instead?

ttt table schema change is send to starrocks

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by everhopingandwaiting** [comment]
I have the same issue

**Comment by lvyanquan** [comment]
fixed by https://github.com/ververica/flink-cdc-connectors/pull/2986.
