### ISSUE TITLE
[Bug] msyql-cdc 2.2.1 is not compatible 2.2.0 savepoint data

### ISSUE THREAD

**Issue by litZz** [ververica/flink-cdc-connectors#3048]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13

### Flink CDC version

2.2.1 & 2.2.0

### Database and its version

mysql 5.7.35

### Minimal reproduce step

1. run mysql-cdc 2.2.0
2. stop with savepoint
3. run mysql-cdc 2.2.1 from savepoint generated by step 2

### What did you expect to see?

mysql-cdc running

### What did you see instead?

Caused by: java.io.EOFException
	at org.apache.flink.core.memory.DataInputDeserializer.readBoolean(DataInputDeserializer.java:125)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserializeSplit(MySqlSplitSerializer.java:165)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:124)
	at com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer.deserialize(MySqlSplitSerializer.java:48)
	at org.apache.flink.core.io.SimpleVersionedSerialization.readVersionAndDeSerialize(SimpleVersionedSerialization.java:165)
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState$DeserializingIterator.next(SimpleVersionedListState.java:138)
	... 10 more

### Anything else?

1. 2.2.0 MySqlSplitSerializer version is 4 and don't serialize binlogSplit.isSuspended(),
2. 2.2.1 MySqlSplitSerializer version is 4 and deserialize binlogSplit.isSuspended() which versoin > 3

see: https://github.com/ververica/flink-cdc-connectors/pull/996

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Hi, version 2.2.x may not be maintained. Please raise another issue for version 2.4.x or 3.x. Thanks.
