### ISSUE TITLE
ClassNotFoundException: org.apache.flink.table.api.ValidationException

### ISSUE THREAD

**Issue by niyanchun** [ververica/flink-cdc-connectors#325]
I ran example here: https://ververica.github.io/flink-cdc-connectors/master/content/about.html#usage-for-datastream-api  in IDEA , but get following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/table/api/ValidationException
	at com.ververica.cdc.connectors.mysql.MySqlSource$Builder.build(MySqlSource.java:230)
	at flinkcdc.MySqlBinlogSourceExample.main(MySqlBinlogSourceExample.java:23)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.ValidationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

Process finished with exit code 1
```

did I miss some dependencies ? thanks in advance.

**Comment by niyanchun** [comment]
problem resolved after add following dependency:

```
<dependency>
    <groupId>org.apache.flink</groupId>
    <artifactId>flink-table-common</artifactId>
    <version>1.13.0</version>
</dependency>
```
