### ISSUE TITLE
mysql-cdc从checkpoint恢复时因为binlog日志文件已清除导致任务无限重启

### ISSUE THREAD

**Issue by liaooo** [ververica/flink-cdc-connectors#442]
异常信息：
`io.debezium.DebeziumException: The connector is trying to read binlog starting at SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin.003008, currentBinlogPosition=169375401, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
	at io.debezium.connector.mysql.MySqlConnectorTask.validateSnapshotFeasibility(MySqlConnectorTask.java:329)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:98)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

在任务重启时，因为mysql-bin.003008日志文件已经被清理了，导致任务一直重试，但是这种情况会永远都重试不能成功。
有什么好的方式处理这种场景呢？

**Comment by leonardBang** [comment]
mysql 侧 binlog文件日期保留长点

**Comment by a120610114** [comment]
> mysql 侧 binlog文件日期保留长点

flink cdc 是否支持when_needed的快照模式？如果使用该模式是否能解决binlog 被清理的问题

**Comment by niunan2019** [comment]
> mysql 侧 binlog文件日期保留长点

保留长了还是会出现这个问题，chk一直不前进

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by MyWillMyHands** [comment]
flink cdc Support for the snapshot mode of when_needed? If you use this mode to solve the problem of binlog being cleaned up
