### ISSUE TITLE
[MYSQL] Caused by: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hwzp99** [ververica/flink-cdc-connectors#460]
**Describe the bug**
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:199)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:681)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:636)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:647)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:146)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1189)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:958)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)
	... 1 more
Caused by: io.debezium.DebeziumException
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1142)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:65)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:262)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:241)
	at java.io.InputStream.skip(InputStream.java:224)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:280)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:305)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945)
	... 3 more

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.0.1
 - Database and version: sql7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by leonardBang** [comment]
could you try 2.0.2 version? @hwzp99

**Comment by hwzp99** [comment]
> could you try 2.0.2 version? @hwzp99

2.0.2，the same problem..  @leonardBang 
2021-09-24 13:39:45,947 ERROR io.debezium.pipeline.ErrorHandler                            [] - Producer failure
io.debezium.DebeziumException: null
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1142) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1189) [darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:958) [darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) [darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) [darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:65) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:262) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:241) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_202]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:280) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:305) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945) ~[darwinKafkaDataToHive-1.0-SNAPSHOT.jar:?]
	... 3 more

**Comment by zhangsir1993** [comment]
Has anyone solved the problem？

**Comment by wjcwin** [comment]
same problem

**Comment by hnjincan** [comment]
mysql-cdc 2.1.0 also exist this bug，my env is flink-1.13.2，mysql-cdc 2.1.0 ，mysql-version 5.7

**Comment by zhengjiasen** [comment]
flink 1.13.3,  mysql-cdc 2.0.2, 10.1.18-MariaDB also exis this bug.  flink on yarn

**Comment by hwzp99** [comment]
@leonardBang could you fix it?🙏

**Comment by QwenStorm** [comment]
mysql-cdc 2.1.0 also exist this bug.
my env is flink-1.13.1，mysql-cdc 2.1.0 ，mysql-version 5.7.2
Looking forward to your repair @leonardBang

**Comment by mincwang** [comment]
@leonardBang we also have this problems， could you have time to fix it  @leonardBang

**Comment by mincwang** [comment]
It looks like this  https://issues.redhat.com/browse/DBZ-3848?jql=text%20~%20%22ArrayIndexOutOfBoundsException%22

**Comment by fsk119** [comment]
If it's the network problem, I think we should do something like retry in connectors rather than throw the exception to trigger failover. What do you think, @leonardBang ?

**Comment by ai-smalleryu** [comment]
有解决方法了吗？又碰到了

**Comment by leonardBang** [comment]
> 有解决方法了吗？又碰到了

可以提供一个稳定复现的case吗？或者你那边能稳定复现吗？我高优看下

**Comment by ai-smalleryu** [comment]
> 
这样子说mysqlsource-cdc-flink逻辑处理-mysql 问题出现在cdc对接前期正常，中间不再有任何数据写入，时间超过八小时无数据写入，在突然大量数据下入到mysqlsource，数据前期少量正常，然后就开始了这个报错，错误完全一样

**Comment by ai-smalleryu** [comment]
> > 有解决方法了吗？又触发了
> 
> 可以提供一个稳定的复现吗？或者你的情况可以稳定复现吗？
mysqlsource-cdc-flink 逻辑中间-mysql 这个问题在cdc-flink之间有任何正常问题，不再有时间写入，超过八小时无写入，在突然有大量数据输入到source，数据少量同步正常，然后就开始了这个报错，错误完全一样

**Comment by ai-smalleryu** [comment]
> > 有解决方法了吗？又碰到了
> 
> 可以提供一个稳定复现的case吗？或者你那边能稳定复现吗？我高优看下
>版本2.1.1

**Comment by ai-smalleryu** [comment]
> > 有解决方法了吗？又碰到了
> 
> 可以提供一个稳定复现的case吗？或者你那边能稳定复现吗？我高优看下
@leonardBang 暂时发现，mysqlsource中间停顿长时间，然后在突然写入数据让再次开始同步，出现这个bug的概率较高，如果是不停的流则不会出现，小数据量十几万也没有出现，大约在60W测试量时候出现了
