### ISSUE TITLE
what is meaning of the mysql cdc connector param 'scan.incremental.snapshot.enabled'

### ISSUE THREAD

**Issue by baisui1981** [ververica/flink-cdc-connectors#463]
when I start my fink cdc job base on mysql connector for monitor couple of mysql table . the code as below:

``` scala

val bsEnv = StreamExecutionEnvironment.getExecutionEnvironment
    bsEnv.enableCheckpointing(1000, CheckpointingMode.EXACTLY_ONCE)
    val backend = new HashMapStateBackend();
    bsEnv.setStateBackend(backend)
    val settings = EnvironmentSettings.newInstance().useBlinkPlanner().inStreamingMode().build()
    val tableEnv = StreamTableEnvironment.create(bsEnv, settings)
   
    // SQL query with a registered table
    // register a table named "Orders"
    tableEnv.executeSql(
      """
        | CREATE TABLE base (
        |          base_id int primary key,
        |          base_location varchar(20)
        | ) WITH (
        |         'connector' = 'mysql-cdc',
        |         'hostname' = '192.168.28.200',
        |         'port' = '3306',
        |         'username' = 'root',
        |         'password' = '123456',
        |         'database-name' = 'order2',
        |         'table-name' = 'base'
        |)
        |""".stripMargin);
    //'scan.incremental.snapshot.enabled' = 'false'
    
    tableEnv.executeSql(
      """
        |create table stuff(
        |    stuff_id int primary key,
        |    stuff_base_id int,
        |    stuff_name varchar(20)
        |) WITH (
        |    'connector' = 'mysql-cdc',
        |    'hostname' = '192.168.28.200',
        |    'port' = '3306',
        |    'username' = 'root',
        |    'password' = '123456',
        |    'database-name' = 'order2',
        |    'table-name' = 'stuff'
        |)
        |""".stripMargin);


    tableEnv.executeSql(
      """
        |create table wide_stuff(
        |    stuff_id int primary key,
        |    base_id int,
        |    base_location varchar(20),
        |    stuff_name varchar(20)
        |) WITH (
        |	   'connector'  = 'jdbc',
        |    'driver'     = 'com.mysql.cj.jdbc.Driver',
        |    'url'        = 'jdbc:mysql://192.168.28.200:3306/order2?rewriteBatchedStatements=true',
        |    'table-name' = 'wide_stuff',
        |    'username'   = 'root',
        |    'password'   = '123456'
        |)
        |""".stripMargin)


    val r = tableEnv.executeSql(
      """
        |insert into wide_stuff
        | select stuff.stuff_id, base.base_id, base.base_location, stuff.stuff_name
        | from stuff inner join base
        | on stuff.stuff_base_id = base.base_id
        |""".stripMargin)

    r.print();

    bsEnv.execute()

```
after launching , try some inserting recodes in source table, checking the sink table `wide_stuff` has find any changing in it.

then tracking the cdc source code, i find the param 'scan.incremental.snapshot.enabled' the default value is true, modify it to false, after relaunching the job,
repeat the process as before , checking the sink table , some new records has been synchronized that meet the expection.

then I check the param 'scan.incremental.snapshot.enabled' explaination as below:

``` java
    public static final ConfigOption<Boolean> SCAN_INCREMENTAL_SNAPSHOT_ENABLED =
            ConfigOptions.key("scan.incremental.snapshot.enabled")
                    .booleanType()
                    .defaultValue(true)
                    .withDescription(
                            "Incremental snapshot is a new mechanism to read snapshot of a table. "
                                    + "Compared to the old snapshot mechanism, the incremental snapshot has many advantages, including:\n"
                                    + "(1) source can be parallel during snapshot reading, \n"
                                    + "(2) source can perform checkpoints in the chunk granularity during snapshot reading, \n"
                                    + "(3) source doesn't need to acquire global read lock (FLUSH TABLES WITH READ LOCK) before snapshot reading.\n"
                                    + "If you would like the source run in parallel, each parallel reader should have an unique server id, "
                                    + "so the 'server-id' must be a range like '5400-6400', and the range must be larger than the parallelism.");
```
This confuses me even more，is there anyone can make further more detailed explaination. thanks

**Comment by leonardBang** [comment]
> after launching , try some inserting recodes in source table, checking the sink table wide_stuff has find any changing in it.
> then tracking the cdc source code, i find the param 'scan.incremental.snapshot.enabled' the default value is true, modify it > to false, after relaunching the job,

could you share the exception? and the INCREMENTAL_SNAPSHOT is a new mechanism to make the snapshot reading phase more effective which supports `non-lock` and `parallel reading`

**Comment by baisui1981** [comment]
when the param 'scan.incremental.snapshot.enabled' is true ,after launching , throw an exception as below. 

after  checkpoint be disbaled as below，the exception will not be display again, though the data synchronizing was unable to return normal  
``` scala
//    bsEnv.enableCheckpointing(1000, CheckpointingMode.EXACTLY_ONCE)
//    val backend = new HashMapStateBackend();
//    bsEnv.setStateBackend(backend)
```
``` shell
2021-09-26 10:15:31 INFO o.a.f.r.e.ExecutionGraph:1446- Source: TableSourceScan(table=[[default_catalog, default_database, base]], fields=[base_id, base_location]) (5/8) (761689a2975f494d0345bfa5a14777b3) switched from RUNNING to FAILED on db19bbfe-d876-4489-92ff-cd63a59d0b9c @ localhost (dataPort=-1).
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:199) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:681) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:636) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:647) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) ~[flink-runtime_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-runtime_2.11-1.13.1.jar:1.13.1]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:146) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:101) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	... 1 common frames omitted
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:47) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.validateAndLoadDatabaseHistory(StatefulTaskContext.java:173) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.configure(StatefulTaskContext.java:125) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.submitSplit(SnapshotSplitReader.java:91) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.submitSplit(SnapshotSplitReader.java:62) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.checkSplitOrStartNext(MySqlSplitReader.java:143) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:69) ~[flink-connector-mysql-cdc-2.0.0.jar:2.0.0]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56) ~[flink-connector-base-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:138) ~[flink-connector-base-1.13.1.jar:1.13.1]
	... 6 common frames omitted
2021-09-26 10:15:31 DEBUG i.d.c.base.ChangeEventQueue:235- no records available yet, sleeping a bit...
2021-09-26 10:15:31 DEBUG o.a.f.r.scheduler.SharedSlot:238- Remove logical slot (SlotRequestId{7ffe004372d9d749db5cce062d465473}) for execution vertex (id feca28aff5a3958840bee985ee7de4d3_4) from the physical slot (SlotRequestId{b092227179e305bc8fbf2f21e56d6ed4})
2021-09-26 10:15:31 INFO o.a.f.r.e.f.f.RestartPipelinedRegionFailoverStrategy:115- Calculating tasks to restart to recover the failed task feca28aff5a3958840bee985ee7de4d3_4.
2021-09-26 10:15:31 INFO o.a.f.r.s.c.SourceCoordinator:184- Removing registered reader after failure for subtask 4 of source Source: TableSourceScan(table=[[default_catalog, default_database, base]], fields=[base_id, base_location]).
2021-09-26 10:15:31 INFO o.a.f.r.e.f.f.RestartPipelinedRegionFailoverStrategy:152- 24 tasks should be restarted to recover the failed task feca28aff5a3958840bee985ee7de4d3_4. 
2021-09-26 10:15:31 INFO c.v.c.c.m.d.t.MySqlSnapshotSplitReadTask:134- Snapshot step 1 - Determining low watermark mysql-bin.000282:150 for split MySqlSnapshotSplit{tableId=order2.stuff, splitId='order2.stuff:0', splitKeyType=[`stuff_id` INT NOT NULL], splitStart=null, splitEnd=null, highWatermark=null}
2021-09-26 10:15:31 INFO o.a.f.r.e.ExecutionGraph:1039- Job insert-into_default_catalog.default_database.wide_stuff (a09637969df1f3662d331476814489a5) switched from state RUNNING to RESTARTING.
2021-09-26 10:15:31 INFO o.a.f.r.s.c.SourceCoordinator:184- Removing registered reader after failure for subtask 0 of source Source: TableSourceScan(table=[[default_catalog, default_database, stuff]], fields=[stuff_id, stuff_base_id, stuff_name]).
2021-09-26 10:15:31 DEBUG o.a.f.r.scheduler.SharedSlot:213- Cancel logical slot (SlotRequestId{5675303ae9c0e3cb7fad49a2368b226f}) for execution vertex (id bc764cd8ddf7a0cff126f51c16239658_0) from the physical slot (SlotRequestId{e739a62724da99fb9829bc7a48c9893f}) from bc764cd8ddf7a0cff126f51c16239658_0
2021-09-26 10:15:31 INFO o.a.f.r.e.ExecutionGraph:1438- Source: TableSourceScan(table=[[default_catalog, default_database, stuff]], fields=[stuff_id, stuff_base_id, stuff_name]) (1/8) (a564f91e696e6b8cfadf43c9b9e9b1bc) switched from RUNNING to CANCELING.
2021-09-26 10:15:31 INFO o.a.f.runtime.taskmanager.Task:1097- Attempting to cancel task Source: TableSourceScan(table=[[default_catalog, default_database, stuff]], fields=[stuff_id, stuff_base_id, stuff_name]) (1/8)#0 (a564f91e696e6b8cfadf43c9b9e9b1bc).
2021-09-26 10:15:31 INFO o.a.f.runtime.taskmanager.Task:1062- Source: TableSourceScan(table=[[default_catalog, default_database, stuff]], fields=[stuff_id, stuff_base_id, stuff_name]) (1/8)#0 (a564f91e696e6b8cfadf43c9b9e9b1bc) switched from RUNNING to CANCELING.
2021-09-26 10:15:31 INFO o.a.f.runtime.taskmanager.Task:1163- Triggering cancellation of task code Source: TableSourceScan(table=[[default_catalog, default_database, stuff]], fields=[stuff_id, stuff_base_id, stuff_name]) (1/8)#0 (a564f91e696e6b8cfadf43c9b9e9b1bc).
```

**Comment by leonardBang** [comment]
please try 2.0.2 version which has fixed this issue

**Comment by baisui1981** [comment]
> please try 2.0.2 version which has fixed this issue

thanks，let me try it
