### ISSUE TITLE
在使用MySQL CDC Connector创建表时不支持debezium.snapshot.mode配置怎么回事

### ISSUE THREAD

**Issue by YoungWildAnFree** [ververica/flink-cdc-connectors#49]
请问：在使用MySQL CDC Connector创建表时不支持debezium.snapshot.mode配置怎么回事？
是还需要配置其他什么吗

 String ddl = "CREATE TABLE datagen ( \n" +
                "  id INT\n" +
                ") WITH ( \n" +
                "  'connector' = 'mysql-cdc',\n" +
                "  'hostname' = '*****', \n" +
                "  'port' = '3306', \n" +
                "  'username' = '*****',\n" +
                "  'password' = '*****',\n" +
                "  'database-name' = '****',\n" +
                "  'debezium.snapshot.locking.mode' = 'schema_only',\n" +
                "  'table-name' = 'mysql_flink_source'\n" +
                ")";
        tEnv.executeSql(ddl);

异常信息：
Exception in thread "main" org.apache.flink.table.api.ValidationException: Unable to create a source for reading table 'default_catalog.default_database.datagen'.

Table options are:

'connector'='mysql-cdc'
'database-name'='******'
'debezium.snapshot.locking.mode'='schema_only'
'hostname'='******'
'password'='******'
'port'='3306'
'table-name'='mysql_flink_source'
'username'='******'
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:125)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.buildTableScan(CatalogSourceTable.scala:135)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.scala:78)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3492)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2415)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2102)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2051)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:661)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:642)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3345)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:568)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:164)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:151)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:774)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:746)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:236)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:525)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:202)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:78)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:684)
	at cn.sprucetec.realtime.driver.TestMysqlCDC.main(TestMysqlCDC.java:70)
Caused by: org.apache.flink.table.api.ValidationException: Unsupported options found for connector 'mysql-cdc'.

Unsupported options:

debezium.snapshot.locking.mode

Supported options:

connector
database-name
hostname
password
port
property-version
server-id
table-name
username
	at org.apache.flink.table.factories.FactoryUtil$TableFactoryHelper.validate(FactoryUtil.java:487)
	at com.alibaba.ververica.cdc.connectors.mysql.table.MySQLTableSourceFactory.createDynamicTableSource(MySQLTableSourceFactory.java:81)
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:122)
	... 20 more

**Comment by shizhengchao** [comment]
配置debezium，需要1.1.x版本以上。还有就是'debezium.snapshot.locking.mode', 是锁的配置 可以配置成 none 来禁用snapshot时锁表，你要的应该是'debezium.shapshot.mode' = 'schema_only'

**Comment by YoungWildAnFree** [comment]
> 配置debezium，需要1.1.x版本以上。还有就是'debezium.snapshot.locking.mode', 是锁的配置 可以配置成 none 来禁用snapshot时锁表，你要的应该是'debezium.shapshot.mode' = 'schema_only'

谢谢 确实是版本的问题
