### ISSUE TITLE
mysql-cdc读取数据后通过jdbc写入postgresql报错

### ISSUE THREAD

**Issue by zzy-data-coder** [ververica/flink-cdc-connectors#54]
报错如下：
```
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'jdbc' that implements 'org.apache.flink.table.factories.DynamicTableSourceFactory' in the classpath.
Available factory identifiers are:
datagen
mysql-cdc
postgres-cdc
```
MySQL建表如下：
```
create table test.dot(
id varchar(100),
dotno varchar(100),
orders int4,
channelname varchar(90) NULL,
etl_time timestamp NULL DEFAULT now(),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT 
CHARSET=utf8;
;
```
postgresql建表如下：
```
create table test.dot(
id varchar(100),
dotno varchar(100),
orders int4,
channelname varchar(90),
etl_time timestamp NULL DEFAULT now(),
PRIMARY KEY (id)
)
DISTRIBUTED BY (id);
```
flink建表如下：
```

create table dot_mysql(
id STRING,
dotno STRING,
orders int,
channelname STRING,
etl_time timestamp
)WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '******',
  'port' = '3307',
  'username' = '***',
  'password' = '******',
  'database-name' = 'test',
  'table-name' = 'dot'
);

create table dot(
id varchar(100),
dotno varchar(100),
orders int,
channelname varchar(90),
etl_time timestamp,
PRIMARY KEY(id) NOT ENFORCED
)
WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:postgresql://************/******',
    'driver' = 'org.postgresql.Driver',
    'username' = '*****',
    'password' = '*****',
    'table-name' = 'dot'
);
```
第一次接触flink sql，然后在flink sql查dot表的时候报上述错误，请问在哪里添加jdbc的驱动呢？我在flink_home/lib下放了postgresql的驱动jar也没有作用。求大佬指点迷津~

**Comment by shizhengchao** [comment]
这个错不是驱动问题，是flink的connector没找到，在pom文件中引入相关依赖即可:
```
<groupId>org.apache.flink</groupId>
<artifactId>flink-connector-jdbc_${scala.binary.version}</artifactId>
<version>1.11.1</version>
```
什么是flink connector，可以看官方文档: https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/connectors.

**Comment by zzy-data-coder** [comment]
> 这个错不是驱动问题，是flink的connector没找到，在pom文件中引入相关依赖即可:
> 
> ```
> <groupId>org.apache.flink</groupId>
> <artifactId>flink-connector-jdbc_${scala.binary.version}</artifactId>
> <version>1.11.1</version>
> ```
> 
> 什么是flink connector，可以看官方文档: https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/connectors.

谢谢您，我在flink_home/lib下放了flink-connector-jdbc_2.11-1.11.2的connector解决了问题。但是有了一个新问题，还望指教。
问题描述：
在MySQL同步数据到postgresql时，执行flink job时报的错，
我的flink sql 如下
`insert into dot(id,dotno,orders,channelname,etl_time) select id,dotno,orders,channelname,etl_time from dot_mysql;`
```
报错如下：
2020-11-11 10:33:46
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:503)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:386)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:284)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:199)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:152)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.checkFlushException(JdbcBatchingOutputFormat.java:142)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.writeRecord(JdbcBatchingOutputFormat.java:148)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:87)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:86)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
	at StreamExecCalc$249.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:305)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:394)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.emitRecords(DebeziumChangeConsumer.java:159)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.emitRecordsUnderCheckpointLock(DebeziumChangeConsumer.java:145)
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.handleBatch(DebeziumChangeConsumer.java:113)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:81)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:812)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.checkFlushException(JdbcBatchingOutputFormat.java:142)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.flush(JdbcBatchingOutputFormat.java:167)
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.lambda$open$0(JdbcBatchingOutputFormat.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	... 3 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
Caused by: java.lang.RuntimeException: Writing records to JDBC failed.
	... 10 more
```

**Comment by shizhengchao** [comment]
你可以调试下 JdbcBatchingOutputFormat的open方法，在open的时候就有异常了，然后writeRecord中，checkFlushException发现 flushException 不为null， 启动时把断点打到flush方法，看下是什么异常。

**Comment by leonardBang** [comment]
This should be related to sink
