### ISSUE TITLE
[CDC-Mysql] 2.1 not load server time zone

### ISSUE THREAD

**Issue by cm2d** [ververica/flink-cdc-connectors#544]
Hello

First of all, congratulations for the work accomplished.

I am currently testing version 2.1, and I may have a little suggestion.
It seems that the mysql cdc connector does not enable the time_zone server configuration.
I added this to the PooledDataSourceFactory.createPooledDataSource which seems to work fine.

```
        config.setPoolName(CONNECTION_POOL_PREFIX + hostName + ":" + port);
        config.setJdbcUrl(String.format(JDBC_URL_PATTERN, hostName, port));
        config.setUsername(sourceConfig.getUsername());
        config.setPassword(sourceConfig.getPassword());
        config.setMaximumPoolSize(sourceConfig.getConnectionPoolSize());
        config.setConnectionTimeout(sourceConfig.getConnectTimeout().toMillis());

      // this add
     if (sourceConfig.getServerTimeZone() != null
                && !"".equals(sourceConfig.getServerTimeZone())) {
            config.addDataSourceProperty("serverTimezone", sourceConfig.getServerTimeZone());
        }
```

Not familiar with this code, I simply prefer to suggest it to you rather than push it on the branch.

Wishing you a nice day.

**Environment :**
 - Flink version :  1.13
 - Flink CDC version:  2.1
 - Database and version: 10.5.12-MariaDB-1:10.5.12+maria~buster-log

**To Reproduce**
1. Thes test data :
2. The test code :
      ``` 
      MySqlSource mySqlSource = MySqlSource.builder()
	              .hostname("10.xxx.xxx.xxx")
	              .port(xxxx)
	              .serverTimeZone("Europe/Paris")
	              .databaseList(databaseList)
	              .tableList(tableList) 
                      .username("login")
	              .password("passs")
	              .deserializer(new JsonDebeziumDeserializationSchema())
	              .build();

3. The error :
Hikari The server time zone value 'CEST' is unrecognized

**Comment by leonardBang** [comment]
Thanks for your timely feedback @cm2d Could you also share your environment  and the detailed exception?

**Comment by cm2d** [comment]
Hello @leonardBang, 
Thanks for your msg.
Can you specify the elements you need regarding the environment?

Stack Error is : 
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-4.0.3.jar:?]
	at com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory.createPooledDataSource(PooledDataSourceFactory.java:58) ~[flink-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionPools.getOrCreateConnectionPool(JdbcConnectionPools.java:51) ~[flink-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:53) ~[flink-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
```

**Comment by leonardBang** [comment]
Hi, @cm2d I mean the OS your MariaDB deployed and the OS flink cluster you deployed.
I have encountered the time zone set on some machines before, and the database server cannot resolve it

**Comment by dliangzhu** [comment]
我也遇到了类似的问题，在windows本地跑的flink，windows上安装的mysql5.7。

`Caused by: java.sql.SQLException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-4.0.3.jar:?]
	at com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory.createPooledDataSource(PooledDataSourceFactory.java:61) ~[flink-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
`

**Comment by cm2d** [comment]
Hello, 

My Mariadb10.5.12 is deployed on Debian 10.10.
DB timezone is
```
SELECT @@time_zone;
  -> 'SYSTEM'
```
Debian timezone is
```
ls -l /etc/localtime
> 32 oct.   4 20:35 /etc/localtime -> /usr/share/zoneinfo/Europe/Paris
```  
I use Flink and flink-cdc-connectors wtih openjdk 11.0.8 code executed "in desktop mode" on Windows 10.
Maven POM ...
```
		<flink.version>1.13-SNAPSHOT</flink.version>
		<target.java.version>1.11</target.java.version>
		<scala.binary.version>2.12</scala.binary.version>
		.....
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-java</artifactId>
			<version>${flink.version}</version>
			<!-- <scope>provided</scope>   -->
		</dependency>
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-streaming-java_${scala.binary.version}</artifactId>
			<version>${flink.version}</version>
			<scope>compile</scope>
		</dependency>
		......
		<dependency>
			<groupId>com.ververica</groupId>
			<artifactId>flink-connector-mysql-cdc</artifactId>
			<version>2.1-SNAPSHOT</version>
		</dependency>		
```

@dliangzhu 
Thanks for your confirmation.

@leonardBang 
"I have encountered the time zone set on some machines before, and the database server cannot resolve it"
Indeed, it happens that the database cannot resolve the time zone of its server.
In this case, why not allow MysqlSource to use the timeZone of its parameters?

```
MySqlSource.builder()
            .hostname("10.xxx.xxx.xxx")
            .port(xxxx)
            .serverTimeZone("Europe/Paris")
```

and in PooledDataSourceFactory.createPooledDataSource 

```
if (sourceConfig.getServerTimeZone() != null
                && !"".equals(sourceConfig.getServerTimeZone())) {
            config.addDataSourceProperty("serverTimezone", sourceConfig.getServerTimeZone());
        }
```

**Comment by leonardBang** [comment]
@cm2d Thanks for your detail description.

> In this case, why not allow MysqlSource to use the timeZone of its parameters?

I just want to figure out what happens when this problem occurs, and then fix it. It seems the problem is clear now, would you like to open a PR to fix it?
