### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by asushiye** [ververica/flink-cdc-connectors#552]
[ERROR] Could not execute SQL statement. Reason:
java.lang.NumberFormatException: For input string: "Struct{scale=0,value=[B@223a3e17}

**Comment by leonardBang** [comment]
@asushiye Could you post more detail? E.g. your sql and the exception stack.

**Comment by asushiye** [comment]
Flink SQL> CREATE TABLE products (
>     ID INT,
>     NAME STRING,
>     DESCRIPTION STRING,
>     PRIMARY KEY (ID) NOT ENFORCED
>   ) WITH (
>     'connector' = 'oracle-cdc',
>     'hostname' = '10.10.*.175',
>     'port' = '1521',
>     'username' = 'ddd',
>     'password' = 'ddd',
>     'database-name' = 'AFD',
>     'schema-name' = 'ddd',  
>     'table-name' = 'products'
>   );
[INFO] Execute statement succeed.

Flink SQL> select * from products;
[ERROR] Could not execute SQL statement. Reason:
java.lang.NumberFormatException: For input string: "Struct{scale=0,value=[B@5061437f}"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema$5.convert(RowDataDebeziumDeserializeSchema.java:340)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema$17.convert(RowDataDebeziumDeserializeSchema.java:610)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.convertField(RowDataDebeziumDeserializeSchema.java:595)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.access$100(RowDataDebeziumDeserializeSchema.java:62)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema$16.convert(RowDataDebeziumDeserializeSchema.java:580)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema$17.convert(RowDataDebeziumDeserializeSchema.java:610)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.extractAfterRow(RowDataDebeziumDeserializeSchema.java:144)
        at com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.deserialize(RowDataDebeziumDeserializeSchema.java:119)
        at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:217)
        at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:151)
        at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:439)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269)

**Comment by asushiye** [comment]
create table products (
  id number not null  primary key,
  name varchar2(255) not null,
  description varchar2(512)
);

**Comment by luoyuxia** [comment]
@asushiye 
It seems when define  column `number` without specifing the precison and scale, debezium will return a Struct object.
But the  'convertToInt` method in `RowDataDebeziumDeserializeSchema` can't handle such object .

I think when you change the `number`  to  `number(10, 0)`, the oracle cdc will work again.
But anyway, I think the oracle cdc  connector should handle such situation instead of assuming user's well table definition  in Oracle.
WDYT, @leonardBang

**Comment by leonardBang** [comment]
Thanks @luoyuxia for the good analysis, If this number type only happens in oracle, I suggest use the `DeserializationRuntimeConverterFactory userDefinedConverterFactory` to support this case

**Comment by ashulin** [comment]
@leonardBang Yes, this currently only happens in oracle NUMBER type. 
In my test, this problem will happen when the oracle NUMBER type is mapped to any numeric type of flink. So should I modify the RowDataDebeziumDeserializeSchema or add an OracleDeserializationConverterFactory to handle this problem?

**Comment by asushiye** [comment]
My problem has been solved. Thank you very much

**Comment by Aer1208** [comment]
Please tell me how to solve this problem. I have encountered it too.

**Comment by ashulin** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/560
