### ISSUE TITLE
org.apache.kafka.connect.errors.DataException: `PrimaryKey` is not a valid field name

### ISSUE THREAD

**Issue by mincwang** [ververica/flink-cdc-connectors#573]
Describe the bug
Multiple table synchronization errors when using ParallelSource
Environment :

Flink version : flink 1.13.3
Flink CDC version: 2.1-snapshot (issues create time)
Database and version: 5.7
To Reproduce

Thes test data :
The test code : parallel=4 serverId=5001-5004
The error :
**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
```
2021-11-05 16:18:02,711 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: mysqlcdc-source -> Sink: kafka-sink (3/4) (866f70b41725880dd77b494cee433023) switched from RUNNING to FAILED on container_e08_1635325297403_14057_01_000005 @ 10.49.2.52 (dataPort=36657).
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:223) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]
Caused by: java.lang.RuntimeException: SplitFetcher thread 262 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: id is not a valid field name
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct.get(Struct.java:74) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.source.utils.RecordUtils.getSplitKey(RecordUtils.java:331) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.source.utils.RecordUtils.normalizedSplitRecords(RecordUtils.java:114) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.pollSplitRecords(SnapshotSplitReader.java:241) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:72) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:140) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
	... 1 more
```
**Additional Description**

**Comment by mincwang** [comment]
Simulation code logic about `com.ververica.cdc.connectors.mysql.source.utils.RecordUtils#getSplitKey`
```
    public static Object[] getSplitKey(
            RowType splitBoundaryType, SourceRecord dataRecord, SchemaNameAdjuster nameAdjuster) {
        // the split key field contains single field now
        String splitFieldName = nameAdjuster.adjust(splitBoundaryType.getFieldNames().get(0));
        Struct key = (Struct) dataRecord.key();
        return new Object[] {key.get(String splitFieldName)}; -- this should not string type
    }

```
![image](https://user-images.githubusercontent.com/33626973/140491973-262c3cbf-51a6-4515-823e-62d450eec9b6.png)

**Comment by mincwang** [comment]
@leonardBang Thanks for fixing this bug.
