### ISSUE TITLE
运行一段时间会报这个异常

### ISSUE THREAD

**Issue by liuxiaolinlxl** [ververica/flink-cdc-connectors#631]
[] - Source: TableSourceScan(table=[[default_catalog, default_database, tb_rhdc_zjdzdxx]], fields=[_id, deleted, cqydm, zdmj, sffz, zjdlyzk, create_date]) -> MiniBatchAssigner(interval=[5000ms], mode=[ProcTime]) (1/1) (579d0f87d1100701ef653a24156a2507) switched from RUNNING to FAILED on container_e67_1637028218711_0235_01_000012 @ i-siqi02.novalocal (dataPort=2143).
java.lang.NullPointerException: null
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:59) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorDeserializationSchema.deserialize(MongoDBConnectorDeserializationSchema.java:122) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:217) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:163) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:439) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269) ~[flink-dist_2.11-1.13.2.jar:1.13.2]

**Comment by Jiabao-Sun** [comment]
Thanks @liuxiaolinlxl to report this. It seems the change event missing `documentKey`.

As https://docs.mongodb.com/v4.0/reference/change-events/ says, data modify change events such as `insert`, `update`, `replace`, `delete` must have `documentKey` field. 

Change events such as `drop`, `rename`, `dropDatabase`, `invalidate` may not have `documentKey` field. 
Stopping the task is expected  when these events occur,  cause we will no longer be able to subscribe to changes.

**Comment by daun-gatal** [comment]
Hi guys (sorry if wrong mentions)
I got similar issue but for mysql cdc connector `2.1.1` and flink `1.13.5`
```
Caused by: java.lang.NullPointerException
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:59) ~[flink-dist_2.12-1.13.5-stream2.jar:1.13.5-stream2]
	at com.ververica.cdc.connectors.mysql.source.config.MySqlSourceConfig.<init>(MySqlSourceConfig.java:91) ~[?:?]
	at com.ververica.cdc.connectors.mysql.source.config.MySqlSourceConfigFactory.createConfig(MySqlSourceConfigFactory.java:287) ~[?:?]
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createEnumerator(MySqlSource.java:153) ~[?:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:128) ~[flink-dist_2.12-1.13.5-stream2.jar:1.13.5-stream2]
	... 40 more
```
Any idea what should I do for fixing this issue?. Thank you.

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
