### ISSUE TITLE
oracle jdbc url 连接不一致导致连接出错

### ISSUE THREAD

**Issue by kuibobo** [ververica/flink-cdc-connectors#632]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.1
 - Database and version: oracle 12c

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
com.ververica.cdc.connectors.oracle.OracleValidator.openConnection 这函数返回的是SID的jdbc url
return DriverManager.getConnection(
                "jdbc:oracle:thin:@" + hostname + ":" + port + ":" + dbname, userName, userpwd);

==============================================
io.debezium.connector.oracle.OracleConnection.connectionString
这个函数返回的是 jdbc:oracle:thin:@192.168.0.171:32769/ORCLCDB 服务名方式的jdbc url

===============================
我的测试ORACLE数据库
服务名ORCLCDB.localhost
SID:ORCLCDB

复现：
当我传入
'database-name' = 'ORCLCDB',
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
 
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:284) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_261]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_261]
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$0(JdbcConnection.java:179) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.jdbc.JdbcConnection$ConnectionFactoryDecorator.connect(JdbcConnection.java:116) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:872) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:867) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:638) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:512) ~[flink-sql-connector-mongodb-cdc-2.1.0.jar:2.1.0]
	at io.debezium.connector.oracle.OracleConnection.resolveOracleDatabaseVersion(OracleConnection.java:128) ~[flink-sql-connector-oracle-cdc-2.1.0.jar:2.1.0]

===================================================

而当我传入
'database-name' = 'ORCLCDB.localdomain',
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:854)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.ververica.cdc.connectors.oracle.OracleValidator.openConnection(OracleValidator.java:72)
	at com.ververica.cdc.connectors.oracle.OracleValidator.validate(OracleValidator.java:47)
	... 12 more

**Comment by paul8263** [comment]
Hi @kuibobo ,
Firstly you have to make sure that Oracle can be successfully connected using SID.
Then, to deal with ORA-12514, you can add the following configurations in listener.ora:
`
SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = ora11g)
      (ORACLE_HOME = /data/oracle/product/11.2.0/dbhome_1)
    )
  )
`
Replace SID_NAME and ORACLE_HOME with the correct ones in your environment. And restart the listener.

**Comment by rekichan** [comment]
Hello @kuibobo.
Recently I also met for this problem.You can try to add the 
**debeziumProperties(properties)** 
with the properties that include 
**properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");**
and config the OracleSource.builder object whose database property is set by your database name 
**OracleSource.builder.database(_sid_)**

**Comment by sty945** [comment]
> Hello @kuibobo. Recently I also met for this problem.You can try to add the **debeziumProperties(properties)** with the properties that include **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");** and config the OracleSource.builder object whose database property is set by your database name **OracleSource.builder.database(_sid_)**

Hello@rekichan ，Recently i missed the same errors when i use **flink-sql to submit the job**. 

**Have you ever encountered this problem？and how to solve the this problem?**

My Flink-sql is :

```
CREATE TABLE source_ORDERS(ORDER_ID INT,ORDER_DATE TIMESTAMP(0),CUSTOMER_NAME STRING,PRICE DECIMAL(10, 5),PRODUCT_ID INT,ORDER_STATUS BOOLEAN) WITH (
        'connector' = 'oracle-cdc',
        'hostname' = '192.168.110.220',
        'port' = '1521',
        'username' = 'flinkuser',
        'password' = 'flinkpw',
        'database-name' = 'ORCL',
        'schema-name' = 'flinkuser',  
        'table-name' = 'ORDERS',
   
        'debezium.log.mining.strategy' = 'online_catalog',
        'debezium.log.mining.continuous.mine' = 'true'
);

CREATE TABLE sink_ORDERS_kafka_101(ORDER_ID INT,ORDER_DATE TIMESTAMP(0),CUSTOMER_NAME STRING,PRICE DECIMAL(10, 5),PRODUCT_ID INT,ORDER_STATUS BOOLEAN) WITH (
        'connector' = 'kafka',
        'topic' = 'sink_ORDERS_kafka_101_topic',
        'properties.bootstrap.servers' = '192.168.122.139:9092',
        'format' = 'debezium-json'
        );

INSERT INTO sink_ORDERS_kafka_101 SELECT * FROM source_ORDERS;
```

In Flink web , i got this error:
```
org.apache.flink.table.api.TableException: Unexpected error while connecting to Oracle and validating

  at com.ververica.cdc.connectors.oracle.OracleValidator.validate(OracleValidator.java:60)

  at com.ververica.cdc.debezium.DebeziumSourceFunction.open(DebeziumSourceFunction.java:215)

  at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)

  at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)

  at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:442)

  at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:585)

  at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100)

  at org.apache.flink.streaming.runtime.tasks.StreamTask.executeRestore(StreamTask.java:565)

  at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650)

  at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:540)

  at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:759)

  at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)

  at java.lang.Thread.run(Thread.java:748)

Caused by: java.sql.SQLException: Listener refused the connection with the following error:

ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

 

  at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:854)

  at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)

  at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)

  at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)

  at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)

  at java.sql.DriverManager.getConnection(DriverManager.java:664)

  at java.sql.DriverManager.getConnection(DriverManager.java:247)

  at com.ververica.cdc.connectors.oracle.OracleValidator.openConnection(OracleValidator.java:72)

  at com.ververica.cdc.connectors.oracle.OracleValidator.validate(OracleValidator.java:47)

  ... 12 more

Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:

ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

 

  at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:284)

  at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)

  at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)

  at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)

  ... 20 more
```

My oracle is **Oracle 12C RAC**

If you can answer questions in your busy schedule, I will be very grateful.

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by 290352095** [comment]
> Hello @kuibobo. Recently I also met for this problem.You can try to add the **debeziumProperties(properties)** with the properties that include **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");** and config the OracleSource.builder object whose database property is set by your database name **OracleSource.builder.database(_sid_)**

非常感谢，根据您的建议，解决了servicename连接RAC的问题

**Comment by taotao8810** [comment]
在用flink-cdc得时候，这个问题该茹姐解决呢？
how to solve the problem when use the flink-cdc?

**Comment by tianboluo** [comment]
> > Hello @kuibobo. Recently I also met for this problem.You can try to add the **debeziumProperties(properties)** with the properties that include **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");** and config the OracleSource.builder object whose database property is set by your database name **OracleSource.builder.database(_sid_)**
> 
> 非常感谢，根据您的建议，解决了servicename连接RAC的问题

请问一下这个怎么解决呢，没看懂。。。

**Comment by xpdgit** [comment]
> 

请问一下怎么解决的？为什么我这还是报错

**Comment by xpdgit** [comment]
> Hello @kuibobo. Recently I also met for this problem.You can try to add the **debeziumProperties(properties)** with the properties that include **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");** and config the OracleSource.builder object whose database property is set by your database name **OracleSource.builder.database(_sid_)**

你好，请问一下怎么解决呢？为什么我这里还是报错？
![image](https://user-images.githubusercontent.com/47846745/185864490-bec7d217-dd32-4ee0-b424-af3302b005d9.png)

**Comment by chenfan331** [comment]
> 机=_主_

大佬，解决了吗，我也遇到这个问题不知道怎么解决

**Comment by chenfan331** [comment]
> > Hello @kuibobo. Recently I also met for this problem.You can try to add the **debeziumProperties(properties)** with the properties that include **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=_host_)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=_servicename_)))");** and config the OracleSource.builder object whose database property is set by your database name **OracleSource.builder.database(_sid_)**
> 
> 你好，请问一下怎么解决呢？为什么我这里还是报错？ ![image](https://user-images.githubusercontent.com/47846745/185864490-bec7d217-dd32-4ee0-b424-af3302b005d9.png)

大佬，解决了吗，我也遇到这个问题不知道怎么解决

**Comment by purechilde** [comment]
> 你好@kuibobo 最近我也遇到了这个问题。您可以尝试添加debeziumProperties **(properties)** ，其属性包括 **properties.put("database.url", "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=是） （故障转移=是）（地址=（协议= tcp）（主机=主机_）_（端口= 1521））（地址=（协议= tcp）（主机=_主机_）（端口= 1521）））（CONNECT_DATA =（ SERVICE_NAME） =_服务名称_)))");****并配置OracleSource.builder对象，其数据库属性由您的数据库名称OracleSource.builder.database( ****_sid_**** )** 设置 **__**

您好，请问可以详细描述一下操作吗？
