### ISSUE TITLE
flink1.11 cdc 连接mysql 开发环境正常，没有用debezium，但生产环境就报错找不到DebeziumSourceFunction

### ISSUE THREAD

**Issue by xiaoc10020015** [ververica/flink-cdc-connectors#66]
- 源码
```scala
package com.ydx.streaming

import com.tool.Conf
import org.apache.flink.streaming.api.scala._
import org.apache.flink.table.api._
import org.apache.flink.table.api.bridge.scala.StreamTableEnvironment
import org.apache.flink.types.Row
object Stat {
  def main(args: Array[String]): Unit = {
    val env = StreamExecutionEnvironment.getExecutionEnvironment
    val bsSettings = EnvironmentSettings.newInstance.useBlinkPlanner.inStreamingMode.build
    val sTableEnv = StreamTableEnvironment.create(env, bsSettings)
    val conf = new Conf
    val orderDDL =
      s"""
         |CREATE TABLE t_order(
         |order_id int
         |) WITH (
         | 'connector' = 'mysql-cdc',
         | 'hostname'      = '${conf.mysqlHost}',
         | 'port'          = '${conf.mysqlPort}',
         | 'username'      = '${conf.mysqlUser}',
         | 'password'      = '${conf.mysqlPwd}',
         | 'database-name' = '${conf.mysqlDb}',
         | 'table-name'    = '${conf.tOrder}'
         |)
         |""".stripMargin
    sTableEnv.executeSql(orderDDL)
    val orderSql =
      s"""
         |SELECT o.order_id
         |FROM t_order o
         |""".stripMargin
    val orderTable:Table = sTableEnv.sqlQuery(orderSql)
    val orderStream: DataStream[(Boolean, Row)] = sTableEnv.toRetractStream(orderTable)
    orderStream.print()
    env.execute("stat Job")
  }
}

```
- maven本地正常
- 生产环境环境引入flink-connector-mysql-cdc-1.1.0.jar
- 但报错信息没有找到类com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction
```shell
2020-12-09 17:24:54
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:503)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:386)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:284)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:199)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:152)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction
ClassLoader info: URL ClassLoader:
    file: '/tmp/blobStore-5bbc21fe-c396-48d5-8700-eea5ca8994e5/job_a8f0062017d0694de4afa7ef87458535/blob_p-e0862bfca22d875c62f68edd4ae69cd74bbb6303-6396e9d65ca3ca0e373e2d980e641bd5' (valid JAR)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:272)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:126)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:459)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:528)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:61)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1807)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2098)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:260)
	... 6 more

```

**Comment by shizhengchao** [comment]
可能 是jar包有问题，重新编译下cdc的包试下，或者用 flink-sql-connector-mysql-cdc-1.1.0.jar

**Comment by 343701675** [comment]
我也遇到这个问题了，放在lib下面，连接器mysql-cdc加载了，但是这个类就说找不到，从1.0.0到最新的1.2快照版本我都试了，都不行
最终的解决方法是：sql客户端有一个--library的参数，主要是用来加载自定义function的，我试了下把这个连接器的类放到library文件夹下，就可以了

**Comment by wuchong** [comment]
放 lib 下要记得重启 Flink cluster 才行。 通过--library 参数是不需要重启 Flink cluster 的。

**Comment by Narutor** [comment]
集成在cdh里，重启过好多回了，不好使。放那不管他，半个小时自己好了。

**Comment by Narutor** [comment]
这个flink-connector-mysql-cdc-1.1.0.jar jar包会和flink-format-changelog-json-1.0.0.jar 这个jar包冲突，两个放一起就报错了。

**Comment by wuchong** [comment]
@Narutor 清使用相同版本号的 jar 包。

**Comment by Narutor** [comment]
谢谢 哥，复制错了，我跟楼上一样，版本一样的 从1.0试到了 1.2，版本一致的。

**Comment by Narutor** [comment]
谢谢 哥，复制错了，我跟楼上一样，版本一样的 从1.0试到了 1.2，版本一致的。后来又看您的视频移除了flink-connector-mysql-cdc-1.1.0.jar这个就好了，重启没用，可能是cdh的原因，等了一会自己好了。后来加了一些连接hive的jar包，后来降版本又好了，又出问题了。大概就是这样的，谢谢 哥回复。

**Comment by vampireDuke07** [comment]
还有一个可能，lib目录下的其他jar与它发生冲突了，新开一个lib目录就能解决，亲测有效
