### ISSUE TITLE
es connector 6和7同时存在时报错

### ISSUE THREAD

**Issue by JaydenHan1106** [ververica/flink-cdc-connectors#669]
**Describe the bug**
当flink目录同时存在flink-sql-connector-elasticsearch6和flink-sql-connector-elasticsearch7时，写入es报错如下：
Caused by: java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.connectors.elasticsearch.table.RowElasticsearchSinkFunction.

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 
 - flink-sql-connector-elasticsearch6_2.11-1.13.2.jar
 - flink-sql-connector-elasticsearch7_2.11-1.13.2.jar

Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.connectors.elasticsearch.table.RowElasticsearchSinkFunction.<init>(org.apache.flink.streaming.connectors.elasticsearch.table.IndexGenerator, java.lang.String, org.apache.flink.api.common.serialization.SerializationSchema, org.apache.flink.elasticsearch7.shaded.org.elasticsearch.common.xcontent.XContentType, org.apache.flink.streaming.connectors.elasticsearch.table.RequestFactory, java.util.function.Function)'
	at org.apache.flink.streaming.connectors.elasticsearch.table.Elasticsearch7DynamicSink.lambda$getSinkRuntimeProvider$0(Elasticsearch7DynamicSink.java:129)
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecSink.createSinkTransformation(CommonExecSink.java:161)
	at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:130)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:134)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:70)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:69)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.delegation.StreamPlanner.translateToPlan(StreamPlanner.scala:69)
	at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:165)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1518)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:740)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeModifyOperations$4(LocalExecutor.java:226)
	at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:90)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeModifyOperations(LocalExecutor.java:226)
	at org.apache.flink.table.client.cli.CliClient.callInserts(CliClient.java:518)
	at org.apache.flink.table.client.cli.CliClient.callInsert(CliClient.java:507)
	at org.apache.flink.table.client.cli.CliClient.callOperation(CliClient.java:409)
	at org.apache.flink.table.client.cli.CliClient.lambda$executeStatement$0(CliClient.java:327)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:327)
	at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297)
	at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221)
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95)
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)

**Comment by leonardBang** [comment]
This isn't related to Flink CDC Connectors
