### ISSUE TITLE
com.ververica.cdc.connectors.oracle.OracleValidator@2bbf180e is not serializable

### ISSUE THREAD

**Issue by szgyh** [ververica/flink-cdc-connectors#672]
**Describe the bug**

**Environment :**
 - Flink version :  1.3
 - Flink CDC version: 2.1
 - Database and version: oracle12
 - 
用官方的例子oracle api 报错，com.ververica.cdc.connectors.oracle.OracleValidator没有实现序列化接口，不能序列化

Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: com.ververica.cdc.connectors.oracle.OracleValidator@2bbf180e is not serializable. The object probably contains or references non serializable fields.
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:164)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:69)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2053)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1737)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1720)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1689)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1675)
	at com.atguigu.OracleSourceExample.main(OracleSourceExample.java:25)
Caused by: java.io.NotSerializableException: com.ververica.cdc.connectors.oracle.OracleValidator
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
	... 8 more
Disconnected from the target VM, address: '127.0.0.1:60186', transport: 'socket'

Process finished with exit code 1

**Comment by ashulin** [comment]
2.1.0是实现了Serializable接口，应该是其他问题；

**Comment by nayoaixgnat** [comment]
我也遇到了同样问题，解决了么

**Comment by nayoaixgnat** [comment]
我也出现了同样的问题，已经解决，原因是我的工程里同时还有2.0.0的mysql-connector，有冲突，去掉mysql或者把mysql-connector的版本升到和orcale-connector版本相同，问题就解决了。

**Comment by gong** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
