### ISSUE TITLE
Encountered change event for table whose schema isn't known to this connector

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#685]
有两个程序同时在线上跑，都监听了这张表，区别就是一个是flink1.13.1，一个是flink1.13.3，早上该表结构变更，1.13.3的这个抛出这个异常，重启没用，但是1.13.1的这个一切正常，有大佬解释下没

org.apache.kafka.connect.errors.ConnectException: Encountered change event for table  whose schema isn't known to this connector
        at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241)
        at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218)
        at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:607)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1104)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:955)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Encountered change event for table  whose schema isn't known to this connector
        at io.debezium.connector.mysql.BinlogReader.informAboutUnknownTableIfRequired(BinlogReader.java:875)
        at io.debezium.connector.mysql.BinlogReader.handleUpdateTableMetadata(BinlogReader.java:849)
        at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:590)
        ... 5 more

**Comment by lykpass** [comment]
由于mysql版本的限制，目前用的cdc1.14

**Comment by dik111** [comment]
> 由于mysql版本的限制，目前用的cdc1.14

我也遇到了同样的问题，后来是怎么解决的？

**Comment by aLivableDedode** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lykpass** [comment]
> 

还没  目前就手动从头跑了

**Comment by lykpass** [comment]
> > 由于mysql版本的限制，目前用的cdc1.14
> 
> 我也遇到了同样的问题，后来是怎么解决的？

还没 目前就手动从头跑了
