### ISSUE TITLE
DebeziumSourceFunction only stores monitored table ddls which cause error in some situation

### ISSUE THREAD

**Issue by docete** [ververica/flink-cdc-connectors#69]
Take the following case as example:
1) create table T
2) insert value to T
3) connects to DB and monitors T
4) create table tmp_T
5) rename T to del_T, tmp_T to T
6) insert value to T
7) trigger a checkpoint cp-0
8) restore from cp-0

Then, the following error occurs. The root cause is: DebeziumSourceFunction only stores monitored table ddls. If there are some renaming operations, debezium can't rebuild table schema from the monitored table ddls.

17984 [debezium-engine] ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction - Reporting error:
org.apache.kafka.connect.errors.ConnectException: Encountered change event for table inventory_11nwd54.products whose schema isn't known to this connector
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:600) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1130) ~[mysql-binlog-connector-java-0.20.1.jar:0.20.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:978) ~[mysql-binlog-connector-java-0.20.1.jar:0.20.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) ~[mysql-binlog-connector-java-0.20.1.jar:0.20.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:860) ~[mysql-binlog-connector-java-0.20.1.jar:0.20.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: org.apache.kafka.connect.errors.ConnectException: Encountered change event for table inventory_11nwd54.products whose schema isn't known to this connector
	at io.debezium.connector.mysql.BinlogReader.informAboutUnknownTableIfRequired(BinlogReader.java:858) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	at io.debezium.connector.mysql.BinlogReader.handleUpdateTableMetadata(BinlogReader.java:832) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:583) ~[debezium-connector-mysql-1.2.1.Final.jar:1.2.1.Final]
	... 5 more

**Comment by docete** [comment]
![image](https://user-images.githubusercontent.com/59622/102569523-976a0a00-4120-11eb-8eb9-9491adfb2b7e.png)

**Comment by docete** [comment]
fixed in https://github.com/ververica/flink-cdc-connectors/pull/70
