### ISSUE TITLE
oracle cdc在flink sql上执行失败，去掉lib下面的mysql cdc jar包，则执行成功，不能同时存在

### ISSUE THREAD

**Issue by whhpc19891120** [ververica/flink-cdc-connectors#708]
Flink SQL> CREATE TABLE oracle_input_ORACLE_BINLOG (
>     id   INT,
> name   VARCHAR,
> sex   INT
>     ,primary key (id) not enforced
>     ) WITH (
>     'connector' = 'oracle-cdc',
>     'hostname' = '10.202.61.124',
>     'port' = '1521',
>     'username' = 'hanpc',
>     'password' = '123456',
>     'database-name' = 'XE',
>     'table-name' = 'ORACLE_BINLOG',
>     'schema-name' = 'hanpc',
>     'scan.startup.mode' = 'initial'
>     )
> ;
[INFO] Execute statement succeed.

Flink SQL> CREATE TABLE mysql_sink_test3 (
>     id   INT,
> name   VARCHAR,
> sex   INT
>     ,primary key (id) not enforced
>     ) WITH (
>     'connector' = 'jdbc',
>     'driver' = 'com.mysql.cj.jdbc.Driver',
>     'url' = 'jdbc:mysql://10.202.61.123:3306/larkmt_web?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false',
>     'username' = 'isport',
>     'password' = 'isport',
>     'table-name' = 'test3'
>     );
[INFO] Execute statement succeed.

Flink SQL> insert into mysql_sink_test3 select * from oracle_input_ORACLE_BINLOG;

Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.NoSuchMethodError: com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema.newBuilder()Lcom/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema$Builder;
        at com.ververica.cdc.connectors.oracle.table.OracleTableSource.getScanRuntimeProvider(OracleTableSource.java:120)
        at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:453)
        at org.apache.flink.table.planner.connectors.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:161)
        at org.apache.flink.table.planner.connectors.DynamicSourceUtils.convertSourceToRel(DynamicSourceUtils.java:119)
        at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:85)
        at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
        at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
        at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:169)
        at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:161)
        at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:989)
        at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:958)
        at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:283)
        at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:603)
        at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:272)
        at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$parseStatement$1(LocalExecutor.java:176)
        at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:90)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.parseStatement(LocalExecutor.java:176)
        at org.apache.flink.table.client.cli.CliClient.parseCommand(CliClient.java:385)
        at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:326)
        at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297)
        at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221)
        at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151)
        at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95)
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
        ... 1 more

Shutting down the session...
done.

**Comment by jasine** [comment]
same issue

**Comment by paul8263** [comment]
Hi @whhpc19891120 ,
Which version of Oracle and Mysql CDC did you use?

**Comment by whhpc19891120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好邮件已收到~查阅后会尽快回复~O(∩_∩)O谢谢~

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
