### ISSUE TITLE
Unsupported options : debezium.snapshot.mode

### ISSUE THREAD

**Issue by xbinliao** [ververica/flink-cdc-connectors#73]
CREATE TABLE zabbixAlertSource (...)
WITH (
'connector' = 'mysql-cdc',
'hostname' = '###,
'port' = '3306',
'username' = 'flink',
'password' = '###',
'database-name' = '###',
'table-name' = '###',
'debezium.snapshot.mode' = 'never'                      <<
)

Unsupported options:

debezium.snapshot.mode

Supported options:

connector
database-name
hostname
password
port
property-version
server-id
table-name
username
	at org.apache.flink.table.factories.FactoryUtil$TableFactoryHelper.validate(FactoryUtil.java:487)
	at com.alibaba.ververica.cdc.connectors.mysql.table.MySQLTableSourceFactory.createDynamicTableSource(MySQLTableSourceFactory.java:81)
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:122)
	... 21 more

**Comment by HaoWenQiang** [comment]
我也也到了这个问题。。。，请问您是如何解决的
