### ISSUE TITLE
scan.startup.mode	= initial运行flink-sql-cdc读取mysql报Stackoverflow

### ISSUE THREAD

**Issue by L-L-Huang** [ververica/flink-cdc-connectors#736]
**Describe the bug**
11:22:42,179 WARN  org.apache.flink.runtime.taskmanager.Task                     - Source: TableSourceScan(table=[[cdc_ods, flink, es_record]], fields=[id, content, create_userid, create_date, modify_userid, modify_date, op_ts]) -> MiniBatchAssigner(interval=[5000ms], mode=[ProcTime]) -> Calc(select=[id, content, create_userid, create_date, modify_userid, modify_date, CAST(op_ts) AS event_time]) -> SinkConversionToTuple2 -> ods_format_process_risk_spartan.es_record -> Sink: ods_format_sink_table:risk_spartan.es_record (1/4)#0 (7289498b2186e4fd402a6443baf4bc1f) switched from RUNNING to FAILED with failure cause: java.lang.StackOverflowError
	at org.apache.log4j.Logger.isTraceEnabled(Logger.java:209)
	at org.slf4j.impl.Log4jLoggerAdapter.isTraceEnabled(Log4jLoggerAdapter.java:101)
	at org.slf4j.impl.Log4jLoggerAdapter.trace(Log4jLoggerAdapter.java:132)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.moveToNextSplit(SourceReaderBase.java:200)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:158)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:141)

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1
 - Database and version:  mysql-5.7.32

**To Reproduce**
我使用flink-sql cdc直连mysql，然后将table转化为Stream流，Stream接入process算子；在idea的启动过程中，等待一段时间后，报错如上；这个错误属于偶现

**Additional Description**

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
