### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/kafka/connect/source/SourceRecord

### ISSUE THREAD

**Issue by liaobaikai** [ververica/flink-cdc-connectors#742]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version:  
 - Database and version: 

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

参考：
https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html

[root@VM-20-11-centos lib]# ls -ltr
total 237996
-rw-r--r-- 1  502 games     23518 Mar 25  2020 log4j-slf4j-impl-2.12.1.jar
-rw-r--r-- 1  502 games     67114 Mar 25  2020 log4j-1.2-api-2.12.1.jar
-rw-r--r-- 1  502 games    276771 Mar 25  2020 log4j-api-2.12.1.jar
-rw-r--r-- 1  502 games   1674433 Mar 25  2020 log4j-core-2.12.1.jar
-rw-r--r-- 1  502 games   7709740 Apr 10  2021 flink-shaded-zookeeper-3.4.14.jar
-rw-r--r-- 1  502 games    148126 Jul 23 19:31 flink-json-1.13.2.jar
-rw-r--r-- 1  502 games     92314 Jul 23 19:32 flink-csv-1.13.2.jar
-rw-r--r-- 1  502 games  36420572 Jul 23 19:37 flink-table_2.11-1.13.2.jar
-rw-r--r-- 1  502 games  40981118 Jul 23 19:37 flink-table-blink_2.11-1.13.2.jar
-rw-r--r-- 1  502 games 115016309 Jul 23 19:40 flink-dist_2.11-1.13.2.jar
**_-rw-r--r-- 1 root root    3670520 Oct 28 14:23 flink-sql-connector-kafka_2.11-1.13.2.jar
-rw-r--r-- 1 root root   27764261 Dec 20 11:10 flink-sql-connector-elasticsearch7_2.11-1.13.2.jar
-rw-r--r-- 1 root root     222830 Dec 20 11:59 flink-connector-mysql-cdc-2.1.1.jar
-rw-r--r-- 1 root root      28493 Dec 20 12:00 flink-connector-postgres-cdc-2.1.1.jar
-rw-r--r-- 1 root root      87851 Dec 20 13:11 flink-connector-debezium-2.1.1.jar
-rw-r--r-- 1 root root     374571 Dec 20 13:13 jackson-core-2.13.0.jar
-rw-r--r-- 1 root root    1533051 Dec 20 13:15 jackson-databind-2.13.0.jar
-rw-r--r-- 1 root root      75718 Dec 20 13:16 jackson-annotations-2.13.0.jar
-rw-r--r-- 1 root root    3674116 Dec 20 13:18 flink-sql-connector-kafka_2.11-1.13.5.jar
-rw-r--r-- 1 root root    3820237 Dec 20 13:50 flink-sql-avro-1.13.5.jar_**

**Additional Description**
Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/connect/source/SourceRecord
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1643)
        at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:79)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:520)
        at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:494)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:391)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1134)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
        at org.apache.flink.util.SerializedValue.<init>(SerializedValue.java:62)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobVertex(StreamingJobGraphGenerator.java:597)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createChain(StreamingJobGraphGenerator.java:457)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.setChaining(StreamingJobGraphGenerator.java:378)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:179)
        at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:117)
        at org.apache.flink.streaming.api.graph.StreamGraph.getJobGraph(StreamGraph.java:934)
        at org.apache.flink.client.StreamGraphTranslator.translateToJobGraph(StreamGraphTranslator.java:50)
        at org.apache.flink.client.FlinkPipelineTranslationUtil.getJobGraph(FlinkPipelineTranslationUtil.java:39)
        at org.apache.flink.client.deployment.executors.PipelineExecutorUtils.getJobGraph(PipelineExecutorUtils.java:56)
        at org.apache.flink.client.deployment.executors.AbstractSessionClusterExecutor.execute(AbstractSessionClusterExecutor.java:67)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1957)
        at org.apache.flink.table.planner.delegation.ExecutorBase.executeAsync(ExecutorBase.java:55)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeQueryOperation(TableEnvironmentImpl.java:795)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1225)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeOperation$3(LocalExecutor.java:213)
        at org.apache.flink.table.client.gateway.context.ExecutionContext.wrapClassLoader(ExecutionContext.java:90)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:213)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQuery(LocalExecutor.java:235)
        at org.apache.flink.table.client.cli.CliClient.callSelect(CliClient.java:479)
        at org.apache.flink.table.client.cli.CliClient.callOperation(CliClient.java:412)
        at org.apache.flink.table.client.cli.CliClient.lambda$executeStatement$0(CliClient.java:327)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.apache.flink.table.client.cli.CliClient.executeStatement(CliClient.java:327)
        at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:297)
        at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:221)
        at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151)
        at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95)
        at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.source.SourceRecord
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 51 more

**Comment by rookiegao** [comment]
You can comment out non SQL jar packages to see if there is a jar package conflict

**Comment by liaobaikai** [comment]
哪里可以找到这个jar 包呢？

**Comment by liaobaikai** [comment]
fix flink version upgrade to: https://dlcdn.apache.org/flink/flink-1.13.5/flink-1.13.5-bin-scala_2.11.tgz
