### ISSUE TITLE
Failed to deserialize data of EventHeaderV4

### ISSUE THREAD

**Issue by q2515045** [ververica/flink-cdc-connectors#773]
**Describe the bug**
When multiple Flink CDCs synchronize the same MySQL database instance at the same time, this error is most likely to occur if the database is updated with large transaction data (one transaction updates or inserts millions or tens of millions of data).

An attempt has been made and "set global slave_net_timeout = 120; " cannot resolve this issue
and 
set global thread_pool_idle_timeout = 120; this configuration mysql5 7 not supported

**Environment :**
 - Flink version :  1.9.2
 - Flink CDC version: 1.1.0
 - Database and version: mysql 5.7

**Initial exception**
Error info:
1. The error :
2022-01-04 21:21:59,779 ERROR io.debezium.connector.mysql.BinlogReader                      - Error while deserializing binlog event at offset {ts_sec=1641299601, file=jzdb-bin.000335, pos=1021207904, gtids=1c5a8e58-7b5e-11eb-81ce-54802851e594:1-24308447,47fccb5f-7afb-11ea-818e-98f2b312e5d4:1-3, server_id=1033238, event=300}.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=1023646827 --stop-position=1023655030 --verbose jzdb-bin.000335
2022-01-04 21:21:59,779 ERROR io.debezium.connector.mysql.BinlogReader                      - Error during binlog processing. Last offset stored = {ts_sec=1641299601, file=jzdb-bin.000335, pos=1016206331, gtids=1c5a8e58-7b5e-11eb-81ce-54802851e594:1-24308446,47fccb5f-7afb-11ea-818e-98f2b312e5d4:1-3, row=30, server_id=1033238, event=566}, binlog reader near position = jzdb-bin.000335/1023646827
2022-01-04 21:21:59,780 ERROR io.debezium.connector.mysql.BinlogReader                      - Failed due to error: Error processing binlog event
shaded.org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1641299601000, eventType=EXT_WRITE_ROWS, serverId=1033238, headerLength=19, dataLength=8184, nextPosition=1023655030, flags=0}
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:600)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1130)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:978)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:860)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1641299601000, eventType=EXT_WRITE_ROWS, serverId=1033238, headerLength=19, dataLength=8184, nextPosition=1023655030, flags=0}
	at io.debezium.connector.mysql.BinlogReader.handleServerIncident(BinlogReader.java:668)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:583)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1641299601000, eventType=EXT_WRITE_ROWS, serverId=1033238, headerLength=19, dataLength=8184, nextPosition=1023655030, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223)
	at io.debezium.connector.mysql.BinlogReader$1.nextEvent(BinlogReader.java:249)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:957)
	... 3 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.InputStream.skip(InputStream.java:224)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296)
	... 6 more

**Comment by xiaoshijiang523** [comment]
I also encountered this problem. After I upgraded the version to 2.10, the problem disappeared.

**Comment by q2515045** [comment]
> I also encountered this problem. After I upgraded the version to 2.10, the problem disappeared.

Thank you for your valuable information

**Comment by q2515045** [comment]
I will try to upgrade the version, observe the production service and feed back the results

**Comment by zhilinli123** [comment]
Does this problem still recur after you upgrade? I encountered this problem in 2.2.1
@q2515045

**Comment by voyagertanyao** [comment]
> Does this problem still recur after you upgrade? I encountered this problem in 2.2.1 @q2515045

**Me Too!! Below is what i got:(flink 1.14.5, flink cdc 2.2.1, mysql 5.7)
This happend when i restart job from a savepoint after about 10mins, and 2 times occured during 2 days running**
@leonardBang  hi , boss ,is there any solution？Or More information u need to know ?




2022-07-04 11:26:06
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:225)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:130)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:156)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:354)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler.setProducerThrowable(MySqlErrorHandler.java:72)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1185)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:973)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)
	... 1 more
Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1656904615000, eventType=EXT_UPDATE_ROWS, serverId=110009, headerLength=19, dataLength=421, nextPosition=672941277, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1146)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1656904615000, eventType=EXT_UPDATE_ROWS, serverId=110009, headerLength=19, dataLength=421, nextPosition=672941277, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945)
	... 3 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:113)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:104)
	at io.debezium.connector.mysql.RowDeserializers.deserializeVarString(RowDeserializers.java:264)
	at io.debezium.connector.mysql.RowDeserializers$UpdateRowsDeserializer.deserializeVarString(RowDeserializers.java:130)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:189)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:143)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:72)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	... 6 more

**Comment by voyagertanyao** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/20474171/177463721-2c503027-1691-4fe2-8c14-24713502886a.png">

**Comment by leonardBang** [comment]
I've investigated this issue， I found it happen to appear when the downstream operators are backpressured. 
I'll try to analyze the related code to find the root cause.

**Comment by li57598** [comment]
Hi, I encountered the same problem in version 2.2. How did you solve it？

**Comment by li57598** [comment]
Hi, I encountered the same problem in version 2.2. How did you solve it？ @leonardBang

**Comment by KevinZwx** [comment]
hi @leonardBang , any update on this problem? I met this problem in 2.4.0, is there any suggestion to solve it by ourselves?

**Comment by potterhe** [comment]
v2.3.0 reappeared. After using savepoint to restore the task, it was not triggered again. It felt like it was accidental.

`
2023-12-08 07:16:40,629 ERROR io.debezium.pipeline.ErrorHandler                            [] - Producer failure
io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1702018927000, eventType=UPDATE_ROWS, serverId=27665007, headerLength=19, dataLength=1089, nextPosition=330664276, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1383) ~[flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1439) [flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:980) [flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [flink-sql-connector-mysql-cdc-2.3.0.jar:2.3.0]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1702018927000, eventType=UPDATE_ROWS, serverId=27665007, headerLength=19, dataLength=1089, nextPosition=330664276, flags=0}
	at com.github.shyiko.mysql.binlog
`

**Comment by komiblog** [comment]
Same problem

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by WanYukun** [comment]
2.2.0 Same problem

**Comment by NullHunt** [comment]
haha， i found the arg of debezium: [max.queue.size](https://debezium.io/documentation/reference/1.9/connectors/mysql.html#mysql-property-max-queue-size), 

i set it to 100000, and solve the problem. 
The blocking queue can provide backpressure for reading change events from the database.， and through peak traffic periods.

**Comment by Rohanhevo** [comment]
Hey @NullHunt, is it related to binlog_row_metadata setting to FULL instead of default MINIMAL?

**Comment by WanYukun** [comment]
这是来自QQ邮箱的自动回复邮件。你好，邮件正常收到，谢谢！                          -----万玉坤
