### ISSUE TITLE
flink-sql-connector-postgres-cdc-2.1.1  java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by zhijiansd** [ververica/flink-cdc-connectors#788]
**Describe the bug**
flink-sql-connector-postgres-cdc  java.net.SocketTimeoutException: connect timed out

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.1.1
 - Database and version: 12.9

**To Reproduce**
1. The test code :
```sql
create table flink_cdc01(
  id int primary key,
  name varchar,
  age int
)
WITH (
   'connector' = 'postgres-cdc',
   'hostname' = '192.168.100.105',
   'port' = '5432',
   'username' = 'postgres',
   'password' = '123456',
   'database-name' = 'postgres',
   'schema-name' = 'public',
   'table-name' = 'flink'
);
```
2. The error :
```bash
Flink SQL> select * from flink_cdc011;
[ERROR] Could not execute SQL statement. Reason:
java.net.SocketTimeoutException: connect timed out
```

**Additional Description**
```bash
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:216) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:206) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:197) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:682) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:435) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.actor.ActorCell.invoke(ActorCell.scala:561) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[flink-dist_2.12-1.13.5.jar:1.13.5]
Caused by: io.debezium.DebeziumException: Couldn't initialize type registry
	at io.debezium.connector.postgresql.TypeRegistry.<init>(TypeRegistry.java:129) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:76) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:75) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_271]
Caused by: org.postgresql.util.PSQLException: 尝试连线已失败。
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:297) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:217) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.Driver.makeConnection(Driver.java:458) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.Driver.connect(Driver.java:260) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:231) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:872) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:867) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.TypeRegistry.<init>(TypeRegistry.java:122) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:76) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:75) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_271]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_271]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[?:1.8.0_271]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[?:1.8.0_271]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[?:1.8.0_271]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[?:1.8.0_271]
	at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_271]
	at org.postgresql.core.PGStream.<init>(PGStream.java:81) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:93) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:217) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.Driver.makeConnection(Driver.java:458) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at org.postgresql.Driver.connect(Driver.java:260) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:231) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:872) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:867) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.TypeRegistry.<init>(TypeRegistry.java:122) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:76) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:75) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) ~[flink-sql-connector-postgres-cdc-2.1.1.jar:2.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_271]
```

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
