### ISSUE TITLE
Flink Sql Mongo 使用的版本是2.1.1 执行同步mongo数据 ,控制台报错: java.lang.ClassCastException: com.ververica.cdc.connectors.mongodb.internal.MongoDBConnectorSourceConnector cannot be cast to com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceConnector 	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:668) [flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1] 	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) [flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_281] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_281] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]

### ISSUE THREAD

**Issue by zuoshoudao** [ververica/flink-cdc-connectors#797]
**Describe the bug**

**Environment :**
 - Flink version :  
 - Flink CDC version: 
 - Database and version: 

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by zuoshoudao** [comment]
问题找到了,依赖中有flink cdc mysql所以才会报错

**Comment by QuintinLuke** [comment]
> 问题找到了,依赖中有flink cdc mysql所以才会报错

不能有其他的cdc?
