### ISSUE TITLE
Connector Options

### ISSUE THREAD

**Issue by imkew** [ververica/flink-cdc-connectors#820]
When I read a shared database  that contains multiple tables, How do I set up to determine which table the data is from?

**Comment by rookiegao** [comment]
Can I understand that you want metadata information? For example, table name?

Here is an official case:

```
CREATE TABLE products (
    db_name STRING METADATA FROM 'database_name' VIRTUAL,
    table_name STRING METADATA  FROM 'table_name' VIRTUAL,
    operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
    order_id INT,
    order_date TIMESTAMP(0),
    customer_name STRING,
    price DECIMAL(10, 5),
    product_id INT,
    order_status BOOLEAN,
    PRIMARY KEY(order_id) NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'mydb',
    'table-name' = 'orders'
);
```

For more information, refer to

[MySQL CDC Connector](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html)

I hope this will help you.

**Comment by imkew** [comment]
> Can I understand that you want metadata information? For example, table name?
> 
> Here is an official case:
> 
> ```
> CREATE TABLE products (
>     db_name STRING METADATA FROM 'database_name' VIRTUAL,
>     table_name STRING METADATA  FROM 'table_name' VIRTUAL,
>     operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
>     order_id INT,
>     order_date TIMESTAMP(0),
>     customer_name STRING,
>     price DECIMAL(10, 5),
>     product_id INT,
>     order_status BOOLEAN,
>     PRIMARY KEY(order_id) NOT ENFORCED
> ) WITH (
>     'connector' = 'mysql-cdc',
>     'hostname' = 'localhost',
>     'port' = '3306',
>     'username' = 'root',
>     'password' = '123456',
>     'database-name' = 'mydb',
>     'table-name' = 'orders'
> );
> ```
> 
> For more information, refer to
> 
> [MySQL CDC Connector](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html)
> 
> I hope this will help you.

**Comment by imkew** [comment]
> Can I understand that you want metadata information? For example, table name?
> 
> Here is an official case:
> 
> ```
> CREATE TABLE products (
>     db_name STRING METADATA FROM 'database_name' VIRTUAL,
>     table_name STRING METADATA  FROM 'table_name' VIRTUAL,
>     operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
>     order_id INT,
>     order_date TIMESTAMP(0),
>     customer_name STRING,
>     price DECIMAL(10, 5),
>     product_id INT,
>     order_status BOOLEAN,
>     PRIMARY KEY(order_id) NOT ENFORCED
> ) WITH (
>     'connector' = 'mysql-cdc',
>     'hostname' = 'localhost',
>     'port' = '3306',
>     'username' = 'root',
>     'password' = '123456',
>     'database-name' = 'mydb',
>     'table-name' = 'orders'
> );
> ```
> 
> For more information, refer to
> 
> [MySQL CDC Connector](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html)
> 
> I hope this will help you.

Thank you very much This is what I want.In addition, can flinksql-cdc get the operator, such as '-U' '+U' '-D' '+I'

> 

Thank you very much This is what I want.In addition, can flinksql-cdc get the operator, such as '-U' '+U' '-D' '+I'

> > Can I understand that you want metadata information? For example, table name?
> > Here is an official case:
> > ```
> > CREATE TABLE products (
> >     db_name STRING METADATA FROM 'database_name' VIRTUAL,
> >     table_name STRING METADATA  FROM 'table_name' VIRTUAL,
> >     operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
> >     order_id INT,
> >     order_date TIMESTAMP(0),
> >     customer_name STRING,
> >     price DECIMAL(10, 5),
> >     product_id INT,
> >     order_status BOOLEAN,
> >     PRIMARY KEY(order_id) NOT ENFORCED
> > ) WITH (
> >     'connector' = 'mysql-cdc',
> >     'hostname' = 'localhost',
> >     'port' = '3306',
> >     'username' = 'root',
> >     'password' = '123456',
> >     'database-name' = 'mydb',
> >     'table-name' = 'orders'
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For more information, refer to
> > [MySQL CDC Connector](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html)
> > I hope this will help you.

Thank you very much This is what I want.In addition, can flinksql-cdc get the operator, such as '-U' '+U' '-D' '+I'

**Comment by imkew** [comment]
> Can I understand that you want metadata information? For example, table name?
> 
> Here is an official case:
> 
> ```
> CREATE TABLE products (
>     db_name STRING METADATA FROM 'database_name' VIRTUAL,
>     table_name STRING METADATA  FROM 'table_name' VIRTUAL,
>     operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
>     order_id INT,
>     order_date TIMESTAMP(0),
>     customer_name STRING,
>     price DECIMAL(10, 5),
>     product_id INT,
>     order_status BOOLEAN,
>     PRIMARY KEY(order_id) NOT ENFORCED
> ) WITH (
>     'connector' = 'mysql-cdc',
>     'hostname' = 'localhost',
>     'port' = '3306',
>     'username' = 'root',
>     'password' = '123456',
>     'database-name' = 'mydb',
>     'table-name' = 'orders'
> );
> ```
> 
> For more information, refer to
> 
> [MySQL CDC Connector](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html)
> 
> I hope this will help you.

Thank you very much This is what I want.In addition, can flinksql-cdc get the operator, such as '-U' '+U' '-D' '+I'

**Comment by imkew** [comment]
`+--------+
| result |
+--------+
|     OK |
+--------+
1 row in set
Exception in thread "main" org.apache.flink.table.api.ValidationException: Table 'MySQL-CDC' declares metadata columns, but the underlying DynamicTableSource doesn't implement the SupportsReadingMetadata interface. Therefore, metadata cannot be read from the given source.
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateAndApplyMetadata(DynamicSourceUtils.java:384)
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:158)
	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.convertSourceToRel(DynamicSourceUtils.java:119)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:85)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:169)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:161)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:989)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:958)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:283)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724)
`
create ddl is ok,but a simple query has an exception for exanple `select * from table`

**Comment by rookiegao** [comment]
According to the document, the current SQL method does not seem to support obtaining specific operation types. You might as well create an issues? At the same time, you can try to improve it.
