### ISSUE TITLE
NoSuchMethodError: org.apache.flink.api.connector.source.SourceReaderContext.metricGroup()Lorg/apache/flink/metrics/MetricGroup;

### ISSUE THREAD

**Issue by sunny1901** [ververica/flink-cdc-connectors#832]
**Describe the bug**

**Environment :**
 - Flink version :  1.14.2
 - Flink CDC version: 2.1.1 
 - Database and version: mysql8

**Additional Description**
2022-01-25 18:56:09
java.lang.NoSuchMethodError: org.apache.flink.api.connector.source.SourceReaderContext.metricGroup()Lorg/apache/flink/metrics/MetricGroup;
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createReader(MySqlSource.java:134)
	at org.apache.flink.streaming.api.operators.SourceOperator.initReader(SourceOperator.java:259)
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask.init(SourceOperatorStreamTask.java:70)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:677)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
	at java.lang.Thread.run(Thread.java:748)

**Comment by paul8263** [comment]
Hi @sunny1901 ,
Currently it does not support Flink 1.14.2. Please try 1.13.* .

**Comment by JaneConan** [comment]
> Hi @sunny1901 , Currently it does not support Flink 1.14.2. Please try 1.13.* .

so, which cdc and flink version is work? we need a release supprot and right work version THX!

**Comment by JaneConan** [comment]
this bug also show in flink v1.14 and v1.17.x
