### ISSUE TITLE
gtid没有生效

### ISSUE THREAD

**Issue by nayoaixgnat** [ververica/flink-cdc-connectors#845]
在使用cdc的stream api的过程中遇到了报错：

io.debezium.DebeziumException: The connector is trying to read binlog starting at SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin.004498, currentBinlogPosition=7859643, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
	at io.debezium.connector.mysql.MySqlConnectorTask.validateSnapshotFeasibility(MySqlConnectorTask.java:329)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:98)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2.0.2不是已经支持了gtid了么，我的mysql是高可用并开启了gtid：

binlog_gtid_simple_recovery	ON
enforce_gtid_consistency	ON
gtid_executed	"89f58b69-27c5-11ea-9a47-00163e0a7028:1-241091988,
89fbc18f-27c5-11ea-8c0a-00163e16ff86:1-29370852"
gtid_executed_compression_period	1000
gtid_mode	ON
gtid_owned	
gtid_purged	"89f58b69-27c5-11ea-9a47-00163e0a7028:1-240938829,
89fbc18f-27c5-11ea-8c0a-00163e16ff86:1-29370851"
opt_rds_last_error_gtid	ON
rds_push_gtid_default_interval	10
session_track_gtids	OFF

是需要额外的配置么，@leonardBang在flink cdc钉钉群说过 ：用2.0.2版本或者master即可，开启了gtid会优先使用

**Comment by guixin** [comment]
hi，可以看下是不是 「currentBinlogFilename=mysql-bin.004498」这个 file 是不是已经不存在了？在 mysql 里执行 `show binary logs`

**Comment by nayoaixgnat** [comment]
> 



> hi，可以看下是不是 「currentBinlogFilename=mysql-bin.004498」这个 file 是不是已经不存在了？在 mysql 里执行 `show binary logs`

现在确实查不到了这个，但是我这mysql应该是进行过主备切换，binlog应该是不一样了，正常来说cdc不是已经支持了gtid点位么，但是我这报错看起来没有使用gtid啊

**Comment by guixin** [comment]
@nayoaixgnat 主从切换后，恢复时有个bug，有同学已经提 mr 修复了，MR 地址 https://github.com/ververica/flink-cdc-connectors/pull/761

**Comment by guixin** [comment]
cdc 是支持 gtid 恢复，但是恢复前优先判断了 binlog file，请等待 master 更新。目前遇到这个问题需要重新 snapshot 来重启作业

**Comment by nayoaixgnat** [comment]
> cdc 是支持 gtid 恢复，但是恢复前优先判断了 binlog file，请等待 master 更新。目前遇到这个问题需要重新 snapshot 来重启作业
