### ISSUE TITLE
报错AbstractMethodError: org.apache.kafka.connect.json.JsonSerializer.configure

### ISSUE THREAD

**Issue by sdlcwangsong** [ververica/flink-cdc-connectors#9]
你好，我在执行Usage for DataStream API的demo时报如下错误，请问是什么原因呢？
```
Caused by: java.lang.AbstractMethodError: org.apache.kafka.connect.json.JsonSerializer.configure(Ljava/util/Map;Z)V
	at org.apache.kafka.connect.json.JsonConverter.configure(JsonConverter.java:300)
	at org.apache.kafka.connect.json.JsonConverter.configure(JsonConverter.java:311)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:582)
	at io.debezium.embedded.EmbeddedEngine.<init>(EmbeddedEngine.java:79)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:300)
	at io.debezium.embedded.EmbeddedEngine$BuilderImpl.build(EmbeddedEngine.java:216)
	at io.debezium.embedded.ConvertingEngineBuilder.build(ConvertingEngineBuilder.java:139)
	at com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:299)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:201)
```

**Comment by sdlcwangsong** [comment]
我用的是自己的mysql库，使用该案例时mysql是否需要进行特殊配置呢？

**Comment by wuchong** [comment]
请检查下你的项目中是否有依赖 kafka-connect? 
因为 flink-cdc-connectors 依赖了kafka-connect 2.5.0，并且没有做 shade。如果你的项目中也依赖了kafka-connect ，要保持版本一致。

**Comment by wcf1** [comment]
原因在与flink-cdc-connectors的部分类与kafka的一些类，其包名和类名一样，产生冲突了。可以把flink-cdc-connectors做成shaded，然后程序引用shaded之后的jar包，就可以解决这个问题。

**Comment by wcf1** [comment]
可以把flink-cdc-connectors做成shaded，然后程序引用shaded之后的jar包，就可以解决这个问题，不然需要换kafka版本。

**Comment by xunchangguo** [comment]
这个问题怎么解决？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
