### ISSUE TITLE
[mongodb] The test  MongoDBConnectorITCase.testConsumingAllEvents failed in azure CI

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#919]
```
2022-03-09T08:24:09.6692574Z Mar 09 08:24:09 08:24:09.668 [INFO] Running com.ververica.cdc.connectors.mongodb.table.MongoDBTimeZoneITCase
2022-03-09T08:24:09.6982839Z Mar 09 08:24:09 08:24:09.697 [INFO] Running com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase
2022-03-09T08:24:46.1187929Z Mar 09 08:24:46 08:24:46.118 [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.433 s - in com.ververica.cdc.connectors.mongodb.table.MongoDBTimeZoneITCase
2022-03-09T08:34:49.3664422Z Mar 09 08:34:49 08:34:49.364 [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 639.662 s <<< FAILURE! - in com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase
2022-03-09T08:34:49.3667745Z Mar 09 08:34:49 08:34:49.366 [ERROR] testConsumingAllEvents(com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase)  Time elapsed: 604.647 s  <<< FAILURE!
2022-03-09T08:34:49.3668843Z Mar 09 08:34:49 java.lang.AssertionError: 
2022-03-09T08:34:49.3669379Z Mar 09 08:34:49 Wait for sink size timeout, raw results: 
2022-03-09T08:34:49.3669903Z Mar 09 08:34:49 +I(scooter,3.140)
2022-03-09T08:34:49.3670365Z Mar 09 08:34:49 +I(car battery,8.100)
2022-03-09T08:34:49.3671214Z Mar 09 08:34:49 +I(12-pack drill bits,0.800)
2022-03-09T08:34:49.3671720Z Mar 09 08:34:49 +I(hammer,0.750)
2022-03-09T08:34:49.3672143Z Mar 09 08:34:49 +U(hammer,1.625)
2022-03-09T08:34:49.3672605Z Mar 09 08:34:49 +U(hammer,2.625)
2022-03-09T08:34:49.3673056Z Mar 09 08:34:49 +I(rocks,5.300)
2022-03-09T08:34:49.3673518Z Mar 09 08:34:49 +I(jacket,0.100)
2022-03-09T08:34:49.3673954Z Mar 09 08:34:49 +I(spare tire,22.200)
2022-03-09T08:34:49.3674370Z Mar 09 08:34:49 +U(hammer,1.625)
2022-03-09T08:34:49.3674796Z Mar 09 08:34:49 +U(hammer,2.625)
2022-03-09T08:34:49.3675348Z Mar 09 08:34:49 -D(rocks,5.300)
2022-03-09T08:34:49.3675810Z Mar 09 08:34:49 +I(rocks,5.100)
2022-03-09T08:34:49.3676236Z Mar 09 08:34:49 +U(jacket,0.300)
2022-03-09T08:34:49.3676647Z Mar 09 08:34:49 +U(scooter,8.320)
2022-03-09T08:34:49.3677072Z Mar 09 08:34:49 +U(jacket,0.100)
2022-03-09T08:34:49.3680080Z Mar 09 08:34:49 +U(jacket,0.600)
2022-03-09T08:34:49.3680743Z Mar 09 08:34:49 +U(scooter,3.140)
2022-03-09T08:34:49.3681426Z Mar 09 08:34:49 	at com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase.waitForSinkSize(MongoDBConnectorITCase.java:490)
2022-03-09T08:34:49.3682311Z Mar 09 08:34:49 	at com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase.waitForSinkSize(MongoDBConnectorITCase.java:481)
2022-03-09T08:34:49.3683196Z Mar 09 08:34:49 	at com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase.testConsumingAllEvents(MongoDBConnectorITCase.java:151)
2022-03-09T08:34:49.3683894Z Mar 09 08:34:49 
2022-03-09T08:34:49.7049309Z Mar 09 08:34:49 08:34:49.703 [INFO] 
2022-03-09T08:34:49.7053979Z Mar 09 08:34:49 08:34:49.703 [INFO] Results:
2022-03-09T08:34:49.7057300Z Mar 09 08:34:49 08:34:49.703 [INFO] 
2022-03-09T08:34:49.7058034Z Mar 09 08:34:49 08:34:49.703 [ERROR] Failures: 
2022-03-09T08:34:49.7059424Z Mar 09 08:34:49 08:34:49.703 [ERROR]   MongoDBConnectorITCase.testConsumingAllEvents:151->waitForSinkSize:481->waitForSinkSize:490 Wait for sink size timeout, raw results: 
2022-03-09T08:34:49.7060178Z Mar 09 08:34:49 +I(scooter,3.140)
2022-03-09T08:34:49.7060613Z Mar 09 08:34:49 +I(car battery,8.100)
2022-03-09T08:34:49.7061463Z Mar 09 08:34:49 +I(12-pack drill bits,0.800)
2022-03-09T08:34:49.7063013Z Mar 09 08:34:49 +I(hammer,0.750)
2022-03-09T08:34:49.7064194Z Mar 09 08:34:49 +U(hammer,1.625)
2022-03-09T08:34:49.7064723Z Mar 09 08:34:49 +U(hammer,2.625)
2022-03-09T08:34:49.7065174Z Mar 09 08:34:49 +I(rocks,5.300)
2022-03-09T08:34:49.7065639Z Mar 09 08:34:49 +I(jacket,0.100)
2022-03-09T08:34:49.7066108Z Mar 09 08:34:49 +I(spare tire,22.200)
2022-03-09T08:34:49.7066573Z Mar 09 08:34:49 +U(hammer,1.625)
2022-03-09T08:34:49.7067035Z Mar 09 08:34:49 +U(hammer,2.625)
2022-03-09T08:34:49.7067771Z Mar 09 08:34:49 -D(rocks,5.300)
2022-03-09T08:34:49.7068253Z Mar 09 08:34:49 +I(rocks,5.100)
2022-03-09T08:34:49.7068712Z Mar 09 08:34:49 +U(jacket,0.300)
2022-03-09T08:34:49.7082570Z Mar 09 08:34:49 +U(scooter,8.320)
2022-03-09T08:34:49.7083270Z Mar 09 08:34:49 +U(jacket,0.100)
2022-03-09T08:34:49.7083737Z Mar 09 08:34:49 +U(jacket,0.600)
2022-03-09T08:34:49.7084212Z Mar 09 08:34:49 +U(scooter,3.140)
2022-03-09T08:34:49.7084688Z Mar 09 08:34:49 08:34:49.703 [INFO] 
2022-03-09T08:34:49.7085225Z Mar 09 08:34:49 08:34:49.704 [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0

```

Failed instance: https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=1057&view=logs&j=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&t=35f661f6-a91b-58bc-c86e-9c0883818913

**Comment by Jiabao-Sun** [comment]
Expected |  Failed
------------ | -------------
+I(scooter,3.140)            |    +I(scooter,3.140)   
+I(car battery,8.100)        |    +I(car battery,8.100)
+I(12-pack drill bits,0.800) |    +I(12-pack drill bits,0.800)
+I(hammer,0.750)             |    +I(hammer,0.750)
+U(hammer,1.625)             |    +U(hammer,1.625)
+U(hammer,2.625)             |    +U(hammer,2.625)
+I(rocks,5.300)              |    +I(rocks,5.300)
+I(jacket,0.100)             |    +I(jacket,0.100)
+I(spare tire,22.200)        |    +I(spare tire,22.200)
+U(hammer,1.625)             |    +U(hammer,1.625)
+U(hammer,2.625)             |    +U(hammer,2.625)
-D(rocks,5.300)              |    -D(rocks,5.300)
+I(rocks,5.100)              |    +I(rocks,5.100)
+U(jacket,0.300)             |    +U(jacket,0.300)
+U(scooter,8.320)            |    +U(scooter,8.320)
+U(jacket,0.100)             |    +U(jacket,0.100)
+U(jacket,0.600)             |    +U(jacket,0.600)
+U(scooter,3.140)            |    +U(scooter,3.140)
+U(scooter,8.310)            |    -
+U(scooter,3.140)            |    -

The `scooter` records changes in the following order.
```sql
INSERT (101, scooter, 3.140)
INSERT (111, scooter, 5.18)
UPDATE (111, scooter, 5.17)
DELETE (111, scooter, 5.17)
```

We ignored an update record because the record has been deleted at that point in time, please refer to:

https://www.mongodb.com/community/forums/t/how-can-change-stream-update-operations-come-with-null-fulldocument-when-changestreamfulldocumentoption-updatelookup-was-used/2537/3
> If there are one or more majority-committed operations that modified the updated document after the update operation but before the lookup, the full document returned may differ significantly from the document at the time of the update operation. In this case, it’s null if another operation deletes the document before the lookup operation happens.

This creates instability for the test, but the result is eventually consistent.
https://github.com/ververica/flink-cdc-connectors/blob/dfca2417a8531c87d4657823dc34da85024313a0/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java#L139-L148

I'll push a PR to fix this problem.
