### ISSUE TITLE
cdc解析binlog中的ddl加字段语句报错

### ISSUE THREAD

**Issue by Level1Accelerator** [ververica/flink-cdc-connectors#923]
**Describe the bug**
换了2.0.2版本 2.1.1版本都是一样的问题 本身这个add 语句不是很规范 但是mysql（5.x 8.x版本)能执行 flink cdc任务直接报错。 异常都捕获不到 ，目前没有解决办法，任务没法恢复 很着急啊。

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.0.2
 - Database and version: mysql5.7 mysql8

原建表语句：
CREATE TABLE `order_sign_received` (
  `order_number` varchar(32) NOT NULL COMMENT '运单编号',
  `sign_people_mobile` varchar(12) DEFAULT NULL COMMENT '签收人电话',
  `function_code` varchar(32) DEFAULT NULL COMMENT '方法编码',
  PRIMARY KEY (`order_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

ddl语句：
ALTER TABLE order_sign_received ADD(
    received_pay_method_changed TINYINT DEFAULT 0 NOT NULL COMMENT '签收修改了收款方式，0：否 1：是'
);

错误信息：
![image](https://user-images.githubusercontent.com/14903509/157601715-788e7d9a-01cd-4e5b-a86f-0d386a97eeb7.png)

![image](https://user-images.githubusercontent.com/14903509/157601796-f77eb610-dab3-4398-b08f-c4a2f54892bc.png)

[blc-localhost:3306] ERROR MySqlStreamingChangeEventSource - Error during binlog processing. Last offset stored = null, binlog reader near position = binlog.000007/3857

[blc-localhost:3306] ERROR ErrorHandler - Producer failure

io.debezium.DebeziumException: Error processing binlog event

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:369)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)

	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)

	at java.lang.Thread.run(Thread.java:748)

Caused by: io.debezium.DebeziumException: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:584)

	at io.debezium.pipeline.EventDispatcher.dispatchSchemaChangeEvent(EventDispatcher.java:276)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:579)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352)

	... 5 more

Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)

	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:374)

	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:119)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)

	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:117)

	at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.lambda$applySchemaChange$2(MySqlDatabaseSchema.java:168)

	at java.lang.Iterable.forEach(Iterable.java:75)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.applySchemaChange(MySqlDatabaseSchema.java:168)

	at io.debezium.pipeline.EventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(EventDispatcher.java:462)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:581)

	... 8 more

Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type INT16: class java.lang.String for field: "null"

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:245)

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)

	... 26 more

[debezium-engine] ERROR Handover - Reporting error:

org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.

	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:369)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)

	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)

	at java.lang.Thread.run(Thread.java:748)

Caused by: io.debezium.DebeziumException: Error processing binlog event

	... 6 more

Caused by: io.debezium.DebeziumException: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:584)

	at io.debezium.pipeline.EventDispatcher.dispatchSchemaChangeEvent(EventDispatcher.java:276)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:579)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352)

	... 5 more

Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)

	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:374)

	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:119)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)

	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:117)

	at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.lambda$applySchemaChange$2(MySqlDatabaseSchema.java:168)

	at java.lang.Iterable.forEach(Iterable.java:75)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.applySchemaChange(MySqlDatabaseSchema.java:168)

	at io.debezium.pipeline.EventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(EventDispatcher.java:462)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:581)

	... 8 more

Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type INT16: class java.lang.String for field: "null"

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:245)

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)

	... 26 more

Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.

	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)

	at org.apache.flink.runtime.minicluster.MiniClusterJobClient.lambda$getJobExecutionResult$3(MiniClusterJobClient.java:137)

	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)

	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)

	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)

	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)

	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$0(AkkaInvocationHandler.java:237)

	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)

	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)

	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)

	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)

	at org.apache.flink.runtime.concurrent.FutureUtils$1.onComplete(FutureUtils.java:1081)

	at akka.dispatch.OnComplete.internal(Future.scala:264)

	at akka.dispatch.OnComplete.internal(Future.scala:261)

	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:191)

	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:188)

	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:36)

	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)

	at org.apache.flink.runtime.concurrent.Executors$DirectExecutionContext.execute(Executors.java:73)

	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)

	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)

	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:572)

	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:22)

	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:21)

	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:436)

	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:435)

	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:36)

	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)

	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)

	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)

	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)

	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)

	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)

	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)

	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)

	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)

	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy

	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)

	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)

	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:207)

	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:197)

	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:188)

	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:677)

	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79)

	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:435)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)

	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)

	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)

	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)

	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)

	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)

	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)

	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)

	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)

	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)

	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)

	at akka.actor.Actor$class.aroundReceive$$$capture(Actor.scala:517)

	at akka.actor.Actor$class.aroundReceive(Actor.scala)

	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)

	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)

	at akka.actor.ActorCell.invoke(ActorCell.scala:561)

	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)

	at akka.dispatch.Mailbox.run(Mailbox.scala:225)

	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)

	... 4 more

Caused by: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.

	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:369)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966)

	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)

	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)

	at java.lang.Thread.run(Thread.java:748)

Caused by: io.debezium.DebeziumException: Error processing binlog event

	... 6 more

Caused by: io.debezium.DebeziumException: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:584)

	at io.debezium.pipeline.EventDispatcher.dispatchSchemaChangeEvent(EventDispatcher.java:276)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:579)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352)

	... 5 more

Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)

	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:374)

	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:119)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)

	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)

	at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:117)

	at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.lambda$applySchemaChange$2(MySqlDatabaseSchema.java:168)

	at java.lang.Iterable.forEach(Iterable.java:75)

	at io.debezium.connector.mysql.MySqlDatabaseSchema.applySchemaChange(MySqlDatabaseSchema.java:168)

	at io.debezium.pipeline.EventDispatcher$SchemaChangeEventReceiver.schemaChangeEvent(EventDispatcher.java:462)

	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleQueryEvent$1(MySqlStreamingChangeEventSource.java:581)

	... 8 more

Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type INT16: class java.lang.String for field: "null"

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:245)

	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)

	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)

	... 26 more

**Comment by wangxiaojian1990** [comment]
![1646893372120_8BFF6FF8-F66D-40c6-A2EA-314A663A7F16](https://user-images.githubusercontent.com/24691069/157604184-9a3fbdfa-ab56-48c4-8677-f81a3586ae8c.png)
![lQLPDhs5HBNtqOrNAvjNBg2wesUjOBi-ZHECLj3emMA1AA_1549_760](https://user-images.githubusercontent.com/24691069/157604212-1b67c3d0-38cc-4063-b2f8-245e8f30b637.png)

**Comment by wangxiaojian1990** [comment]
并且 设置 .includeSchemaChanges(false) 也不行，也是会报错，没有忽略DDL语句。全局try catch 也捕获不到异常。

**Comment by leonardBang** [comment]
@wangxiaojian1990 Thanks for reporting this, could you change your description in English so that all developers/users can understand the issue?

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
