### ISSUE TITLE
when use flink1.14.3 ,throw MetricGroup not Found Exception

### ISSUE THREAD

**Issue by ChangjunZhang** [ververica/flink-cdc-connectors#993]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2-SNAPSHOT(master)
 - Database and version: MySQL5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
**Additional Description**
``` java
java.lang.NoSuchMethodError: org.apache.flink.api.connector.source.SourceReaderContext.metricGroup()Lorg/apache/flink/metrics/MetricGroup;
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createReader(MySqlSource.java:134) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.streaming.api.operators.SourceOperator.initReader(SourceOperator.java:264) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask.init(SourceOperatorStreamTask.java:70) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:677) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575) ~[aibee-flink-1.0-SNAPSHOT-1.14-feature-cdc.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]
```
![Uploading WX20220323-211702.png…]()

**Comment by ChangjunZhang** [comment]
It may be a jar package conflict. I appreciate solving it myself first

**Comment by Kdbowtr** [comment]
so whats your solution？which jars
